CREATE TABLE database_alokasi_subsidi (
id SERIAL NOT NULL PRIMARY KEY,
country_id INT NOT NULL,
country_slug VARCHAR(100) NOT NULL UNIQUE,
country_name VARCHAR(100) NOT NULL,
iso VARCHAR(10) NOT NULL,
sub_bbm BOOLEAN NOT NULL DEFAULT true,
sub_listrik BOOLEAN NOT NULL DEFAULT true,
sub_lpg BOOLEAN NOT NULL DEFAULT true,
sub_pdam BOOLEAN NOT NULL DEFAULT true,
sub_pupuk BOOLEAN NOT NULL DEFAULT true,
sub_sembako BOOLEAN NOT NULL DEFAULT true,
sub_bantuan_pangan BOOLEAN NOT NULL DEFAULT true,
sub_pendidikan BOOLEAN NOT NULL DEFAULT true,
sub_bpjs BOOLEAN NOT NULL DEFAULT true,
sub_vaksin BOOLEAN NOT NULL DEFAULT false,
sub_transport_publik BOOLEAN NOT NULL DEFAULT true,
sub_perumahan BOOLEAN NOT NULL DEFAULT true,
sub_ev BOOLEAN NOT NULL DEFAULT false,
sub_kur BOOLEAN NOT NULL DEFAULT true,
sub_pajak_umkm BOOLEAN NOT NULL DEFAULT true,
sub_blt BOOLEAN NOT NULL DEFAULT true,
sub_pensiun BOOLEAN NOT NULL DEFAULT true,
sub_bencana BOOLEAN NOT NULL DEFAULT true
);
INSERT INTO database_alokasi_subsidi
(country_id, country_slug, country_name, iso, sub_bbm, sub_listrik, sub_lpg, sub_pdam, sub_pupuk, sub_sembako, sub_bantuan_pangan, sub_pendidikan, sub_bpjs, sub_vaksin, sub_transport_publik, sub_perumahan, sub_ev, sub_kur, sub_pajak_umkm, sub_blt, sub_pensiun, sub_bencana)
VALUES
(1, 'afrika_selatan', 'Afrika Selatan', 'za', true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, true, true),
(2, 'aljazair', 'Aljazair', 'dz', true, true, true, true, true, true, true, true, false, false, true, true, false, true, true, true, true, true),
(3, 'angola', 'Angola', 'ao', true, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, false, true),
(4, 'benin', 'Benin', 'bj', false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true),
(5, 'botswana', 'Botswana', 'bw', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(6, 'burkina_faso', 'Burkina faso', 'bf', true, true, true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true),
(7, 'burundi', 'Burundi', 'bi', true, true, false, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(8, 'chad', 'Chad', 'td', true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(9, 'djibouti', 'Djibouti', 'dj', true, true, true, true, true, true, true, false, true, false, true, true, false, true, true, true, true, true),
(10, 'eritrea', 'Eritrea', 'er', true, true, true, false, true, true, true, true, true, false, true, true, false, true, false, true, true, true),
(11, 'eswatini', 'Eswatini', 'sz', true, false, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(12, 'ethiopia', 'Ethiopia', 'et', false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true),
(13, 'gabon', 'Gabon', 'ga', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(14, 'gambia', 'Gambia', 'gm', true, true, true, true, true, true, false, true, true, false, true, true, false, false, true, false, true, false),
(15, 'ghana', 'Ghana', 'gh', true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, true, true, true),
(16, 'guinea', 'Guinea', 'gn', true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(17, 'guinea_bissau', 'Guinea bissau', 'gw', false, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true, true),
(18, 'kamerun', 'Kamerun', 'cm', true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, true, true, true),
(19, 'kenya', 'Kenya', 'ke', true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20, 'komoro', 'Komoro', 'km', true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true),
(21, 'kongo', 'Kongo', 'cg', true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true),
(22, 'lesotho', 'Lesotho', 'ls', true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true),
(23, 'liberia', 'Liberia', 'lr', true, true, true, true, true, true, true, true, false, false, true, true, false, false, true, false, true, true),
(24, 'libya', 'Libya', 'ly', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(25, 'madagaskar', 'Madagaskar', 'mg', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(26, 'malawi', 'Malawi', 'mw', false, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, true),
(27, 'mali', 'Mali', 'ml', true, true, true, true, true, true, true, true, false, true, true, true, false, true, true, true, true, true),
(28, 'maroko', 'Maroko', 'ma', true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, false),
(29, 'mauritania', 'Mauritania', 'mr', true, true, true, true, true, false, true, true, true, false, true, true, true, false, true, false, false, true),
(30, 'mauritius', 'Mauritius', 'mu', true, true, true, true, false, true, true, true, true, true, true, true, false, true, true, true, true, true),
(31, 'mesir', 'Mesir', 'eg', true, true, false, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(32, 'mozambik', 'Mozambik', 'mz', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(33, 'namibia', 'Namibia', 'na', true, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, false, true),
(34, 'niger', 'Niger', 'ne', true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true),
(35, 'nigeria', 'Nigeria', 'ng', false, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, true),
(36, 'pantai_gading', 'Pantai gading', 'ci', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(37, 'republik_afrika_tengah', 'Republik afrika tengah', 'cf', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(38, 'republik_demokratik_kongo', 'Republik demokratik kongo', 'cd', true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true),
(39, 'republik_sudan', 'Republik sudan', 'sd', true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, false, true),
(40, 'republik_tanzania', 'Republik tanzania', 'tz', true, true, true, true, true, true, true, true, false, true, true, true, false, false, true, false, true, true),
(41, 'republik_uganda', 'Republik uganda', 'ug', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(42, 'republik_zambia', 'Republik zambia', 'zm', true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true),
(43, 'republik_zimbabwe', 'Republik zimbabwe', 'zw', true, true, true, true, true, true, true, false, true, false, true, true, false, true, true, true, true, true),
(44, 'rwanda', 'Rwanda', 'rw', true, true, false, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(45, 'sao_tome_dan_principe', 'Sao tome dan principe', 'st', true, true, true, true, true, true, true, false, true, false, true, true, false, false, true, false, true, true),
(46, 'senegal', 'Senegal', 'sn', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(47, 'seychelles', 'Seychelles', 'sc', true, true, true, false, true, true, true, true, true, false, true, true, false, true, false, true, true, true),
(48, 'sierra_leone', 'Sierra leone', 'sl', true, true, false, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(49, 'somalia', 'Somalia', 'so', true, true, true, true, true, true, true, true, false, false, true, true, false, true, true, true, true, true),
(50, 'sudan_selatan', 'Sudan selatan', 'sd', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(51, 'tanjung_verde', 'Tanjung verde', 'cv', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(52, 'togo', 'Togo', 'tg', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(53, 'tunisia', 'Tunisia', 'tn', true, true, false, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(54, 'afganistan', 'Afganistan', 'af', false, true, true, true, true, true, true, true, true, true, true, false, true, false, true, false, true, true),
(55, 'arab_saudi', 'Arab Saudi', 'sa', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(56, 'armenia', 'Armenia', 'am', true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true),
(57, 'azerbaijan', 'Azerbaijan', 'az', true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(58, 'bahrain', 'Bahrain', 'bh', true, true, true, true, true, true, true, false, true, false, true, true, true, true, true, true, true, true),
(59, 'bangladesh', 'Bangladesh', 'bd', true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, false),
(60, 'bhutan', 'Bhutan', 'bt', true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, true, true),
(61, 'brunei', 'Brunei', 'bn', true, true, true, true, true, false, true, true, true, true, true, true, false, false, true, false, false, true),
(62, 'china', 'China', 'cn', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(63, 'filipina', 'Filipina', 'ph', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(64, 'georgia', 'Georgia', 'ge', true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, false, true),
(65, 'hong_kong', 'Hong kong', 'hk', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(66, 'india', 'India', 'in', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(67, 'indonesia', 'Indonesia', 'id', true, true, true, true, false, true, true, true, true, true, true, true, false, true, true, true, true, true),
(68, 'irak', 'Irak', 'iq', true, false, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true),
(69, 'iran', 'Iran', 'ir', true, true, false, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(70, 'israel', 'Israel', 'il', true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, true, true),
(71, 'jepang', 'Jepang', 'jp', true, true, true, true, true, true, true, false, true, true, true, true, true, false, true, false, true, true),
(72, 'kamboja', 'Kamboja', 'kh', true, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, false, true),
(73, 'kazakhstan', 'Kazakhstan', 'kz', true, true, false, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true),
(74, 'kirgizstan', 'Kirgizstan', 'kg', false, true, true, true, true, true, true, true, true, false, true, false, false, false, true, false, true, true),
(75, 'korea_selatan', 'Korea Selatan', 'kr', true, true, true, true, true, true, true, false, true, false, true, true, false, true, true, true, true, true),
(76, 'korea_utara', 'Korea Utara', 'kp', true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, false),
(77, 'kuwait', 'Kuwait', 'kw', true, true, false, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(78, 'laos', 'Laos', 'la', true, false, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(79, 'lebanon', 'Lebanon', 'lb', true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, true, true),
(80, 'makau', 'Makau', 'mo', true, true, false, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(81, 'malaysia', 'Malaysia', 'my', true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true),
(82, 'maldives', 'Maldives', 'mv', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(83, 'mongolia', 'Mongolia', 'mn', true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, false, true, true),
(84, 'myanmar', 'Myanmar', 'mm', true, true, true, true, true, true, false, true, true, false, true, true, true, true, true, true, true, false),
(85, 'nepal', 'Nepal', 'np', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(86, 'oman', 'Oman', 'om', true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(87, 'pakistan', 'Pakistan', 'pk', true, true, true, true, true, true, true, true, false, true, true, true, false, true, true, true, true, true),
(88, 'palestina', 'Palestina', 'ps', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(89, 'qatar', 'Qatar', 'qa', true, true, true, true, true, true, true, true, true, false, false, true, false, false, true, false, true, true),
(90, 'republik_timor_leste', 'Republik timor leste', 'tl', true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, false),
(91, 'singapura', 'Singapura', 'sg', true, false, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(92, 'sri_lanka', 'Sri lanka', 'lk', true, true, true, true, true, true, false, true, true, false, true, true, false, true, true, true, true, false),
(93, 'suriah', 'Suriah', 'sy', true, true, false, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(94, 'taiwan', 'Taiwan', 'cn-tw', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(95, 'tajikistan', 'Tajikistan', 'tj', true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(96, 'thailand', 'Thailand', 'th', true, true, true, true, true, true, true, false, true, false, true, true, false, true, true, true, true, true),
(97, 'turkmenistan', 'Turkmenistan', 'tm', false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true),
(98, 'uni_emirat_arab', 'Uni emirat arab', 'ae', true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true),
(99, 'uzbekistan', 'Uzbekistan', 'uz', true, true, true, true, true, false, true, true, true, true, true, true, false, false, true, false, false, true),
(100, 'vietnam', 'Vietnam', 'vn', true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(101, 'yaman', 'Yaman', 'ye', false, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, true),
(102, 'yordania', 'Yordania', 'jo', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(103, 'albania', 'Albania', 'al', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(104, 'andorra', 'Andorra', 'ad', true, true, true, true, true, true, false, true, true, false, true, true, true, true, true, true, true, false),
(105, 'austria', 'Austria', 'at', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(106, 'belanda', 'Belanda', 'nl', true, true, true, true, false, true, true, true, true, true, true, true, false, true, true, true, true, true),
(107, 'belarus', 'Belarus', 'by', true, true, true, false, true, true, true, true, true, false, true, true, false, true, false, true, true, true),
(108, 'belgia', 'Belgia', 'be', true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true),
(109, 'bosnia_dan_hercegovina', 'Bosnia dan hercegovina', 'ba', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(110, 'bulgaria', 'Bulgaria', 'bg', true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, true, true, true),
(111, 'ceko', 'Ceko', 'cz', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(112, 'denmark', 'Denmark', 'dk', true, true, true, true, true, true, true, true, false, true, true, true, false, true, true, true, true, true),
(113, 'estonia', 'Estonia', 'ee', true, true, false, true, true, true, true, true, true, true, true, true, false, false, true, false, true, true),
(114, 'finlandia', 'Finlandia', 'fi', true, true, true, true, true, true, true, true, false, false, true, true, false, true, true, true, true, true),
(115, 'gibraltar', 'Gibraltar', 'gi', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(116, 'hungaria', 'Hungaria', 'hu', true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, false),
(117, 'inggris', 'Inggris', 'gb', true, true, true, false, true, true, true, true, true, false, true, true, false, false, false, false, true, true),
(118, 'irlandia', 'Irlandia', 'ie', false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true),
(119, 'islandia', 'Islandia', 'is', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(120, 'italia', 'Italia', 'it', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(121, 'jerman', 'Jerman', 'de', true, true, true, true, true, true, false, true, true, false, true, true, false, true, true, true, true, false),
(122, 'kepulauan_faroe', 'Kepulauan faroe', 'fo', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(123, 'kosovo', 'Kosovo', 'xk', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(124, 'kroasia', 'Kroasia', 'hr', true, true, true, true, false, true, true, true, true, true, true, true, false, false, true, false, true, true),
(125, 'latvia', 'Latvia', 'lv', false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true),
(126, 'liechtenstein', 'Liechtenstein', 'li', true, true, true, true, true, true, false, true, true, false, true, true, false, true, true, true, true, false),
(127, 'lithuania', 'Lithuania', 'lt', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(128, 'luksemburg', 'Luksemburg', 'lu', true, true, true, true, false, true, true, true, true, false, true, true, true, true, true, true, true, true),
(129, 'makedonia_utara', 'Makedonia utara', 'mk', true, false, true, true, true, true, true, true, true, true, true, true, false, false, true, false, true, true),
(130, 'malta', 'Malta', 'mt', true, true, true, true, true, true, true, false, true, false, true, true, false, true, true, true, true, true),
(131, 'moldova', 'Moldova', 'md', false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true),
(132, 'monako', 'Monako', 'mc', true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, true, true),
(133, 'montenegro', 'Montenegro', 'me', true, true, true, true, true, true, true, true, false, false, true, true, false, true, true, true, true, true),
(134, 'norwegia', 'Norwegia', 'no', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(135, 'polandia', 'Polandia', 'pl', true, false, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(136, 'portugal', 'Portugal', 'pt', false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true),
(137, 'prancis', 'Prancis', 'fr', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(138, 'republik_rumania', 'Republik rumania', 'ro', true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, true, true, true),
(139, 'republik_serbia', 'Republik serbia', 'rs', true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true),
(140, 'rusia', 'Rusia', 'ru', true, true, true, false, true, true, true, true, true, true, true, true, true, false, false, false, true, true),
(141, 'san_marino', 'San marino', 'sm', true, true, true, true, true, true, true, true, false, true, true, true, false, true, true, true, true, true),
(142, 'siprus', 'Siprus', 'cy', true, true, true, true, true, true, true, true, true, false, true, true, true, false, true, false, true, true),
(143, 'slovenia', 'Slovenia', 'si', true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true),
(144, 'slowakia', 'Slowakia', 'sk', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(145, 'spanyol', 'Spanyol', 'es', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(146, 'swedia', 'Swedia', 'se', true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(147, 'swiss', 'Swiss', 'ch', false, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true, true),
(148, 'turki', 'Turki', 'tr', true, false, true, true, true, true, true, true, true, false, true, true, true, false, true, false, true, true),
(149, 'ukraina', 'Ukraina', 'ua', true, true, true, true, true, true, true, true, false, false, true, true, false, true, true, true, true, true),
(150, 'vatikan', 'Vatikan', 'va', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(151, 'yunani', 'Yunani', 'gr', true, true, true, true, true, true, true, true, true, false, true, true, false, false, true, false, true, true),
(152, 'amerika_serikat', 'Amerika Serikat', 'us', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(153, 'antigua_dan_barbuda', 'Antigua dan Barbuda', 'ag', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(154, 'bahama', 'Bahama', 'bs', true, true, true, true, true, true, true, true, false, true, true, true, false, false, true, false, true, true),
(155, 'barbados', 'Barbados', 'bb', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(156, 'belize', 'Belize', 'bz', true, false, true, true, true, true, true, true, true, false, true, true, false, false, true, false, true, true),
(157, 'bermuda', 'Bermuda', 'bm', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(158, 'costa_rica', 'Costa rica', 'cr', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(159, 'curacao', 'Curacao', 'cw', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(160, 'dominika', 'Dominika', 'dm', true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, false),
(161, 'el_salvador', 'El salvador', 'sv', true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true),
(162, 'greenland', 'Greenland', 'gl', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(163, 'grenada', 'Grenada', 'gd', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(164, 'guatemala', 'Guatemala', 'gt', true, true, false, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(165, 'haiti', 'Haiti', 'ht', true, true, true, true, true, true, true, true, false, true, true, true, false, true, true, true, true, true),
(166, 'honduras', 'Honduras', 'hn', true, true, true, true, true, true, true, false, true, false, true, true, false, true, true, true, true, true),
(167, 'jamaika', 'Jamaika', 'jm', true, true, true, true, true, true, true, true, false, false, true, true, false, true, true, true, true, true),
(168, 'kanada', 'Kanada', 'ca', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(169, 'kuba', 'Kuba', 'cu', true, true, true, false, true, true, true, true, true, false, true, true, true, true, false, true, true, true),
(170, 'meksiko', 'Meksiko', 'mx', true, true, true, false, true, true, true, true, true, false, true, true, false, true, false, true, true, true),
(171, 'nikaragua', 'Nikaragua', 'ni', true, true, false, true, true, true, true, true, true, false, true, true, false, false, true, false, true, true),
(172, 'panama', 'Panama', 'pa', true, true, true, true, true, true, false, true, true, true, true, true, false, false, true, false, true, false),
(173, 'puerto_rico', 'Puerto rico', 'pr', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(174, 'republik_dominika', 'Republik dominika', 'do', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(175, 'saint_kitts_dan_nevis', 'Saint kitts dan nevis', 'kn', true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(176, 'saint_lucia', 'Saint lucia', 'lc', false, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, true),
(177, 'saint_vincent_dan_grenadine', 'Saint vincent dan grenadine', 'vc', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(178, 'trinidad_dan_tobago', 'Trinidad dan tobago', 'tt', true, true, true, false, true, true, true, true, true, false, true, true, false, true, false, true, true, true),
(179, 'australia', 'Australia', 'au', false, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, true),
(180, 'fiji', 'Fiji', 'fj', true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true),
(181, 'guam', 'Guam', 'gu', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(182, 'kiribati', 'Kiribati', 'ki', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(183, 'marshall', 'Marshall', 'mh', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(184, 'mikronesia', 'Mikronesia', 'fm', true, false, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(185, 'nauru', 'Nauru', 'nr', true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, true, true, true),
(186, 'palau', 'Palau', 'pw', true, true, true, true, true, true, true, false, true, false, true, true, true, true, true, true, true, true),
(187, 'papua_nugini', 'Papua nugini', 'pg', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(188, 'samoa', 'Samoa', 'ws', true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true),
(189, 'samoa_amerika', 'Samoa amerika', 'ws', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(190, 'selandia_baru', 'Selandia baru', 'nz', true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, false),
(191, 'tahiti', 'Tahiti', 'pf', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(192, 'tonga', 'Tonga', 'to', true, true, true, true, false, true, true, true, true, true, true, true, false, true, true, true, true, true),
(193, 'tuvalu', 'Tuvalu', 'tv', true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, true, true),
(194, 'vanuatu', 'Vanuatu', 'vu', true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, true, true, true),
(195, 'argentina', 'Argentina', 'ar', true, true, false, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(196, 'bolivia', 'Bolivia', 'bo', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(197, 'brazil', 'Brazil', 'br', true, true, true, true, true, true, false, true, true, false, true, true, false, true, true, true, true, false),
(198, 'chile', 'Chile', 'cl', false, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, true),
(199, 'ekuador', 'Ekuador', 'ec', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(200, 'guiana_prancis', 'Guiana prancis', 'gf', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(201, 'guyana', 'Guyana', 'gy', true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(202, 'kolombia', 'Kolombia', 'co', true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(203, 'paraguay', 'Paraguay', 'py', true, true, true, true, false, true, true, true, true, true, true, true, false, true, true, true, true, true),
(204, 'peru', 'Peru', 'pe', true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true),
(205, 'suriname', 'Suriname', 'sr', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(206, 'uruguay', 'Uruguay', 'uy', true, true, true, true, true, true, false, true, true, false, true, true, false, true, true, true, true, false),
(207, 'venezuela', 'Venezuela', 've', true, true, false, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true);
-- ========================================================
