-- ========================================================
-- DATABASE ALOKASI & KEBIJAKAN SUBSIDI (207 NEGARA)
-- File: d:\project-sendiri\em\json\database_alokasi_subsidi\database_alokasi_subsidi.sql
-- Description: Menyimpan status aktif (true/false) 18 kartu subsidi untuk 207 negara
-- ========================================================

DROP TABLE IF EXISTS database_alokasi_subsidi;
CREATE TABLE IF NOT EXISTS database_alokasi_subsidi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    country_id INT NOT NULL,
    country_slug VARCHAR(100) NOT NULL UNIQUE,
    country_name VARCHAR(100) NOT NULL,
    iso VARCHAR(10) NOT NULL,
    sub_bbm BOOLEAN NOT NULL DEFAULT true,
    sub_listrik BOOLEAN NOT NULL DEFAULT true,
    sub_lpg BOOLEAN NOT NULL DEFAULT true,
    sub_pdam BOOLEAN NOT NULL DEFAULT true,
    sub_pupuk BOOLEAN NOT NULL DEFAULT true,
    sub_sembako BOOLEAN NOT NULL DEFAULT true,
    sub_bantuan_pangan BOOLEAN NOT NULL DEFAULT true,
    sub_pendidikan BOOLEAN NOT NULL DEFAULT true,
    sub_bpjs BOOLEAN NOT NULL DEFAULT true,
    sub_vaksin BOOLEAN NOT NULL DEFAULT false,
    sub_transport_publik BOOLEAN NOT NULL DEFAULT true,
    sub_perumahan BOOLEAN NOT NULL DEFAULT true,
    sub_ev BOOLEAN NOT NULL DEFAULT false,
    sub_kur BOOLEAN NOT NULL DEFAULT true,
    sub_pajak_umkm BOOLEAN NOT NULL DEFAULT true,
    sub_blt BOOLEAN NOT NULL DEFAULT true,
    sub_pensiun BOOLEAN NOT NULL DEFAULT true,
    sub_bencana BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO database_alokasi_subsidi 
(country_id, country_slug, country_name, iso, sub_bbm, sub_listrik, sub_lpg, sub_pdam, sub_pupuk, sub_sembako, sub_bantuan_pangan, sub_pendidikan, sub_bpjs, sub_vaksin, sub_transport_publik, sub_perumahan, sub_ev, sub_kur, sub_pajak_umkm, sub_blt, sub_pensiun, sub_bencana) 
VALUES
(21869, 'afganistan', 'Afganistan', 'af', false, true, true, true, true, true, true, true, true, true, true, false, true, false, true, false, true, true),
(29240, 'afrika-selatan', 'Afrika selatan', 'za', true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, true, true),
(93002, 'albania', 'Albania', 'al', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20793, 'aljazair', 'Aljazair', 'dz', true, true, true, true, true, true, true, true, false, false, true, true, false, true, true, true, true, true),
(20257, 'amerika-serikat', 'Amerika serikat', 'us', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(34293, 'andorra', 'Andorra', 'ad', true, true, true, true, true, true, false, true, true, false, true, true, true, true, true, true, true, false),
(20427, 'angola', 'Angola', 'ao', true, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, false, true),
(10222, 'antigua-dan-barbuda', 'Antigua dan barbuda', 'ag', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(21021, 'arab-saudi', 'Arab saudi', 'sa', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(20367, 'argentina', 'Argentina', 'ar', true, true, false, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20977, 'armenia', 'Armenia', 'am', true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true),
(20448, 'australia', 'Australia', 'au', false, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, true),
(20456, 'austria', 'Austria', 'at', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(20835, 'azerbaijan', 'Azerbaijan', 'az', true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(21714, 'bahama', 'Bahama', 'bs', true, true, true, true, true, true, true, true, false, true, true, true, false, false, true, false, true, true),
(20836, 'bahrain', 'Bahrain', 'bh', true, true, true, true, true, true, true, false, true, false, true, true, true, true, true, true, true, true),
(20465, 'bangladesh', 'Bangladesh', 'bd', true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, false),
(20469, 'barbados', 'Barbados', 'bb', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(20474, 'belanda', 'Belanda', 'nl', true, true, true, true, false, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20478, 'belarus', 'Belarus', 'by', true, true, true, false, true, true, true, true, true, false, true, true, false, true, false, true, true, true),
(20482, 'belgia', 'Belgia', 'be', true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true),
(20486, 'belize', 'Belize', 'bz', true, false, true, true, true, true, true, true, true, false, true, true, false, false, true, false, true, true),
(20490, 'benin', 'Benin', 'bj', false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true),
(20494, 'bhutan', 'Bhutan', 'bt', true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, true, true),
(20500, 'bolivia', 'Bolivia', 'bo', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20505, 'bosnia-dan-herzegovina', 'Bosnia dan herzegovina', 'ba', true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true),
(20510, 'botswana', 'Botswana', 'bw', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(20515, 'brazil', 'Brazil', 'br', true, true, true, true, true, true, false, true, true, false, true, true, false, true, true, true, true, false),
(20520, 'brunei', 'Brunei', 'bn', true, true, true, true, true, false, true, true, true, true, true, true, false, false, true, false, false, true),
(20525, 'bulgaria', 'Bulgaria', 'bg', true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20530, 'burkina-faso', 'Burkina faso', 'bf', true, true, true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true),
(20535, 'burundi', 'Burundi', 'bi', true, true, false, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20540, 'tchad', 'Chad', 'td', true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20545, 'chile', 'Chile', 'cl', false, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, true),
(20550, 'china', 'China', 'cn', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(20555, 'cyprus', 'Cyprus', 'cy', true, true, true, true, true, true, true, true, true, false, true, true, true, false, true, false, true, true),
(20560, 'denmark', 'Denmark', 'dk', true, true, true, true, true, true, true, true, false, true, true, true, false, true, true, true, true, true),
(20565, 'djibouti', 'Djibouti', 'dj', true, true, true, true, true, true, true, false, true, false, true, true, false, true, true, true, true, true),
(20570, 'dominika', 'Dominika', 'dm', true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, false),
(20575, 'ekuador', 'Ekuador', 'ec', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(20580, 'el-salvador', 'El salvador', 'sv', true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true),
(20585, 'eritrea', 'Eritrea', 'er', true, true, true, false, true, true, true, true, true, false, true, true, false, true, false, true, true, true),
(20590, 'estonia', 'Estonia', 'ee', true, true, false, true, true, true, true, true, true, true, true, true, false, false, true, false, true, true),
(20595, 'eswatini', 'Eswatini', 'sz', true, false, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20600, 'ethiopia', 'Ethiopia', 'et', false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true),
(20605, 'fiji', 'Fiji', 'fj', true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true),
(20610, 'filipina', 'Filipina', 'ph', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20615, 'finlandia', 'Finlandia', 'fi', true, true, true, true, true, true, true, true, false, false, true, true, false, true, true, true, true, true),
(20620, 'gabon', 'Gabon', 'ga', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(20625, 'gambia', 'Gambia', 'gm', true, true, true, true, true, true, false, true, true, false, true, true, false, false, true, false, true, false),
(20630, 'georgia', 'Georgia', 'ge', true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, false, true),
(20635, 'ghana', 'Ghana', 'gh', true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20640, 'grenada', 'Grenada', 'gd', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(20645, 'guatemala', 'Guatemala', 'gt', true, true, false, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20650, 'guinea', 'Guinea', 'gn', true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20655, 'guinea-bissau', 'Guinea-bissau', 'gw', false, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true, true),
(20660, 'guinea-khatulistiwa', 'Guinea khatulistiwa', 'gq', true, true, true, true, true, true, true, true, true, true, false, true, false, false, true, false, true, true),
(20665, 'guyana', 'Guyana', 'gy', true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20670, 'haiti', 'Haiti', 'ht', true, true, true, true, true, true, true, true, false, true, true, true, false, true, true, true, true, true),
(20675, 'honduras', 'Honduras', 'hn', true, true, true, true, true, true, true, false, true, false, true, true, false, true, true, true, true, true),
(20680, 'hungaria', 'Hungaria', 'hu', true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, false),
(20685, 'india', 'India', 'in', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(20690, 'indonesia', 'Indonesia', 'id', true, true, true, true, false, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20695, 'inggris', 'Inggris', 'gb', true, true, true, false, true, true, true, true, true, false, true, true, false, false, false, false, true, true),
(20700, 'iran', 'Iran', 'ir', true, true, false, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20705, 'irak', 'Irak', 'iq', true, false, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true),
(20710, 'irlandia', 'Irlandia', 'ie', false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true),
(20715, 'israel', 'Israel', 'il', true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, true, true),
(20720, 'italia', 'Italia', 'it', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20725, 'jamaika', 'Jamaika', 'jm', true, true, true, true, true, true, true, true, false, false, true, true, false, true, true, true, true, true),
(20730, 'jepang', 'Jepang', 'jp', true, true, true, true, true, true, true, false, true, true, true, true, true, false, true, false, true, true),
(20735, 'jerman', 'Jerman', 'de', true, true, true, true, true, true, false, true, true, false, true, true, false, true, true, true, true, false),
(20740, 'kamboja', 'Kamboja', 'kh', true, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, false, true),
(20745, 'kamerun', 'Kamerun', 'cm', true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20750, 'kanada', 'Kanada', 'ca', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(20755, 'kazakhstan', 'Kazakhstan', 'kz', true, true, false, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true),
(20760, 'kenya', 'Kenya', 'ke', true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20765, 'kirgizstan', 'Kirgizstan', 'kg', false, true, true, true, true, true, true, true, true, false, true, false, false, false, true, false, true, true),
(20770, 'kiribati', 'Kiribati', 'ki', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(20775, 'kolombia', 'Kolombia', 'co', true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20780, 'komoro', 'Komoro', 'km', true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true),
(20785, 'korea-selatan', 'Korea selatan', 'kr', true, true, true, true, true, true, true, false, true, false, true, true, false, true, true, true, true, true),
(20790, 'korea-utara', 'Korea utara', 'kp', true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, false),
(20795, 'kosta-rika', 'Kosta rika', 'cr', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(20800, 'kroasia', 'Kroasia', 'hr', true, true, true, true, false, true, true, true, true, true, true, true, false, false, true, false, true, true),
(20805, 'kuba', 'Kuba', 'cu', true, true, true, false, true, true, true, true, true, false, true, true, true, true, false, true, true, true),
(20810, 'kuwait', 'Kuwait', 'kw', true, true, false, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20815, 'laos', 'Laos', 'la', true, false, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20820, 'latvia', 'Latvia', 'lv', false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true),
(20825, 'lebanon', 'Lebanon', 'lb', true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, true, true),
(20830, 'lesotho', 'Lesotho', 'ls', true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true),
(20840, 'liberia', 'Liberia', 'lr', true, true, true, true, true, true, true, true, false, false, true, true, false, false, true, false, true, true),
(20845, 'libya', 'Libya', 'ly', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(20850, 'liechtenstein', 'Liechtenstein', 'li', true, true, true, true, true, true, false, true, true, false, true, true, false, true, true, true, true, false),
(20855, 'lituania', 'Lituania', 'lt', true, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, false, true),
(20860, 'luksemburg', 'Luksemburg', 'lu', true, true, true, true, false, true, true, true, true, false, true, true, true, true, true, true, true, true),
(20865, 'madagaskar', 'Madagaskar', 'mg', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(20870, 'makau', 'Makau', 'mo', true, true, false, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20875, 'makedonia-utara', 'Makedonia utara', 'mk', true, false, true, true, true, true, true, true, true, true, true, true, false, false, true, false, true, true),
(20880, 'malawi', 'Malawi', 'mw', false, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, true),
(20885, 'malaysia', 'Malaysia', 'my', true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true),
(20890, 'maladewa', 'Maladewa', 'mv', true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20895, 'mali', 'Mali', 'ml', true, true, true, true, true, true, true, true, false, true, true, true, false, true, true, true, true, true),
(20900, 'malta', 'Malta', 'mt', true, true, true, true, true, true, true, false, true, false, true, true, false, true, true, true, true, true),
(20905, 'maroko', 'Maroko', 'ma', true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, false),
(20910, 'mauritania', 'Mauritania', 'mr', true, true, true, true, true, false, true, true, true, false, true, true, true, false, true, false, false, true),
(20915, 'mauritius', 'Mauritius', 'mu', true, true, true, true, false, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20920, 'meksiko', 'Meksiko', 'mx', true, true, true, false, true, true, true, true, true, false, true, true, false, true, false, true, true, true),
(20925, 'mesir', 'Mesir', 'eg', true, true, false, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(20930, 'mikronesia', 'Mikronesia', 'fm', true, false, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20935, 'moldova', 'Moldova', 'md', false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true),
(20940, 'monako', 'Monako', 'mc', true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, true, true),
(20945, 'mongolia', 'Mongolia', 'mn', true, true, true, true, true, true, true, true, true, true, true, true, false, false, true, false, true, true),
(20950, 'montenegro', 'Montenegro', 'me', true, true, true, true, true, true, true, true, false, false, true, true, false, true, true, true, true, true),
(20955, 'mozambik', 'Mozambik', 'mz', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(20960, 'myanmar', 'Myanmar', 'mm', true, true, true, true, true, true, false, true, true, false, true, true, true, true, true, true, true, false),
(20965, 'namibia', 'Namibia', 'na', true, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, false, true),
(20970, 'nauru', 'Nauru', 'nr', true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, true, true, true),
(20975, 'nepal', 'Nepal', 'np', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(20980, 'nikaragua', 'Nikaragua', 'ni', true, true, false, true, true, true, true, true, true, false, true, true, false, false, true, false, true, true),
(20985, 'niger', 'Niger', 'ne', true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true),
(20990, 'nigeria', 'Nigeria', 'ng', false, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, true),
(20995, 'norwegia', 'Norwegia', 'no', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(21000, 'oman', 'Oman', 'om', true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(21005, 'pakistan', 'Pakistan', 'pk', true, true, true, true, true, true, true, true, false, true, true, true, false, true, true, true, true, true),
(21010, 'palau', 'Palau', 'pw', true, true, true, true, true, true, true, false, true, false, true, true, true, true, true, true, true, true),
(21015, 'panama', 'Panama', 'pa', true, true, true, true, true, true, false, true, true, true, true, true, false, false, true, false, true, false),
(21020, 'papua-nugini', 'Papua nugini', 'pg', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(21025, 'paraguay', 'Paraguay', 'py', true, true, true, true, false, true, true, true, true, true, true, true, false, true, true, true, true, true),
(21030, 'perancis', 'Prancis', 'fr', true, true, true, false, true, true, true, true, true, false, true, true, false, true, false, true, true, true),
(21035, 'peru', 'Peru', 'pe', true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true),
(21040, 'polandia', 'Polandia', 'pl', true, false, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(21045, 'portugal', 'Portugal', 'pt', false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true),
(21050, 'qatar', 'Qatar', 'qa', true, true, true, true, true, true, true, true, true, false, false, true, false, false, true, false, true, true),
(21055, 'republik-afrika-tengah', 'Republik afrika tengah', 'cf', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(21060, 'republik-demokratik-kongo', 'Republik demokratik kongo', 'cd', true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true, true),
(21065, 'republik-dominika', 'Republik dominika', 'do', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(21070, 'republik-kongo', 'Republik kongo', 'cg', true, true, true, true, true, true, false, true, true, false, true, true, false, true, true, true, true, false),
(21075, 'republik-ceko', 'Ceko', 'cz', true, true, true, true, true, false, true, true, true, true, true, true, false, true, true, true, false, true),
(21080, 'rumania', 'Rumania', 'ro', true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, true, true, true),
(21085, 'rusia', 'Rusia', 'ru', true, true, true, false, true, true, true, true, true, true, true, true, true, false, false, false, true, true),
(21090, 'rwanda', 'Rwanda', 'rw', true, true, false, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(21095, 'saint-kitts-dan-nevis', 'Saint kitts dan nevis', 'kn', true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(21100, 'saint-lucia', 'Saint lucia', 'lc', false, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, true),
(21105, 'saint-vincent-dan-grenadine', 'Saint vincent dan grenadine', 'vc', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(21110, 'samoa', 'Samoa', 'ws', true, true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true),
(21115, 'san-marino', 'San marino', 'sm', true, true, true, true, true, true, true, true, false, true, true, true, false, true, true, true, true, true),
(21120, 'sao-tome-dan-principe', 'Sao tome dan principe', 'st', true, true, true, true, true, true, true, false, true, false, true, true, false, false, true, false, true, true),
(21125, 'selandia-baru', 'Selandia baru', 'nz', true, true, true, true, true, true, false, true, true, true, true, true, false, true, true, true, true, false),
(21130, 'senegal', 'Senegal', 'sn', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(21135, 'serbia', 'Serbia', 'rs', true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true),
(21140, 'seychelles', 'Seychelles', 'sc', true, true, true, false, true, true, true, true, true, false, true, true, false, true, false, true, true, true),
(21145, 'sierra-leone', 'Sierra leone', 'sl', true, true, false, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(21150, 'singapura', 'Singapura', 'sg', true, false, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(21155, 'siprus-utara', 'Siprus utara', 'cy', false, true, true, true, true, true, true, true, true, true, true, false, false, false, true, false, true, true),
(21160, 'slovenia', 'Slovenia', 'si', true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true, true, true),
(21165, 'slovakia', 'Slovakia', 'sk', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(21170, 'somalia', 'Somalia', 'so', true, true, true, true, true, true, true, true, false, false, true, true, false, true, true, true, true, true),
(21175, 'spanyol', 'Spanyol', 'es', true, true, true, true, true, true, true, false, true, true, true, true, false, true, true, true, true, true),
(21180, 'sri-lanka', 'Sri lanka', 'lk', true, true, true, true, true, true, false, true, true, false, true, true, false, true, true, true, true, false),
(21185, 'sudan', 'Sudan', 'sd', true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, false, true),
(21190, 'sudan-selatan', 'Sudan selatan', 'ss', true, true, true, true, false, true, true, true, true, false, true, true, false, false, true, false, true, true),
(21195, 'suriname', 'Suriname', 'sr', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(21200, 'suriah', 'Suriah', 'sy', true, true, false, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(21205, 'swedia', 'Swedia', 'se', true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(21210, 'swiss', 'Swiss', 'ch', false, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true, true),
(21215, 'taiwan', 'Taiwan', 'tw', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(21220, 'tajikistan', 'Tajikistan', 'tj', true, true, true, true, true, true, true, true, true, false, true, true, false, true, true, true, true, true),
(21225, 'tanzania', 'Tanzania', 'tz', true, true, true, true, true, true, true, true, false, true, true, true, false, false, true, false, true, true),
(21230, 'thailand', 'Thailand', 'th', true, true, true, true, true, true, true, false, true, false, true, true, false, true, true, true, true, true),
(21235, 'timor-leste', 'Timor leste', 'tl', true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true, false),
(21240, 'togo', 'Togo', 'tg', true, true, true, true, true, false, true, true, true, false, true, true, false, true, true, true, false, true),
(21245, 'tonga', 'Tonga', 'to', true, true, true, true, false, true, true, true, true, true, true, true, false, true, true, true, true, true),
(21250, 'trinidad-dan-tobago', 'Trinidad dan tobago', 'tt', true, true, true, false, true, true, true, true, true, false, true, true, false, true, false, true, true, true),
(21255, 'tunisia', 'Tunisia', 'tn', true, true, false, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(21260, 'turki', 'Turki', 'tr', true, false, true, true, true, true, true, true, true, false, true, true, true, false, true, false, true, true),
(21265, 'turkmenistan', 'Turkmenistan', 'tm', false, true, true, true, true, true, true, true, true, true, true, false, false, true, true, true, true, true),
(21270, 'tuvalu', 'Tuvalu', 'tv', true, true, true, true, true, true, true, true, true, false, false, true, false, true, true, true, true, true),
(21275, 'uganda', 'Uganda', 'ug', true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(21280, 'ukraina', 'Ukraina', 'ua', true, true, true, true, true, true, true, true, false, false, true, true, false, true, true, true, true, true),
(21285, 'uni-emirat-arab', 'Uni emirat arab', 'ae', true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true, true),
(21290, 'uruguay', 'Uruguay', 'uy', true, true, true, true, true, true, false, true, true, false, true, true, false, true, true, true, true, false),
(21295, 'uzbekistan', 'Uzbekistan', 'uz', true, true, true, true, true, false, true, true, true, true, true, true, false, false, true, false, false, true),
(21300, 'vanuatu', 'Vanuatu', 'vu', true, true, true, true, false, true, true, true, true, false, true, true, false, true, true, true, true, true),
(21305, 'vatikan', 'Vatikan', 'va', true, true, true, false, true, true, true, true, true, true, true, true, false, true, false, true, true, true),
(21310, 'venezuela', 'Venezuela', 've', true, true, false, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true),
(21315, 'vietnam', 'Vietnam', 'vn', true, false, true, true, true, true, true, true, true, true, true, true, false, true, true, true, true, true),
(21320, 'yaman', 'Yaman', 'ye', false, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, true),
(21325, 'yordania', 'Yordania', 'jo', true, true, true, true, true, true, true, true, true, true, false, true, false, true, true, true, true, true),
(21330, 'yunani', 'Yunani', 'gr', true, true, true, true, true, true, true, true, true, false, true, true, false, false, true, false, true, true),
(21335, 'zambia', 'Zambia', 'zm', true, true, true, true, true, true, true, true, false, true, true, true, true, true, true, true, true, true),
(21340, 'zimbabwe', 'Zimbabwe', 'zw', true, true, true, true, true, true, true, false, true, false, true, true, false, true, true, true, true, true);
