export interface StaticPbbVoteEntry {
  name_id: string;
  un_vote: number;
}

export const STATIC_PBB_VOTES: StaticPbbVoteEntry[] = [
  { name_id: "Afganistan", un_vote: 131 },
  { name_id: "Afrika Selatan", un_vote: 193 },
  { name_id: "Albania", un_vote: 82 },
  { name_id: "Aljazair", un_vote: 89 },
  { name_id: "Amerika Serikat", un_vote: 208 },
  { name_id: "Andorra", un_vote: 16 },
  { name_id: "Angola", un_vote: 160 },
  { name_id: "Antigua dan Barbuda", un_vote: 17 },
  { name_id: "Arab Saudi", un_vote: 168 },
  { name_id: "Argentina", un_vote: 195 },
  { name_id: "Armenia", un_vote: 157 },
  { name_id: "Australia", un_vote: 117 },
  { name_id: "Austria", un_vote: 197 },
  { name_id: "Azerbaijan", un_vote: 145 },
  { name_id: "Bahama", un_vote: 175 },
  { name_id: "Bahrain", un_vote: 101 },
  { name_id: "Bangladesh", un_vote: 123 },
  { name_id: "Barbados", un_vote: 15 },
  { name_id: "Belanda", un_vote: 201 },
  { name_id: "Belarus", un_vote: 107 },
  { name_id: "Belgia", un_vote: 194 },
  { name_id: "Belize", un_vote: 20 },
  { name_id: "Benin", un_vote: 67 },
  { name_id: "Bermuda", un_vote: 27 },
  { name_id: "Bhutan", un_vote: 154 },
  { name_id: "Bolivia", un_vote: 73 },
  { name_id: "Bosnia dan hercegovina", un_vote: 149 },
  { name_id: "Botswana", un_vote: 53 },
  { name_id: "Brazil", un_vote: 211 },
  { name_id: "Brunei", un_vote: 119 },
  { name_id: "Bulgaria", un_vote: 47 },
  { name_id: "Burkina faso", un_vote: 51 },
  { name_id: "Burundi", un_vote: 42 },
  { name_id: "Ceko", un_vote: 31 },
  { name_id: "Chad", un_vote: 63 },
  { name_id: "Chile", un_vote: 152 },
  { name_id: "China", un_vote: 206 },
  { name_id: "Costa rica", un_vote: 77 },
  { name_id: "Curacao", un_vote: 21 },
  { name_id: "Denmark", un_vote: 189 },
  { name_id: "Djibouti", un_vote: 18 },
  { name_id: "Dominika", un_vote: 59 },
  { name_id: "Ekuador", un_vote: 37 },
  { name_id: "El salvador", un_vote: 84 },
  { name_id: "Eritrea", un_vote: 52 },
  { name_id: "Estonia", un_vote: 173 },
  { name_id: "Eswatini", un_vote: 65 },
  { name_id: "Ethiopia", un_vote: 75 },
  { name_id: "Fiji", un_vote: 118 },
  { name_id: "Filipina", un_vote: 144 },
  { name_id: "Finlandia", un_vote: 161 },
  { name_id: "Gabon", un_vote: 78 },
  { name_id: "Gambia", un_vote: 121 },
  { name_id: "Georgia", un_vote: 132 },
  { name_id: "Ghana", un_vote: 130 },
  { name_id: "Gibraltar", un_vote: 28 },
  { name_id: "Greenland", un_vote: 48 },
  { name_id: "Grenada", un_vote: 68 },
  { name_id: "Guam", un_vote: 156 },
  { name_id: "Guatemala", un_vote: 147 },
  { name_id: "Guiana prancis", un_vote: 44 },
  { name_id: "Guinea", un_vote: 54 },
  { name_id: "Guinea bissau", un_vote: 105 },
  { name_id: "Guyana", un_vote: 79 },
  { name_id: "Haiti", un_vote: 110 },
  { name_id: "Honduras", un_vote: 142 },
  { name_id: "Hong kong", un_vote: 32 },
  { name_id: "Hungaria", un_vote: 99 },
  { name_id: "India", un_vote: 209 },
  { name_id: "Indonesia", un_vote: 133 },
  { name_id: "Inggris", un_vote: 186 },
  { name_id: "Irak", un_vote: 137 },
  { name_id: "Iran", un_vote: 196 },
  { name_id: "Irlandia", un_vote: 158 },
  { name_id: "Islandia", un_vote: 108 },
  { name_id: "Israel", un_vote: 204 },
  { name_id: "Italia", un_vote: 151 },
  { name_id: "Jamaika", un_vote: 62 },
  { name_id: "Jepang", un_vote: 212 },
  { name_id: "Jerman", un_vote: 202 },
  { name_id: "Kamboja", un_vote: 171 },
  { name_id: "Kamerun", un_vote: 143 },
  { name_id: "Kanada", un_vote: 165 },
  { name_id: "Kazakhstan", un_vote: 192 },
  { name_id: "Kenya", un_vote: 174 },
  { name_id: "Kepulauan faroe", un_vote: 23 },
  { name_id: "Kirgizstan", un_vote: 24 },
  { name_id: "Kiribati", un_vote: 7 },
  { name_id: "Kolombia", un_vote: 178 },
  { name_id: "Komoro", un_vote: 66 },
  { name_id: "Kongo", un_vote: 58 },
  { name_id: "Korea Selatan", un_vote: 190 },
  { name_id: "Korea Utara", un_vote: 61 },
  { name_id: "Kosovo", un_vote: 12 },
  { name_id: "Kroasia", un_vote: 134 },
  { name_id: "Kuba", un_vote: 176 },
  { name_id: "Kuwait", un_vote: 162 },
  { name_id: "Laos", un_vote: 26 },
  { name_id: "Latvia", un_vote: 169 },
  { name_id: "Lebanon", un_vote: 188 },
  { name_id: "Lesotho", un_vote: 120 },
  { name_id: "Liberia", un_vote: 98 },
  { name_id: "Libya", un_vote: 113 },
  { name_id: "Liechtenstein", un_vote: 25 },
  { name_id: "Lithuania", un_vote: 179 },
  { name_id: "Luksemburg", un_vote: 72 },
  { name_id: "Madagaskar", un_vote: 92 },
  { name_id: "Makau", un_vote: 13 },
  { name_id: "Makedonia utara", un_vote: 177 },
  { name_id: "Malawi", un_vote: 40 },
  { name_id: "Malaysia", un_vote: 146 },
  { name_id: "Maldives", un_vote: 150 },
  { name_id: "Mali", un_vote: 111 },
  { name_id: "Malta", un_vote: 126 },
  { name_id: "Maroko", un_vote: 114 },
  { name_id: "Marshall", un_vote: 9 },
  { name_id: "Mauritania", un_vote: 129 },
  { name_id: "Mauritius", un_vote: 74 },
  { name_id: "Meksiko", un_vote: 191 },
  { name_id: "Mesir", un_vote: 164 },
  { name_id: "Mikronesia", un_vote: 19 },
  { name_id: "Moldova", un_vote: 43 },
  { name_id: "Monako", un_vote: 93 },
  { name_id: "Mongolia", un_vote: 139 },
  { name_id: "Montenegro", un_vote: 109 },
  { name_id: "Mozambik", un_vote: 90 },
  { name_id: "Myanmar", un_vote: 60 },
  { name_id: "Namibia", un_vote: 33 },
  { name_id: "Nauru", un_vote: 57 },
  { name_id: "Nepal", un_vote: 94 },
  { name_id: "Niger", un_vote: 35 },
  { name_id: "Nigeria", un_vote: 180 },
  { name_id: "Nikaragua", un_vote: 167 },
  { name_id: "Norwegia", un_vote: 166 },
  { name_id: "Oman", un_vote: 170 },
  { name_id: "Pakistan", un_vote: 185 },
  { name_id: "Palau", un_vote: 49 },
  { name_id: "Palestina", un_vote: 45 },
  { name_id: "Panama", un_vote: 125 },
  { name_id: "Pantai gading", un_vote: 56 },
  { name_id: "Papua nugini", un_vote: 135 },
  { name_id: "Paraguay", un_vote: 76 },
  { name_id: "Peru", un_vote: 46 },
  { name_id: "Polandia", un_vote: 205 },
  { name_id: "Portugal", un_vote: 199 },
  { name_id: "Prancis", un_vote: 207 },
  { name_id: "Puerto rico", un_vote: 122 },
  { name_id: "Qatar", un_vote: 187 },
  { name_id: "Republik afrika tengah", un_vote: 71 },
  { name_id: "Republik demokratik kongo", un_vote: 141 },
  { name_id: "Republik dominika", un_vote: 50 },
  { name_id: "Republik rumania", un_vote: 148 },
  { name_id: "Republik serbia", un_vote: 172 },
  { name_id: "Republik sudan", un_vote: 100 },
  { name_id: "Republik tanzania", un_vote: 183 },
  { name_id: "Republik timor leste", un_vote: 38 },
  { name_id: "Republik uganda", un_vote: 106 },
  { name_id: "Republik zambia", un_vote: 30 },
  { name_id: "Republik zimbabwe", un_vote: 41 },
  { name_id: "Rusia", un_vote: 155 },
  { name_id: "Rwanda", un_vote: 55 },
  { name_id: "Saint kitts dan nevis", un_vote: 69 },
  { name_id: "Saint lucia", un_vote: 22 },
  { name_id: "Saint vincent dan grenadine", un_vote: 115 },
  { name_id: "Samoa", un_vote: 14 },
  { name_id: "Samoa amerika", un_vote: 29 },
  { name_id: "San marino", un_vote: 36 },
  { name_id: "Sao tome dan principe", un_vote: 91 },
  { name_id: "Selandia baru", un_vote: 112 },
  { name_id: "Senegal", un_vote: 124 },
  { name_id: "Seychelles", un_vote: 11 },
  { name_id: "Sierra leone", un_vote: 96 },
  { name_id: "Singapura", un_vote: 153 },
  { name_id: "Siprus", un_vote: 136 },
  { name_id: "Slovenia", un_vote: 83 },
  { name_id: "Slowakia", un_vote: 181 },
  { name_id: "Somalia", un_vote: 103 },
  { name_id: "Spanyol", un_vote: 140 },
  { name_id: "Sri lanka", un_vote: 163 },
  { name_id: "Sudan selatan", un_vote: 97 },
  { name_id: "Suriah", un_vote: 70 },
  { name_id: "Suriname", un_vote: 8 },
  { name_id: "Swedia", un_vote: 95 },
  { name_id: "Swiss", un_vote: 203 },
  { name_id: "Tahiti", un_vote: 86 },
  { name_id: "Taiwan", un_vote: 80 },
  { name_id: "Tajikistan", un_vote: 182 },
  { name_id: "Tanjung verde", un_vote: 102 },
  { name_id: "Thailand", un_vote: 159 },
  { name_id: "Togo", un_vote: 127 },
  { name_id: "Tonga", un_vote: 10 },
  { name_id: "Trinidad dan tobago", un_vote: 128 },
  { name_id: "Tunisia", un_vote: 64 },
  { name_id: "Turki", un_vote: 88 },
  { name_id: "Turkmenistan", un_vote: 138 },
  { name_id: "Tuvalu", un_vote: 34 },
  { name_id: "Ukraina", un_vote: 210 },
  { name_id: "Uni emirat arab", un_vote: 198 },
  { name_id: "Uruguay", un_vote: 104 },
  { name_id: "Uzbekistan", un_vote: 85 },
  { name_id: "Vanuatu", un_vote: 6 },
  { name_id: "Vatikan", un_vote: 39 },
  { name_id: "Venezuela", un_vote: 200 },
  { name_id: "Vietnam", un_vote: 81 },
  { name_id: "Yaman", un_vote: 116 },
  { name_id: "Yordania", un_vote: 87 },
  { name_id: "Yunani", un_vote: 184 },
  { name_id: "Mayotte", un_vote: 1 },
  { name_id: "Reunion", un_vote: 2 },
  { name_id: "Guadeloupe", un_vote: 3 },
  { name_id: "Martinique", un_vote: 4 },
  { name_id: "Bonaire, Sint Eustatius dan Saba", un_vote: 5 },
];
