-- Database SDA SQL Export
-- Total 207 Negara

DROP TABLE IF EXISTS database_sda;
CREATE TABLE IF NOT EXISTS database_sda (
    id INT PRIMARY KEY,
    country VARCHAR(100) NOT NULL,
    country_slug VARCHAR(100) NOT NULL,
    emas BOOLEAN NOT NULL DEFAULT FALSE,
    uranium BOOLEAN NOT NULL DEFAULT FALSE,
    batu_bara BOOLEAN NOT NULL DEFAULT FALSE,
    minyak_bumi BOOLEAN NOT NULL DEFAULT FALSE,
    gas_alam BOOLEAN NOT NULL DEFAULT FALSE,
    garam BOOLEAN NOT NULL DEFAULT FALSE,
    litium BOOLEAN NOT NULL DEFAULT FALSE,
    logam_tanah_jarang BOOLEAN NOT NULL DEFAULT FALSE,
    bijih_besi BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO database_sda (
    id, country, country_slug, emas, uranium, batu_bara, minyak_bumi, gas_alam, garam, litium, logam_tanah_jarang, bijih_besi
) VALUES
    (1, 'Afrika Selatan', 'afrika_selatan', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (2, 'Aljazair', 'aljazair', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (3, 'Angola', 'angola', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (4, 'Benin', 'benin', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (5, 'Botswana', 'botswana', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (6, 'Burkina Faso', 'burkina_faso', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (7, 'Burundi', 'burundi', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (8, 'Chad', 'chad', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (9, 'Djibouti', 'djibouti', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
    (10, 'Eritrea', 'eritrea', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (11, 'Eswatini', 'eswatini', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (12, 'Ethiopia', 'ethiopia', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (13, 'Gabon', 'gabon', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (14, 'Gambia', 'gambia', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (15, 'Ghana', 'ghana', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (16, 'Guinea', 'guinea', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (17, 'Guinea Bissau', 'guinea_bissau', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (18, 'Kamerun', 'kamerun', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (19, 'Kenya', 'kenya', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE),
    (20, 'Komoro', 'komoro', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (21, 'Kongo', 'kongo', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE),
    (22, 'Lesotho', 'lesotho', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (23, 'Liberia', 'liberia', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (24, 'Libya', 'libya', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (25, 'Madagaskar', 'madagaskar', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (26, 'Malawi', 'malawi', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (27, 'Mali', 'mali', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (28, 'Maroko', 'maroko', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE),
    (29, 'Mauritania', 'mauritania', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE),
    (30, 'Mauritius', 'mauritius', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (31, 'Mesir', 'mesir', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE),
    (32, 'Mozambik', 'mozambik', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (33, 'Namibia', 'namibia', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE),
    (34, 'Niger', 'niger', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (35, 'Nigeria', 'nigeria', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE),
    (36, 'Pantai Gading', 'pantai_gading', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (37, 'Republik Afrika Tengah', 'republik_afrika_tengah', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (38, 'Republik Demokratik Kongo', 'republik_demokratik_kongo', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE),
    (39, 'Republik Sudan', 'republik_sudan', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (40, 'Republik Tanzania', 'republik_tanzania', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (41, 'Republik Uganda', 'republik_uganda', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (42, 'Republik Zambia', 'republik_zambia', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (43, 'Republik Zimbabwe', 'republik_zimbabwe', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE),
    (44, 'Rwanda', 'rwanda', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (45, 'Sao Tome Dan Principe', 'sao_tome_dan_principe', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (46, 'Senegal', 'senegal', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE),
    (47, 'Seychelles', 'seychelles', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (48, 'Sierra Leone', 'sierra_leone', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (49, 'Somalia', 'somalia', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (50, 'Sudan Selatan', 'sudan_selatan', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (51, 'Tanjung Verde', 'tanjung_verde', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (52, 'Togo', 'togo', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (53, 'Tunisia', 'tunisia', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE),
    (54, 'Afganistan', 'afganistan', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (55, 'Arab Saudi', 'arab_saudi', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE),
    (56, 'Armenia', 'armenia', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (57, 'Azerbaijan', 'azerbaijan', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (58, 'Bahrain', 'bahrain', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (59, 'Bangladesh', 'bangladesh', TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (60, 'Bhutan', 'bhutan', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (61, 'Brunei', 'brunei', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (62, 'China', 'china', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (63, 'Filipina', 'filipina', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (64, 'Georgia', 'georgia', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (65, 'Hong Kong', 'hong_kong', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (66, 'India', 'india', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE),
    (67, 'Indonesia', 'indonesia', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (68, 'Irak', 'irak', TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE),
    (69, 'Iran', 'iran', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (70, 'Israel', 'israel', TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE),
    (71, 'Jepang', 'jepang', TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE),
    (72, 'Kamboja', 'kamboja', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (73, 'Kazakhstan', 'kazakhstan', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (74, 'Kirgizstan', 'kirgizstan', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE),
    (75, 'Korea Selatan', 'korea_selatan', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (76, 'Korea Utara', 'korea_utara', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE),
    (77, 'Kuwait', 'kuwait', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (78, 'Laos', 'laos', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (79, 'Lebanon', 'lebanon', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (80, 'Makau', 'makau', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (81, 'Malaysia', 'malaysia', TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (82, 'Maldives', 'maldives', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (83, 'Mongolia', 'mongolia', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (84, 'Myanmar', 'myanmar', TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (85, 'Nepal', 'nepal', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (86, 'Oman', 'oman', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (87, 'Pakistan', 'pakistan', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (88, 'Palestina', 'palestina', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (89, 'Qatar', 'qatar', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (90, 'Republik Timor Leste', 'republik_timor_leste', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (91, 'Singapura', 'singapura', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (92, 'Sri Lanka', 'sri_lanka', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (93, 'Suriah', 'suriah', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (94, 'Taiwan', 'taiwan', TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (95, 'Tajikistan', 'tajikistan', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (96, 'Thailand', 'thailand', TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE),
    (97, 'Turkmenistan', 'turkmenistan', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (98, 'Uni Emirat Arab', 'uni_emirat_arab', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (99, 'Uzbekistan', 'uzbekistan', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (100, 'Vietnam', 'vietnam', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE),
    (101, 'Yaman', 'yaman', TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE),
    (102, 'Yordania', 'yordania', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE),
    (103, 'Albania', 'albania', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE),
    (104, 'Andorra', 'andorra', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (105, 'Austria', 'austria', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (106, 'Belanda', 'belanda', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (107, 'Belarus', 'belarus', TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE),
    (108, 'Belgia', 'belgia', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (109, 'Bosnia Dan Hercegovina', 'bosnia_dan_hercegovina', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (110, 'Bulgaria', 'bulgaria', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (111, 'Ceko', 'ceko', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (112, 'Denmark', 'denmark', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (113, 'Estonia', 'estonia', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (114, 'Finlandia', 'finlandia', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE),
    (115, 'Gibraltar', 'gibraltar', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (116, 'Hungaria', 'hungaria', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (117, 'Inggris', 'inggris', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE),
    (118, 'Irlandia', 'irlandia', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (119, 'Islandia', 'islandia', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (120, 'Italia', 'italia', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (121, 'Jerman', 'jerman', TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE),
    (122, 'Kepulauan Faroe', 'kepulauan_faroe', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (123, 'Kosovo', 'kosovo', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (124, 'Kroasia', 'kroasia', TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
    (125, 'Latvia', 'latvia', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (126, 'Liechtenstein', 'liechtenstein', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (127, 'Lithuania', 'lithuania', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (128, 'Luksemburg', 'luksemburg', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (129, 'Makedonia Utara', 'makedonia_utara', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (130, 'Malta', 'malta', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (131, 'Moldova', 'moldova', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (132, 'Monako', 'monako', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (133, 'Montenegro', 'montenegro', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (134, 'Norwegia', 'norwegia', TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (135, 'Polandia', 'polandia', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE),
    (136, 'Portugal', 'portugal', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (137, 'Prancis', 'prancis', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (138, 'Republik Rumania', 'republik_rumania', TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (139, 'Republik Serbia', 'republik_serbia', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (140, 'Rusia', 'rusia', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (141, 'San Marino', 'san_marino', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (142, 'Siprus', 'siprus', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (143, 'Slovenia', 'slovenia', TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (144, 'Slowakia', 'slowakia', TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (145, 'Spanyol', 'spanyol', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (146, 'Swedia', 'swedia', TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE),
    (147, 'Swiss', 'swiss', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE),
    (148, 'Turki', 'turki', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE),
    (149, 'Ukraina', 'ukraina', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (150, 'Vatikan', 'vatikan', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (151, 'Yunani', 'yunani', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE),
    (152, 'Amerika Serikat', 'amerika_serikat', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (153, 'Antigua Dan Barbuda', 'antigua_dan_barbuda', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (154, 'Bahama', 'bahama', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (155, 'Barbados', 'barbados', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (156, 'Belize', 'belize', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (157, 'Bermuda', 'bermuda', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (158, 'Costa Rica', 'costa_rica', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (159, 'Curacao', 'curacao', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (160, 'Dominika', 'dominika', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (161, 'El Salvador', 'el_salvador', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (162, 'Greenland', 'greenland', TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE),
    (163, 'Grenada', 'grenada', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (164, 'Guatemala', 'guatemala', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (165, 'Haiti', 'haiti', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (166, 'Honduras', 'honduras', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (167, 'Jamaika', 'jamaika', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (168, 'Kanada', 'kanada', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (169, 'Kuba', 'kuba', TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE),
    (170, 'Meksiko', 'meksiko', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (171, 'Nikaragua', 'nikaragua', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (172, 'Panama', 'panama', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (173, 'Puerto Rico', 'puerto_rico', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (174, 'Republik Dominika', 'republik_dominika', TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE),
    (175, 'Saint Kitts Dan Nevis', 'saint_kitts_dan_nevis', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (176, 'Saint Lucia', 'saint_lucia', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (177, 'Saint Vincent Dan Grenadine', 'saint_vincent_dan_grenadine', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (178, 'Trinidad Dan Tobago', 'trinidad_dan_tobago', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (179, 'Australia', 'australia', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (180, 'Fiji', 'fiji', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (181, 'Guam', 'guam', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (182, 'Kiribati', 'kiribati', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (183, 'Marshall', 'marshall', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (184, 'Mikronesia', 'mikronesia', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (185, 'Nauru', 'nauru', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (186, 'Palau', 'palau', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (187, 'Papua Nugini', 'papua_nugini', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (188, 'Samoa', 'samoa', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (189, 'Samoa Amerika', 'samoa_amerika', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (190, 'Selandia Baru', 'selandia_baru', TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (191, 'Tahiti', 'tahiti', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (192, 'Tonga', 'tonga', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (193, 'Tuvalu', 'tuvalu', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (194, 'Vanuatu', 'vanuatu', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    (195, 'Argentina', 'argentina', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE),
    (196, 'Bolivia', 'bolivia', TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE),
    (197, 'Brazil', 'brazil', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE),
    (198, 'Chile', 'chile', TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    (199, 'Ekuador', 'ekuador', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (200, 'Guiana Prancis', 'guiana_prancis', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (201, 'Guyana', 'guyana', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (202, 'Kolombia', 'kolombia', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE),
    (203, 'Paraguay', 'paraguay', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (204, 'Peru', 'peru', TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE),
    (205, 'Suriname', 'suriname', TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE),
    (206, 'Uruguay', 'uruguay', TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
    (207, 'Venezuela', 'venezuela', TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE);
