-- Database Mitra Perdagangan SQL Export
-- Total 1610 Records

DROP TABLE IF EXISTS database_mitra_perdagangan;
CREATE TABLE IF NOT EXISTS database_mitra_perdagangan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    country_id INT NOT NULL,
    country_slug VARCHAR(100) NOT NULL,
    mitra_no INT NOT NULL,
    mitra_country VARCHAR(100) NOT NULL,
    trade_type VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL
);


INSERT INTO database_mitra_perdagangan (
    country_id, country_slug, mitra_no, mitra_country, trade_type, status
) VALUES
(1, 'afrika_selatan', 1, 'Botswana', 'Perdagangan', 'Aktif'),
(2, 'afrika_selatan', 2, 'Bangladesh', 'Perdagangan', 'Aktif'),
(3, 'afrika_selatan', 3, 'Argentina', 'Perdagangan', 'Aktif'),
(4, 'afrika_selatan', 4, 'Bhutan', 'Perdagangan', 'Aktif'),
(5, 'afrika_selatan', 5, 'Albania', 'Perdagangan', 'Aktif'),
(6, 'afrika_selatan', 6, 'Benin', 'Perdagangan', 'Aktif'),
(7, 'afrika_selatan', 7, 'Barbados', 'Perdagangan', 'Aktif'),
(8, 'afrika_selatan', 8, 'Austria', 'Perdagangan', 'Aktif'),
(9, 'afrika_selatan', 9, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(10, 'afrika_selatan', 10, 'Brunei', 'Perdagangan', 'Aktif'),
(11, 'aljazair', 1, 'Brunei', 'Perdagangan', 'Aktif'),
(12, 'aljazair', 2, 'Benin', 'Perdagangan', 'Aktif'),
(13, 'aljazair', 3, 'Bahrain', 'Perdagangan', 'Aktif'),
(14, 'aljazair', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(15, 'aljazair', 5, 'Bolivia', 'Perdagangan', 'Aktif'),
(16, 'aljazair', 6, 'Bermuda', 'Perdagangan', 'Aktif'),
(17, 'aljazair', 7, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(18, 'aljazair', 8, 'Botswana', 'Perdagangan', 'Aktif'),
(19, 'angola', 1, 'Aljazair', 'Perdagangan', 'Aktif'),
(20, 'angola', 2, 'Bermuda', 'Perdagangan', 'Aktif'),
(21, 'angola', 3, 'Argentina', 'Perdagangan', 'Aktif'),
(22, 'angola', 4, 'Bolivia', 'Perdagangan', 'Aktif'),
(23, 'angola', 5, 'Barbados', 'Perdagangan', 'Aktif'),
(24, 'angola', 6, 'Belize', 'Perdagangan', 'Aktif'),
(25, 'angola', 7, 'Benin', 'Perdagangan', 'Aktif'),
(26, 'angola', 8, 'Albania', 'Perdagangan', 'Aktif'),
(27, 'benin', 1, 'Belize', 'Perdagangan', 'Aktif'),
(28, 'benin', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(29, 'benin', 3, 'Aljazair', 'Perdagangan', 'Aktif'),
(30, 'benin', 4, 'Botswana', 'Perdagangan', 'Aktif'),
(31, 'benin', 5, 'Belgia', 'Perdagangan', 'Aktif'),
(32, 'benin', 6, 'Barbados', 'Perdagangan', 'Aktif'),
(33, 'benin', 7, 'Bahrain', 'Perdagangan', 'Aktif'),
(34, 'botswana', 1, 'Bahama', 'Perdagangan', 'Aktif'),
(35, 'botswana', 2, 'Afganistan', 'Perdagangan', 'Aktif'),
(36, 'botswana', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(37, 'botswana', 4, 'Belgia', 'Perdagangan', 'Aktif'),
(38, 'botswana', 5, 'Belanda', 'Perdagangan', 'Aktif'),
(39, 'botswana', 6, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(40, 'botswana', 7, 'Benin', 'Perdagangan', 'Aktif'),
(41, 'botswana', 8, 'Brunei', 'Perdagangan', 'Aktif'),
(42, 'burkina_faso', 1, 'Belize', 'Perdagangan', 'Aktif'),
(43, 'burkina_faso', 2, 'Bangladesh', 'Perdagangan', 'Aktif'),
(44, 'burkina_faso', 3, 'Aljazair', 'Perdagangan', 'Aktif'),
(45, 'burkina_faso', 4, 'Afganistan', 'Perdagangan', 'Aktif'),
(46, 'burkina_faso', 5, 'Bolivia', 'Perdagangan', 'Aktif'),
(47, 'burkina_faso', 6, 'Benin', 'Perdagangan', 'Aktif'),
(48, 'burundi', 1, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(49, 'burundi', 2, 'Albania', 'Perdagangan', 'Aktif'),
(50, 'burundi', 3, 'Angola', 'Perdagangan', 'Aktif'),
(51, 'burundi', 4, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(52, 'burundi', 5, 'Afganistan', 'Perdagangan', 'Aktif'),
(53, 'burundi', 6, 'Australia', 'Perdagangan', 'Aktif'),
(54, 'burundi', 7, 'Andorra', 'Perdagangan', 'Aktif'),
(55, 'burundi', 8, 'Argentina', 'Perdagangan', 'Aktif'),
(56, 'chad', 1, 'Belanda', 'Perdagangan', 'Aktif'),
(57, 'chad', 2, 'Belarus', 'Perdagangan', 'Aktif'),
(58, 'chad', 3, 'Bhutan', 'Perdagangan', 'Aktif'),
(59, 'chad', 4, 'Argentina', 'Perdagangan', 'Aktif'),
(60, 'chad', 5, 'Bahama', 'Perdagangan', 'Aktif'),
(61, 'chad', 6, 'Albania', 'Perdagangan', 'Aktif'),
(62, 'chad', 7, 'Bahrain', 'Perdagangan', 'Aktif'),
(63, 'djibouti', 1, 'Belgia', 'Perdagangan', 'Aktif'),
(64, 'djibouti', 2, 'Belanda', 'Perdagangan', 'Aktif'),
(65, 'djibouti', 3, 'Australia', 'Perdagangan', 'Aktif'),
(66, 'djibouti', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(67, 'djibouti', 5, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(68, 'djibouti', 6, 'Austria', 'Perdagangan', 'Aktif'),
(69, 'djibouti', 7, 'Benin', 'Perdagangan', 'Aktif'),
(70, 'djibouti', 8, 'Bhutan', 'Perdagangan', 'Aktif'),
(71, 'eritrea', 1, 'Aljazair', 'Perdagangan', 'Aktif'),
(72, 'eritrea', 2, 'Bahrain', 'Perdagangan', 'Aktif'),
(73, 'eritrea', 3, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(74, 'eritrea', 4, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(75, 'eritrea', 5, 'Brunei', 'Perdagangan', 'Aktif'),
(76, 'eritrea', 6, 'Belize', 'Perdagangan', 'Aktif'),
(77, 'eritrea', 7, 'Botswana', 'Perdagangan', 'Aktif'),
(78, 'eritrea', 8, 'Belanda', 'Perdagangan', 'Aktif'),
(79, 'eswatini', 1, 'Aljazair', 'Perdagangan', 'Aktif'),
(80, 'eswatini', 2, 'Bolivia', 'Perdagangan', 'Aktif'),
(81, 'eswatini', 3, 'Armenia', 'Perdagangan', 'Aktif'),
(82, 'eswatini', 4, 'Australia', 'Perdagangan', 'Aktif'),
(83, 'eswatini', 5, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(84, 'eswatini', 6, 'Barbados', 'Perdagangan', 'Aktif'),
(85, 'eswatini', 7, 'Belize', 'Perdagangan', 'Aktif'),
(86, 'eswatini', 8, 'Afganistan', 'Perdagangan', 'Aktif'),
(87, 'eswatini', 9, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(88, 'eswatini', 10, 'Bahrain', 'Perdagangan', 'Aktif'),
(89, 'ethiopia', 1, 'Bahrain', 'Perdagangan', 'Aktif'),
(90, 'ethiopia', 2, 'Belgia', 'Perdagangan', 'Aktif'),
(91, 'ethiopia', 3, 'Argentina', 'Perdagangan', 'Aktif'),
(92, 'ethiopia', 4, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(93, 'ethiopia', 5, 'Brunei', 'Perdagangan', 'Aktif'),
(94, 'ethiopia', 6, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(95, 'ethiopia', 7, 'Afganistan', 'Perdagangan', 'Aktif'),
(96, 'ethiopia', 8, 'Benin', 'Perdagangan', 'Aktif'),
(97, 'ethiopia', 9, 'Australia', 'Perdagangan', 'Aktif'),
(98, 'ethiopia', 10, 'Austria', 'Perdagangan', 'Aktif'),
(99, 'gabon', 1, 'Andorra', 'Perdagangan', 'Aktif'),
(100, 'gabon', 2, 'Barbados', 'Perdagangan', 'Aktif'),
(101, 'gabon', 3, 'Austria', 'Perdagangan', 'Aktif'),
(102, 'gabon', 4, 'Brunei', 'Perdagangan', 'Aktif'),
(103, 'gabon', 5, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(104, 'gabon', 6, 'Armenia', 'Perdagangan', 'Aktif'),
(105, 'gabon', 7, 'Bangladesh', 'Perdagangan', 'Aktif'),
(106, 'gabon', 8, 'Bahrain', 'Perdagangan', 'Aktif'),
(107, 'gabon', 9, 'Albania', 'Perdagangan', 'Aktif'),
(108, 'gambia', 1, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(109, 'gambia', 2, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(110, 'gambia', 3, 'Bahama', 'Perdagangan', 'Aktif'),
(111, 'gambia', 4, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(112, 'gambia', 5, 'Bangladesh', 'Perdagangan', 'Aktif'),
(113, 'gambia', 6, 'Belize', 'Perdagangan', 'Aktif'),
(114, 'gambia', 7, 'Andorra', 'Perdagangan', 'Aktif'),
(115, 'gambia', 8, 'Albania', 'Perdagangan', 'Aktif'),
(116, 'ghana', 1, 'Bhutan', 'Perdagangan', 'Aktif'),
(117, 'ghana', 2, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(118, 'ghana', 3, 'Bolivia', 'Perdagangan', 'Aktif'),
(119, 'ghana', 4, 'Afganistan', 'Perdagangan', 'Aktif'),
(120, 'ghana', 5, 'Argentina', 'Perdagangan', 'Aktif'),
(121, 'ghana', 6, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(122, 'ghana', 7, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(123, 'ghana', 8, 'Austria', 'Perdagangan', 'Aktif'),
(124, 'ghana', 9, 'Brunei', 'Perdagangan', 'Aktif'),
(125, 'ghana', 10, 'Andorra', 'Perdagangan', 'Aktif'),
(126, 'guinea', 1, 'Belanda', 'Perdagangan', 'Aktif'),
(127, 'guinea', 2, 'Brunei', 'Perdagangan', 'Aktif'),
(128, 'guinea', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(129, 'guinea', 4, 'Bahrain', 'Perdagangan', 'Aktif'),
(130, 'guinea', 5, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(131, 'guinea', 6, 'Australia', 'Perdagangan', 'Aktif'),
(132, 'guinea', 7, 'Bahama', 'Perdagangan', 'Aktif'),
(133, 'guinea_bissau', 1, 'Belanda', 'Perdagangan', 'Aktif'),
(134, 'guinea_bissau', 2, 'Angola', 'Perdagangan', 'Aktif'),
(135, 'guinea_bissau', 3, 'Bahrain', 'Perdagangan', 'Aktif'),
(136, 'guinea_bissau', 4, 'Bahama', 'Perdagangan', 'Aktif'),
(137, 'guinea_bissau', 5, 'Austria', 'Perdagangan', 'Aktif'),
(138, 'guinea_bissau', 6, 'Brunei', 'Perdagangan', 'Aktif'),
(139, 'kamerun', 1, 'Austria', 'Perdagangan', 'Aktif'),
(140, 'kamerun', 2, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(141, 'kamerun', 3, 'Bahama', 'Perdagangan', 'Aktif'),
(142, 'kamerun', 4, 'Argentina', 'Perdagangan', 'Aktif'),
(143, 'kamerun', 5, 'Belarus', 'Perdagangan', 'Aktif'),
(144, 'kamerun', 6, 'Bahrain', 'Perdagangan', 'Aktif'),
(145, 'kenya', 1, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(146, 'kenya', 2, 'Brazil', 'Perdagangan', 'Aktif'),
(147, 'kenya', 3, 'Bahama', 'Perdagangan', 'Aktif'),
(148, 'kenya', 4, 'Bhutan', 'Perdagangan', 'Aktif'),
(149, 'kenya', 5, 'Argentina', 'Perdagangan', 'Aktif'),
(150, 'kenya', 6, 'Bahrain', 'Perdagangan', 'Aktif'),
(151, 'kenya', 7, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(152, 'komoro', 1, 'Barbados', 'Perdagangan', 'Aktif'),
(153, 'komoro', 2, 'Benin', 'Perdagangan', 'Aktif'),
(154, 'komoro', 3, 'Belgia', 'Perdagangan', 'Aktif'),
(155, 'komoro', 4, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(156, 'komoro', 5, 'Botswana', 'Perdagangan', 'Aktif'),
(157, 'komoro', 6, 'Belanda', 'Perdagangan', 'Aktif'),
(158, 'kongo', 1, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(159, 'kongo', 2, 'Australia', 'Perdagangan', 'Aktif'),
(160, 'kongo', 3, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(161, 'kongo', 4, 'Armenia', 'Perdagangan', 'Aktif'),
(162, 'kongo', 5, 'Belarus', 'Perdagangan', 'Aktif'),
(163, 'kongo', 6, 'Bhutan', 'Perdagangan', 'Aktif'),
(164, 'kongo', 7, 'Bahama', 'Perdagangan', 'Aktif'),
(165, 'kongo', 8, 'Angola', 'Perdagangan', 'Aktif'),
(166, 'kongo', 9, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(167, 'kongo', 10, 'Belanda', 'Perdagangan', 'Aktif'),
(168, 'lesotho', 1, 'Andorra', 'Perdagangan', 'Aktif'),
(169, 'lesotho', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(170, 'lesotho', 3, 'Barbados', 'Perdagangan', 'Aktif'),
(171, 'lesotho', 4, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(172, 'lesotho', 5, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(173, 'lesotho', 6, 'Brunei', 'Perdagangan', 'Aktif'),
(174, 'lesotho', 7, 'Bolivia', 'Perdagangan', 'Aktif'),
(175, 'lesotho', 8, 'Armenia', 'Perdagangan', 'Aktif'),
(176, 'liberia', 1, 'Brazil', 'Perdagangan', 'Aktif'),
(177, 'liberia', 2, 'Argentina', 'Perdagangan', 'Aktif'),
(178, 'liberia', 3, 'Bahrain', 'Perdagangan', 'Aktif'),
(179, 'liberia', 4, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(180, 'liberia', 5, 'Aljazair', 'Perdagangan', 'Aktif'),
(181, 'liberia', 6, 'Bangladesh', 'Perdagangan', 'Aktif'),
(182, 'liberia', 7, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(183, 'liberia', 8, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(184, 'liberia', 9, 'Afganistan', 'Perdagangan', 'Aktif'),
(185, 'liberia', 10, 'Andorra', 'Perdagangan', 'Aktif'),
(186, 'libya', 1, 'Angola', 'Perdagangan', 'Aktif'),
(187, 'libya', 2, 'Belize', 'Perdagangan', 'Aktif'),
(188, 'libya', 3, 'Bangladesh', 'Perdagangan', 'Aktif'),
(189, 'libya', 4, 'Bermuda', 'Perdagangan', 'Aktif'),
(190, 'libya', 5, 'Armenia', 'Perdagangan', 'Aktif'),
(191, 'libya', 6, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(192, 'libya', 7, 'Bolivia', 'Perdagangan', 'Aktif'),
(193, 'libya', 8, 'Belarus', 'Perdagangan', 'Aktif'),
(194, 'libya', 9, 'Austria', 'Perdagangan', 'Aktif'),
(195, 'libya', 10, 'Bahama', 'Perdagangan', 'Aktif'),
(196, 'madagaskar', 1, 'Afganistan', 'Perdagangan', 'Aktif'),
(197, 'madagaskar', 2, 'Austria', 'Perdagangan', 'Aktif'),
(198, 'madagaskar', 3, 'Belgia', 'Perdagangan', 'Aktif'),
(199, 'madagaskar', 4, 'Belanda', 'Perdagangan', 'Aktif'),
(200, 'madagaskar', 5, 'Belarus', 'Perdagangan', 'Aktif'),
(201, 'madagaskar', 6, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(202, 'madagaskar', 7, 'Bahrain', 'Perdagangan', 'Aktif'),
(203, 'malawi', 1, 'Barbados', 'Perdagangan', 'Aktif'),
(204, 'malawi', 2, 'Benin', 'Perdagangan', 'Aktif'),
(205, 'malawi', 3, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(206, 'malawi', 4, 'Armenia', 'Perdagangan', 'Aktif'),
(207, 'malawi', 5, 'Aljazair', 'Perdagangan', 'Aktif'),
(208, 'malawi', 6, 'Botswana', 'Perdagangan', 'Aktif'),
(209, 'malawi', 7, 'Belgia', 'Perdagangan', 'Aktif'),
(210, 'malawi', 8, 'Bermuda', 'Perdagangan', 'Aktif'),
(211, 'malawi', 9, 'Bahama', 'Perdagangan', 'Aktif'),
(212, 'mali', 1, 'Bangladesh', 'Perdagangan', 'Aktif'),
(213, 'mali', 2, 'Bahrain', 'Perdagangan', 'Aktif'),
(214, 'mali', 3, 'Belanda', 'Perdagangan', 'Aktif'),
(215, 'mali', 4, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(216, 'mali', 5, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(217, 'mali', 6, 'Bahama', 'Perdagangan', 'Aktif'),
(218, 'mali', 7, 'Brunei', 'Perdagangan', 'Aktif'),
(219, 'maroko', 1, 'Argentina', 'Perdagangan', 'Aktif'),
(220, 'maroko', 2, 'Belgia', 'Perdagangan', 'Aktif'),
(221, 'maroko', 3, 'Benin', 'Perdagangan', 'Aktif'),
(222, 'maroko', 4, 'Angola', 'Perdagangan', 'Aktif'),
(223, 'maroko', 5, 'Austria', 'Perdagangan', 'Aktif'),
(224, 'maroko', 6, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(225, 'maroko', 7, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(226, 'maroko', 8, 'Bahrain', 'Perdagangan', 'Aktif'),
(227, 'maroko', 9, 'Barbados', 'Perdagangan', 'Aktif'),
(228, 'mauritania', 1, 'Brazil', 'Perdagangan', 'Aktif'),
(229, 'mauritania', 2, 'Belanda', 'Perdagangan', 'Aktif'),
(230, 'mauritania', 3, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(231, 'mauritania', 4, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(232, 'mauritania', 5, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(233, 'mauritania', 6, 'Belgia', 'Perdagangan', 'Aktif'),
(234, 'mauritania', 7, 'Benin', 'Perdagangan', 'Aktif'),
(235, 'mauritania', 8, 'Afganistan', 'Perdagangan', 'Aktif'),
(236, 'mauritania', 9, 'Aljazair', 'Perdagangan', 'Aktif'),
(237, 'mauritania', 10, 'Belarus', 'Perdagangan', 'Aktif'),
(238, 'mauritius', 1, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(239, 'mauritius', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(240, 'mauritius', 3, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(241, 'mauritius', 4, 'Bhutan', 'Perdagangan', 'Aktif'),
(242, 'mauritius', 5, 'Armenia', 'Perdagangan', 'Aktif'),
(243, 'mauritius', 6, 'Austria', 'Perdagangan', 'Aktif'),
(244, 'mauritius', 7, 'Belize', 'Perdagangan', 'Aktif'),
(245, 'mesir', 1, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(246, 'mesir', 2, 'Bhutan', 'Perdagangan', 'Aktif'),
(247, 'mesir', 3, 'Afganistan', 'Perdagangan', 'Aktif'),
(248, 'mesir', 4, 'Austria', 'Perdagangan', 'Aktif'),
(249, 'mesir', 5, 'Belgia', 'Perdagangan', 'Aktif'),
(250, 'mesir', 6, 'Argentina', 'Perdagangan', 'Aktif'),
(251, 'mesir', 7, 'Barbados', 'Perdagangan', 'Aktif'),
(252, 'mesir', 8, 'Belarus', 'Perdagangan', 'Aktif'),
(253, 'mesir', 9, 'Australia', 'Perdagangan', 'Aktif'),
(254, 'mesir', 10, 'Bermuda', 'Perdagangan', 'Aktif'),
(255, 'mozambik', 1, 'Angola', 'Perdagangan', 'Aktif'),
(256, 'mozambik', 2, 'Barbados', 'Perdagangan', 'Aktif'),
(257, 'mozambik', 3, 'Belanda', 'Perdagangan', 'Aktif'),
(258, 'mozambik', 4, 'Bahrain', 'Perdagangan', 'Aktif'),
(259, 'mozambik', 5, 'Afganistan', 'Perdagangan', 'Aktif'),
(260, 'mozambik', 6, 'Belarus', 'Perdagangan', 'Aktif'),
(261, 'mozambik', 7, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(262, 'mozambik', 8, 'Austria', 'Perdagangan', 'Aktif'),
(263, 'mozambik', 9, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(264, 'namibia', 1, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(265, 'namibia', 2, 'Argentina', 'Perdagangan', 'Aktif'),
(266, 'namibia', 3, 'Brunei', 'Perdagangan', 'Aktif'),
(267, 'namibia', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(268, 'namibia', 5, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(269, 'namibia', 6, 'Bahrain', 'Perdagangan', 'Aktif'),
(270, 'namibia', 7, 'Benin', 'Perdagangan', 'Aktif'),
(271, 'namibia', 8, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(272, 'niger', 1, 'Bhutan', 'Perdagangan', 'Aktif'),
(273, 'niger', 2, 'Belanda', 'Perdagangan', 'Aktif'),
(274, 'niger', 3, 'Belarus', 'Perdagangan', 'Aktif'),
(275, 'niger', 4, 'Austria', 'Perdagangan', 'Aktif'),
(276, 'niger', 5, 'Angola', 'Perdagangan', 'Aktif'),
(277, 'niger', 6, 'Australia', 'Perdagangan', 'Aktif'),
(278, 'nigeria', 1, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(279, 'nigeria', 2, 'Australia', 'Perdagangan', 'Aktif'),
(280, 'nigeria', 3, 'Bangladesh', 'Perdagangan', 'Aktif'),
(281, 'nigeria', 4, 'Belanda', 'Perdagangan', 'Aktif'),
(282, 'nigeria', 5, 'Austria', 'Perdagangan', 'Aktif'),
(283, 'nigeria', 6, 'Bahama', 'Perdagangan', 'Aktif'),
(284, 'nigeria', 7, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(285, 'nigeria', 8, 'Belarus', 'Perdagangan', 'Aktif'),
(286, 'pantai_gading', 1, 'Belgia', 'Perdagangan', 'Aktif'),
(287, 'pantai_gading', 2, 'Bolivia', 'Perdagangan', 'Aktif'),
(288, 'pantai_gading', 3, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(289, 'pantai_gading', 4, 'Argentina', 'Perdagangan', 'Aktif'),
(290, 'pantai_gading', 5, 'Angola', 'Perdagangan', 'Aktif'),
(291, 'pantai_gading', 6, 'Brunei', 'Perdagangan', 'Aktif'),
(292, 'pantai_gading', 7, 'Bhutan', 'Perdagangan', 'Aktif'),
(293, 'pantai_gading', 8, 'Andorra', 'Perdagangan', 'Aktif'),
(294, 'pantai_gading', 9, 'Benin', 'Perdagangan', 'Aktif'),
(295, 'pantai_gading', 10, 'Bahrain', 'Perdagangan', 'Aktif'),
(296, 'republik_afrika_tengah', 1, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(297, 'republik_afrika_tengah', 2, 'Angola', 'Perdagangan', 'Aktif'),
(298, 'republik_afrika_tengah', 3, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(299, 'republik_afrika_tengah', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(300, 'republik_afrika_tengah', 5, 'Botswana', 'Perdagangan', 'Aktif'),
(301, 'republik_afrika_tengah', 6, 'Albania', 'Perdagangan', 'Aktif'),
(302, 'republik_afrika_tengah', 7, 'Bermuda', 'Perdagangan', 'Aktif'),
(303, 'republik_afrika_tengah', 8, 'Austria', 'Perdagangan', 'Aktif'),
(304, 'republik_demokratik_kongo', 1, 'Bahama', 'Perdagangan', 'Aktif'),
(305, 'republik_demokratik_kongo', 2, 'Bolivia', 'Perdagangan', 'Aktif'),
(306, 'republik_demokratik_kongo', 3, 'Belanda', 'Perdagangan', 'Aktif'),
(307, 'republik_demokratik_kongo', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(308, 'republik_demokratik_kongo', 5, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(309, 'republik_demokratik_kongo', 6, 'Benin', 'Perdagangan', 'Aktif'),
(310, 'republik_demokratik_kongo', 7, 'Brunei', 'Perdagangan', 'Aktif'),
(311, 'republik_demokratik_kongo', 8, 'Armenia', 'Perdagangan', 'Aktif'),
(312, 'republik_demokratik_kongo', 9, 'Afganistan', 'Perdagangan', 'Aktif'),
(313, 'republik_demokratik_kongo', 10, 'Austria', 'Perdagangan', 'Aktif'),
(314, 'republik_sudan', 1, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(315, 'republik_sudan', 2, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(316, 'republik_sudan', 3, 'Belanda', 'Perdagangan', 'Aktif'),
(317, 'republik_sudan', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(318, 'republik_sudan', 5, 'Argentina', 'Perdagangan', 'Aktif'),
(319, 'republik_sudan', 6, 'Bahrain', 'Perdagangan', 'Aktif'),
(320, 'republik_sudan', 7, 'Bolivia', 'Perdagangan', 'Aktif'),
(321, 'republik_sudan', 8, 'Austria', 'Perdagangan', 'Aktif'),
(322, 'republik_sudan', 9, 'Aljazair', 'Perdagangan', 'Aktif'),
(323, 'republik_tanzania', 1, 'Australia', 'Perdagangan', 'Aktif'),
(324, 'republik_tanzania', 2, 'Bangladesh', 'Perdagangan', 'Aktif'),
(325, 'republik_tanzania', 3, 'Benin', 'Perdagangan', 'Aktif'),
(326, 'republik_tanzania', 4, 'Austria', 'Perdagangan', 'Aktif'),
(327, 'republik_tanzania', 5, 'Albania', 'Perdagangan', 'Aktif'),
(328, 'republik_tanzania', 6, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(329, 'republik_tanzania', 7, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(330, 'republik_uganda', 1, 'Bahrain', 'Perdagangan', 'Aktif'),
(331, 'republik_uganda', 2, 'Belarus', 'Perdagangan', 'Aktif'),
(332, 'republik_uganda', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(333, 'republik_uganda', 4, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(334, 'republik_uganda', 5, 'Barbados', 'Perdagangan', 'Aktif'),
(335, 'republik_uganda', 6, 'Australia', 'Perdagangan', 'Aktif'),
(336, 'republik_uganda', 7, 'Brunei', 'Perdagangan', 'Aktif'),
(337, 'republik_zambia', 1, 'Armenia', 'Perdagangan', 'Aktif'),
(338, 'republik_zambia', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(339, 'republik_zambia', 3, 'Andorra', 'Perdagangan', 'Aktif'),
(340, 'republik_zambia', 4, 'Belanda', 'Perdagangan', 'Aktif'),
(341, 'republik_zambia', 5, 'Belgia', 'Perdagangan', 'Aktif'),
(342, 'republik_zambia', 6, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(343, 'republik_zambia', 7, 'Bahama', 'Perdagangan', 'Aktif'),
(344, 'republik_zambia', 8, 'Australia', 'Perdagangan', 'Aktif'),
(345, 'republik_zambia', 9, 'Belarus', 'Perdagangan', 'Aktif'),
(346, 'republik_zimbabwe', 1, 'Bermuda', 'Perdagangan', 'Aktif'),
(347, 'republik_zimbabwe', 2, 'Albania', 'Perdagangan', 'Aktif'),
(348, 'republik_zimbabwe', 3, 'Belarus', 'Perdagangan', 'Aktif'),
(349, 'republik_zimbabwe', 4, 'Benin', 'Perdagangan', 'Aktif'),
(350, 'republik_zimbabwe', 5, 'Belanda', 'Perdagangan', 'Aktif'),
(351, 'republik_zimbabwe', 6, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(352, 'republik_zimbabwe', 7, 'Australia', 'Perdagangan', 'Aktif'),
(353, 'republik_zimbabwe', 8, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(354, 'republik_zimbabwe', 9, 'Belize', 'Perdagangan', 'Aktif'),
(355, 'republik_zimbabwe', 10, 'Bahrain', 'Perdagangan', 'Aktif'),
(356, 'rwanda', 1, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(357, 'rwanda', 2, 'Benin', 'Perdagangan', 'Aktif'),
(358, 'rwanda', 3, 'Bangladesh', 'Perdagangan', 'Aktif'),
(359, 'rwanda', 4, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(360, 'rwanda', 5, 'Australia', 'Perdagangan', 'Aktif'),
(361, 'rwanda', 6, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(362, 'rwanda', 7, 'Afganistan', 'Perdagangan', 'Aktif'),
(363, 'rwanda', 8, 'Albania', 'Perdagangan', 'Aktif'),
(364, 'sao_tome_dan_principe', 1, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(365, 'sao_tome_dan_principe', 2, 'Barbados', 'Perdagangan', 'Aktif'),
(366, 'sao_tome_dan_principe', 3, 'Australia', 'Perdagangan', 'Aktif'),
(367, 'sao_tome_dan_principe', 4, 'Bhutan', 'Perdagangan', 'Aktif'),
(368, 'sao_tome_dan_principe', 5, 'Argentina', 'Perdagangan', 'Aktif'),
(369, 'sao_tome_dan_principe', 6, 'Albania', 'Perdagangan', 'Aktif'),
(370, 'sao_tome_dan_principe', 7, 'Afganistan', 'Perdagangan', 'Aktif'),
(371, 'senegal', 1, 'Belanda', 'Perdagangan', 'Aktif'),
(372, 'senegal', 2, 'Bermuda', 'Perdagangan', 'Aktif'),
(373, 'senegal', 3, 'Bahrain', 'Perdagangan', 'Aktif'),
(374, 'senegal', 4, 'Afganistan', 'Perdagangan', 'Aktif'),
(375, 'senegal', 5, 'Belize', 'Perdagangan', 'Aktif'),
(376, 'senegal', 6, 'Barbados', 'Perdagangan', 'Aktif'),
(377, 'senegal', 7, 'Brunei', 'Perdagangan', 'Aktif'),
(378, 'senegal', 8, 'Brazil', 'Perdagangan', 'Aktif'),
(379, 'senegal', 9, 'Andorra', 'Perdagangan', 'Aktif'),
(380, 'seychelles', 1, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(381, 'seychelles', 2, 'Argentina', 'Perdagangan', 'Aktif'),
(382, 'seychelles', 3, 'Benin', 'Perdagangan', 'Aktif'),
(383, 'seychelles', 4, 'Bhutan', 'Perdagangan', 'Aktif'),
(384, 'seychelles', 5, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(385, 'seychelles', 6, 'Bahrain', 'Perdagangan', 'Aktif'),
(386, 'seychelles', 7, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(387, 'sierra_leone', 1, 'Belgia', 'Perdagangan', 'Aktif'),
(388, 'sierra_leone', 2, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(389, 'sierra_leone', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(390, 'sierra_leone', 4, 'Brunei', 'Perdagangan', 'Aktif'),
(391, 'sierra_leone', 5, 'Andorra', 'Perdagangan', 'Aktif'),
(392, 'sierra_leone', 6, 'Benin', 'Perdagangan', 'Aktif'),
(393, 'somalia', 1, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(394, 'somalia', 2, 'Bermuda', 'Perdagangan', 'Aktif'),
(395, 'somalia', 3, 'Bahrain', 'Perdagangan', 'Aktif'),
(396, 'somalia', 4, 'Belize', 'Perdagangan', 'Aktif'),
(397, 'somalia', 5, 'Benin', 'Perdagangan', 'Aktif'),
(398, 'somalia', 6, 'Barbados', 'Perdagangan', 'Aktif'),
(399, 'somalia', 7, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(400, 'somalia', 8, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(401, 'somalia', 9, 'Botswana', 'Perdagangan', 'Aktif'),
(402, 'sudan_selatan', 1, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(403, 'sudan_selatan', 2, 'Argentina', 'Perdagangan', 'Aktif'),
(404, 'sudan_selatan', 3, 'Benin', 'Perdagangan', 'Aktif'),
(405, 'sudan_selatan', 4, 'Bolivia', 'Perdagangan', 'Aktif'),
(406, 'sudan_selatan', 5, 'Bermuda', 'Perdagangan', 'Aktif'),
(407, 'sudan_selatan', 6, 'Andorra', 'Perdagangan', 'Aktif'),
(408, 'tanjung_verde', 1, 'Bolivia', 'Perdagangan', 'Aktif'),
(409, 'tanjung_verde', 2, 'Aljazair', 'Perdagangan', 'Aktif'),
(410, 'tanjung_verde', 3, 'Albania', 'Perdagangan', 'Aktif'),
(411, 'tanjung_verde', 4, 'Brunei', 'Perdagangan', 'Aktif'),
(412, 'tanjung_verde', 5, 'Australia', 'Perdagangan', 'Aktif'),
(413, 'tanjung_verde', 6, 'Armenia', 'Perdagangan', 'Aktif'),
(414, 'togo', 1, 'Botswana', 'Perdagangan', 'Aktif'),
(415, 'togo', 2, 'Bahama', 'Perdagangan', 'Aktif'),
(416, 'togo', 3, 'Australia', 'Perdagangan', 'Aktif'),
(417, 'togo', 4, 'Armenia', 'Perdagangan', 'Aktif'),
(418, 'togo', 5, 'Bolivia', 'Perdagangan', 'Aktif'),
(419, 'togo', 6, 'Bermuda', 'Perdagangan', 'Aktif'),
(420, 'togo', 7, 'Angola', 'Perdagangan', 'Aktif'),
(421, 'togo', 8, 'Brazil', 'Perdagangan', 'Aktif'),
(422, 'togo', 9, 'Bangladesh', 'Perdagangan', 'Aktif'),
(423, 'togo', 10, 'Bhutan', 'Perdagangan', 'Aktif'),
(424, 'tunisia', 1, 'Afganistan', 'Perdagangan', 'Aktif'),
(425, 'tunisia', 2, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(426, 'tunisia', 3, 'Argentina', 'Perdagangan', 'Aktif'),
(427, 'tunisia', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(428, 'tunisia', 5, 'Benin', 'Perdagangan', 'Aktif'),
(429, 'tunisia', 6, 'Bolivia', 'Perdagangan', 'Aktif'),
(430, 'tunisia', 7, 'Angola', 'Perdagangan', 'Aktif'),
(431, 'tunisia', 8, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(432, 'tunisia', 9, 'Albania', 'Perdagangan', 'Aktif'),
(433, 'afganistan', 1, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(434, 'afganistan', 2, 'Argentina', 'Perdagangan', 'Aktif'),
(435, 'afganistan', 3, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(436, 'afganistan', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(437, 'afganistan', 5, 'Aljazair', 'Perdagangan', 'Aktif'),
(438, 'afganistan', 6, 'Austria', 'Perdagangan', 'Aktif'),
(439, 'afganistan', 7, 'Albania', 'Perdagangan', 'Aktif'),
(440, 'afganistan', 8, 'Bolivia', 'Perdagangan', 'Aktif'),
(441, 'afganistan', 9, 'Armenia', 'Perdagangan', 'Aktif'),
(442, 'arab_saudi', 1, 'Albania', 'Perdagangan', 'Aktif'),
(443, 'arab_saudi', 2, 'Belgia', 'Perdagangan', 'Aktif'),
(444, 'arab_saudi', 3, 'Afganistan', 'Perdagangan', 'Aktif'),
(445, 'arab_saudi', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(446, 'arab_saudi', 5, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(447, 'arab_saudi', 6, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(448, 'arab_saudi', 7, 'Bhutan', 'Perdagangan', 'Aktif'),
(449, 'arab_saudi', 8, 'Benin', 'Perdagangan', 'Aktif'),
(450, 'arab_saudi', 9, 'Belize', 'Perdagangan', 'Aktif'),
(451, 'arab_saudi', 10, 'Botswana', 'Perdagangan', 'Aktif'),
(452, 'armenia', 1, 'Andorra', 'Perdagangan', 'Aktif'),
(453, 'armenia', 2, 'Bahrain', 'Perdagangan', 'Aktif'),
(454, 'armenia', 3, 'Albania', 'Perdagangan', 'Aktif'),
(455, 'armenia', 4, 'Bahama', 'Perdagangan', 'Aktif'),
(456, 'armenia', 5, 'Botswana', 'Perdagangan', 'Aktif'),
(457, 'armenia', 6, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(458, 'armenia', 7, 'Belize', 'Perdagangan', 'Aktif'),
(459, 'armenia', 8, 'Aljazair', 'Perdagangan', 'Aktif'),
(460, 'armenia', 9, 'Belgia', 'Perdagangan', 'Aktif'),
(461, 'azerbaijan', 1, 'Benin', 'Perdagangan', 'Aktif'),
(462, 'azerbaijan', 2, 'Bangladesh', 'Perdagangan', 'Aktif'),
(463, 'azerbaijan', 3, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(464, 'azerbaijan', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(465, 'azerbaijan', 5, 'Bahama', 'Perdagangan', 'Aktif'),
(466, 'azerbaijan', 6, 'Afganistan', 'Perdagangan', 'Aktif'),
(467, 'azerbaijan', 7, 'Andorra', 'Perdagangan', 'Aktif'),
(468, 'azerbaijan', 8, 'Bhutan', 'Perdagangan', 'Aktif'),
(469, 'bahrain', 1, 'Bermuda', 'Perdagangan', 'Aktif'),
(470, 'bahrain', 2, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(471, 'bahrain', 3, 'Benin', 'Perdagangan', 'Aktif'),
(472, 'bahrain', 4, 'Bahama', 'Perdagangan', 'Aktif'),
(473, 'bahrain', 5, 'Belanda', 'Perdagangan', 'Aktif'),
(474, 'bahrain', 6, 'Botswana', 'Perdagangan', 'Aktif'),
(475, 'bangladesh', 1, 'Angola', 'Perdagangan', 'Aktif'),
(476, 'bangladesh', 2, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(477, 'bangladesh', 3, 'Belanda', 'Perdagangan', 'Aktif'),
(478, 'bangladesh', 4, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(479, 'bangladesh', 5, 'Andorra', 'Perdagangan', 'Aktif'),
(480, 'bangladesh', 6, 'Austria', 'Perdagangan', 'Aktif'),
(481, 'bhutan', 1, 'Bulgaria', 'Perdagangan', 'Aktif'),
(482, 'bhutan', 2, 'Australia', 'Perdagangan', 'Aktif'),
(483, 'bhutan', 3, 'Belanda', 'Perdagangan', 'Aktif'),
(484, 'bhutan', 4, 'Botswana', 'Perdagangan', 'Aktif'),
(485, 'bhutan', 5, 'Brazil', 'Perdagangan', 'Aktif'),
(486, 'bhutan', 6, 'Argentina', 'Perdagangan', 'Aktif'),
(487, 'bhutan', 7, 'Bangladesh', 'Perdagangan', 'Aktif'),
(488, 'brunei', 1, 'Botswana', 'Perdagangan', 'Aktif'),
(489, 'brunei', 2, 'Aljazair', 'Perdagangan', 'Aktif'),
(490, 'brunei', 3, 'Belize', 'Perdagangan', 'Aktif'),
(491, 'brunei', 4, 'Angola', 'Perdagangan', 'Aktif'),
(492, 'brunei', 5, 'Belarus', 'Perdagangan', 'Aktif'),
(493, 'brunei', 6, 'Benin', 'Perdagangan', 'Aktif'),
(494, 'brunei', 7, 'Albania', 'Perdagangan', 'Aktif'),
(495, 'china', 1, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(496, 'china', 2, 'Angola', 'Perdagangan', 'Aktif'),
(497, 'china', 3, 'Aljazair', 'Perdagangan', 'Aktif'),
(498, 'china', 4, 'Austria', 'Perdagangan', 'Aktif'),
(499, 'china', 5, 'Andorra', 'Perdagangan', 'Aktif'),
(500, 'china', 6, 'Belgia', 'Perdagangan', 'Aktif');

INSERT INTO database_mitra_perdagangan (
    country_id, country_slug, mitra_no, mitra_country, trade_type, status
) VALUES
(501, 'china', 7, 'Armenia', 'Perdagangan', 'Aktif'),
(502, 'china', 8, 'Australia', 'Perdagangan', 'Aktif'),
(503, 'china', 9, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(504, 'china', 10, 'Barbados', 'Perdagangan', 'Aktif'),
(505, 'filipina', 1, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(506, 'filipina', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(507, 'filipina', 3, 'Andorra', 'Perdagangan', 'Aktif'),
(508, 'filipina', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(509, 'filipina', 5, 'Australia', 'Perdagangan', 'Aktif'),
(510, 'filipina', 6, 'Bahama', 'Perdagangan', 'Aktif'),
(511, 'filipina', 7, 'Belanda', 'Perdagangan', 'Aktif'),
(512, 'filipina', 8, 'Austria', 'Perdagangan', 'Aktif'),
(513, 'georgia', 1, 'Bangladesh', 'Perdagangan', 'Aktif'),
(514, 'georgia', 2, 'Benin', 'Perdagangan', 'Aktif'),
(515, 'georgia', 3, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(516, 'georgia', 4, 'Andorra', 'Perdagangan', 'Aktif'),
(517, 'georgia', 5, 'Belarus', 'Perdagangan', 'Aktif'),
(518, 'georgia', 6, 'Afganistan', 'Perdagangan', 'Aktif'),
(519, 'georgia', 7, 'Brazil', 'Perdagangan', 'Aktif'),
(520, 'georgia', 8, 'Belize', 'Perdagangan', 'Aktif'),
(521, 'georgia', 9, 'Barbados', 'Perdagangan', 'Aktif'),
(522, 'georgia', 10, 'Brunei', 'Perdagangan', 'Aktif'),
(523, 'hong_kong', 1, 'Aljazair', 'Perdagangan', 'Aktif'),
(524, 'hong_kong', 2, 'Belize', 'Perdagangan', 'Aktif'),
(525, 'hong_kong', 3, 'Barbados', 'Perdagangan', 'Aktif'),
(526, 'hong_kong', 4, 'Botswana', 'Perdagangan', 'Aktif'),
(527, 'hong_kong', 5, 'Bhutan', 'Perdagangan', 'Aktif'),
(528, 'hong_kong', 6, 'Bolivia', 'Perdagangan', 'Aktif'),
(529, 'hong_kong', 7, 'Belgia', 'Perdagangan', 'Aktif'),
(530, 'india', 1, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(531, 'india', 2, 'Bahrain', 'Perdagangan', 'Aktif'),
(532, 'india', 3, 'Belanda', 'Perdagangan', 'Aktif'),
(533, 'india', 4, 'Bermuda', 'Perdagangan', 'Aktif'),
(534, 'india', 5, 'Belarus', 'Perdagangan', 'Aktif'),
(535, 'india', 6, 'Bahama', 'Perdagangan', 'Aktif'),
(536, 'india', 7, 'Aljazair', 'Perdagangan', 'Aktif'),
(537, 'india', 8, 'Andorra', 'Perdagangan', 'Aktif'),
(538, 'indonesia', 1, 'Belarus', 'Perdagangan', 'Aktif'),
(539, 'indonesia', 2, 'Benin', 'Perdagangan', 'Aktif'),
(540, 'indonesia', 3, 'Bahrain', 'Perdagangan', 'Aktif'),
(541, 'indonesia', 4, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(542, 'indonesia', 5, 'Australia', 'Perdagangan', 'Aktif'),
(543, 'indonesia', 6, 'Afganistan', 'Perdagangan', 'Aktif'),
(544, 'indonesia', 7, 'Austria', 'Perdagangan', 'Aktif'),
(545, 'indonesia', 8, 'Belanda', 'Perdagangan', 'Aktif'),
(546, 'irak', 1, 'Armenia', 'Perdagangan', 'Aktif'),
(547, 'irak', 2, 'Brazil', 'Perdagangan', 'Aktif'),
(548, 'irak', 3, 'Albania', 'Perdagangan', 'Aktif'),
(549, 'irak', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(550, 'irak', 5, 'Belarus', 'Perdagangan', 'Aktif'),
(551, 'irak', 6, 'Barbados', 'Perdagangan', 'Aktif'),
(552, 'irak', 7, 'Bahama', 'Perdagangan', 'Aktif'),
(553, 'irak', 8, 'Bolivia', 'Perdagangan', 'Aktif'),
(554, 'irak', 9, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(555, 'iran', 1, 'Andorra', 'Perdagangan', 'Aktif'),
(556, 'iran', 2, 'Benin', 'Perdagangan', 'Aktif'),
(557, 'iran', 3, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(558, 'iran', 4, 'Argentina', 'Perdagangan', 'Aktif'),
(559, 'iran', 5, 'Botswana', 'Perdagangan', 'Aktif'),
(560, 'iran', 6, 'Bermuda', 'Perdagangan', 'Aktif'),
(561, 'israel', 1, 'Belgia', 'Perdagangan', 'Aktif'),
(562, 'israel', 2, 'Bahrain', 'Perdagangan', 'Aktif'),
(563, 'israel', 3, 'Botswana', 'Perdagangan', 'Aktif'),
(564, 'israel', 4, 'Aljazair', 'Perdagangan', 'Aktif'),
(565, 'israel', 5, 'Austria', 'Perdagangan', 'Aktif'),
(566, 'israel', 6, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(567, 'israel', 7, 'Barbados', 'Perdagangan', 'Aktif'),
(568, 'israel', 8, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(569, 'jepang', 1, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(570, 'jepang', 2, 'Belanda', 'Perdagangan', 'Aktif'),
(571, 'jepang', 3, 'Belize', 'Perdagangan', 'Aktif'),
(572, 'jepang', 4, 'Bolivia', 'Perdagangan', 'Aktif'),
(573, 'jepang', 5, 'Barbados', 'Perdagangan', 'Aktif'),
(574, 'jepang', 6, 'Armenia', 'Perdagangan', 'Aktif'),
(575, 'jepang', 7, 'Botswana', 'Perdagangan', 'Aktif'),
(576, 'jepang', 8, 'Afganistan', 'Perdagangan', 'Aktif'),
(577, 'kamboja', 1, 'Andorra', 'Perdagangan', 'Aktif'),
(578, 'kamboja', 2, 'Argentina', 'Perdagangan', 'Aktif'),
(579, 'kamboja', 3, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(580, 'kamboja', 4, 'Albania', 'Perdagangan', 'Aktif'),
(581, 'kamboja', 5, 'Barbados', 'Perdagangan', 'Aktif'),
(582, 'kamboja', 6, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(583, 'kazakhstan', 1, 'Belgia', 'Perdagangan', 'Aktif'),
(584, 'kazakhstan', 2, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(585, 'kazakhstan', 3, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(586, 'kazakhstan', 4, 'Austria', 'Perdagangan', 'Aktif'),
(587, 'kazakhstan', 5, 'Australia', 'Perdagangan', 'Aktif'),
(588, 'kazakhstan', 6, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(589, 'kazakhstan', 7, 'Bahama', 'Perdagangan', 'Aktif'),
(590, 'kirgizstan', 1, 'Belanda', 'Perdagangan', 'Aktif'),
(591, 'kirgizstan', 2, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(592, 'kirgizstan', 3, 'Barbados', 'Perdagangan', 'Aktif'),
(593, 'kirgizstan', 4, 'Afganistan', 'Perdagangan', 'Aktif'),
(594, 'kirgizstan', 5, 'Benin', 'Perdagangan', 'Aktif'),
(595, 'kirgizstan', 6, 'Bahrain', 'Perdagangan', 'Aktif'),
(596, 'kirgizstan', 7, 'Angola', 'Perdagangan', 'Aktif'),
(597, 'korea_selatan', 1, 'Afganistan', 'Perdagangan', 'Aktif'),
(598, 'korea_selatan', 2, 'Barbados', 'Perdagangan', 'Aktif'),
(599, 'korea_selatan', 3, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(600, 'korea_selatan', 4, 'Angola', 'Perdagangan', 'Aktif'),
(601, 'korea_selatan', 5, 'Brunei', 'Perdagangan', 'Aktif'),
(602, 'korea_selatan', 6, 'Belgia', 'Perdagangan', 'Aktif'),
(603, 'korea_selatan', 7, 'Belize', 'Perdagangan', 'Aktif'),
(604, 'korea_utara', 1, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(605, 'korea_utara', 2, 'Australia', 'Perdagangan', 'Aktif'),
(606, 'korea_utara', 3, 'Andorra', 'Perdagangan', 'Aktif'),
(607, 'korea_utara', 4, 'Bermuda', 'Perdagangan', 'Aktif'),
(608, 'korea_utara', 5, 'Bangladesh', 'Perdagangan', 'Aktif'),
(609, 'korea_utara', 6, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(610, 'kuwait', 1, 'Belanda', 'Perdagangan', 'Aktif'),
(611, 'kuwait', 2, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(612, 'kuwait', 3, 'Andorra', 'Perdagangan', 'Aktif'),
(613, 'kuwait', 4, 'Afganistan', 'Perdagangan', 'Aktif'),
(614, 'kuwait', 5, 'Australia', 'Perdagangan', 'Aktif'),
(615, 'kuwait', 6, 'Armenia', 'Perdagangan', 'Aktif'),
(616, 'laos', 1, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(617, 'laos', 2, 'Botswana', 'Perdagangan', 'Aktif'),
(618, 'laos', 3, 'Armenia', 'Perdagangan', 'Aktif'),
(619, 'laos', 4, 'Bhutan', 'Perdagangan', 'Aktif'),
(620, 'laos', 5, 'Afganistan', 'Perdagangan', 'Aktif'),
(621, 'laos', 6, 'Bolivia', 'Perdagangan', 'Aktif'),
(622, 'laos', 7, 'Barbados', 'Perdagangan', 'Aktif'),
(623, 'laos', 8, 'Aljazair', 'Perdagangan', 'Aktif'),
(624, 'lebanon', 1, 'Bangladesh', 'Perdagangan', 'Aktif'),
(625, 'lebanon', 2, 'Angola', 'Perdagangan', 'Aktif'),
(626, 'lebanon', 3, 'Afganistan', 'Perdagangan', 'Aktif'),
(627, 'lebanon', 4, 'Benin', 'Perdagangan', 'Aktif'),
(628, 'lebanon', 5, 'Andorra', 'Perdagangan', 'Aktif'),
(629, 'lebanon', 6, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(630, 'makau', 1, 'Albania', 'Perdagangan', 'Aktif'),
(631, 'makau', 2, 'Australia', 'Perdagangan', 'Aktif'),
(632, 'makau', 3, 'Belanda', 'Perdagangan', 'Aktif'),
(633, 'makau', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(634, 'makau', 5, 'Bahama', 'Perdagangan', 'Aktif'),
(635, 'makau', 6, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(636, 'makau', 7, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(637, 'makau', 8, 'Belize', 'Perdagangan', 'Aktif'),
(638, 'makau', 9, 'Bhutan', 'Perdagangan', 'Aktif'),
(639, 'makau', 10, 'Benin', 'Perdagangan', 'Aktif'),
(640, 'malaysia', 1, 'Bermuda', 'Perdagangan', 'Aktif'),
(641, 'malaysia', 2, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(642, 'malaysia', 3, 'Bangladesh', 'Perdagangan', 'Aktif'),
(643, 'malaysia', 4, 'Albania', 'Perdagangan', 'Aktif'),
(644, 'malaysia', 5, 'Angola', 'Perdagangan', 'Aktif'),
(645, 'malaysia', 6, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(646, 'malaysia', 7, 'Benin', 'Perdagangan', 'Aktif'),
(647, 'maldives', 1, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(648, 'maldives', 2, 'Andorra', 'Perdagangan', 'Aktif'),
(649, 'maldives', 3, 'Aljazair', 'Perdagangan', 'Aktif'),
(650, 'maldives', 4, 'Belarus', 'Perdagangan', 'Aktif'),
(651, 'maldives', 5, 'Armenia', 'Perdagangan', 'Aktif'),
(652, 'maldives', 6, 'Bangladesh', 'Perdagangan', 'Aktif'),
(653, 'maldives', 7, 'Bhutan', 'Perdagangan', 'Aktif'),
(654, 'maldives', 8, 'Bermuda', 'Perdagangan', 'Aktif'),
(655, 'maldives', 9, 'Bahama', 'Perdagangan', 'Aktif'),
(656, 'maldives', 10, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(657, 'mongolia', 1, 'Bahama', 'Perdagangan', 'Aktif'),
(658, 'mongolia', 2, 'Benin', 'Perdagangan', 'Aktif'),
(659, 'mongolia', 3, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(660, 'mongolia', 4, 'Austria', 'Perdagangan', 'Aktif'),
(661, 'mongolia', 5, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(662, 'mongolia', 6, 'Belize', 'Perdagangan', 'Aktif'),
(663, 'myanmar', 1, 'Australia', 'Perdagangan', 'Aktif'),
(664, 'myanmar', 2, 'Bahrain', 'Perdagangan', 'Aktif'),
(665, 'myanmar', 3, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(666, 'myanmar', 4, 'Argentina', 'Perdagangan', 'Aktif'),
(667, 'myanmar', 5, 'Barbados', 'Perdagangan', 'Aktif'),
(668, 'myanmar', 6, 'Benin', 'Perdagangan', 'Aktif'),
(669, 'myanmar', 7, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(670, 'myanmar', 8, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(671, 'nepal', 1, 'Angola', 'Perdagangan', 'Aktif'),
(672, 'nepal', 2, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(673, 'nepal', 3, 'Albania', 'Perdagangan', 'Aktif'),
(674, 'nepal', 4, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(675, 'nepal', 5, 'Belize', 'Perdagangan', 'Aktif'),
(676, 'nepal', 6, 'Bangladesh', 'Perdagangan', 'Aktif'),
(677, 'nepal', 7, 'Bahama', 'Perdagangan', 'Aktif'),
(678, 'oman', 1, 'Australia', 'Perdagangan', 'Aktif'),
(679, 'oman', 2, 'Afganistan', 'Perdagangan', 'Aktif'),
(680, 'oman', 3, 'Albania', 'Perdagangan', 'Aktif'),
(681, 'oman', 4, 'Belanda', 'Perdagangan', 'Aktif'),
(682, 'oman', 5, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(683, 'oman', 6, 'Bermuda', 'Perdagangan', 'Aktif'),
(684, 'pakistan', 1, 'Bermuda', 'Perdagangan', 'Aktif'),
(685, 'pakistan', 2, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(686, 'pakistan', 3, 'Aljazair', 'Perdagangan', 'Aktif'),
(687, 'pakistan', 4, 'Belize', 'Perdagangan', 'Aktif'),
(688, 'pakistan', 5, 'Andorra', 'Perdagangan', 'Aktif'),
(689, 'pakistan', 6, 'Bangladesh', 'Perdagangan', 'Aktif'),
(690, 'pakistan', 7, 'Brazil', 'Perdagangan', 'Aktif'),
(691, 'pakistan', 8, 'Angola', 'Perdagangan', 'Aktif'),
(692, 'pakistan', 9, 'Barbados', 'Perdagangan', 'Aktif'),
(693, 'palestina', 1, 'Belgia', 'Perdagangan', 'Aktif'),
(694, 'palestina', 2, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(695, 'palestina', 3, 'Albania', 'Perdagangan', 'Aktif'),
(696, 'palestina', 4, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(697, 'palestina', 5, 'Bahrain', 'Perdagangan', 'Aktif'),
(698, 'palestina', 6, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(699, 'palestina', 7, 'Angola', 'Perdagangan', 'Aktif'),
(700, 'palestina', 8, 'Aljazair', 'Perdagangan', 'Aktif'),
(701, 'palestina', 9, 'Belize', 'Perdagangan', 'Aktif'),
(702, 'palestina', 10, 'Armenia', 'Perdagangan', 'Aktif'),
(703, 'qatar', 1, 'Belanda', 'Perdagangan', 'Aktif'),
(704, 'qatar', 2, 'Brunei', 'Perdagangan', 'Aktif'),
(705, 'qatar', 3, 'Australia', 'Perdagangan', 'Aktif'),
(706, 'qatar', 4, 'Argentina', 'Perdagangan', 'Aktif'),
(707, 'qatar', 5, 'Bhutan', 'Perdagangan', 'Aktif'),
(708, 'qatar', 6, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(709, 'qatar', 7, 'Benin', 'Perdagangan', 'Aktif'),
(710, 'qatar', 8, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(711, 'qatar', 9, 'Bermuda', 'Perdagangan', 'Aktif'),
(712, 'qatar', 10, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(713, 'republik_timor_leste', 1, 'Belgia', 'Perdagangan', 'Aktif'),
(714, 'republik_timor_leste', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(715, 'republik_timor_leste', 3, 'Argentina', 'Perdagangan', 'Aktif'),
(716, 'republik_timor_leste', 4, 'Bolivia', 'Perdagangan', 'Aktif'),
(717, 'republik_timor_leste', 5, 'Botswana', 'Perdagangan', 'Aktif'),
(718, 'republik_timor_leste', 6, 'Austria', 'Perdagangan', 'Aktif'),
(719, 'republik_timor_leste', 7, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(720, 'singapura', 1, 'Benin', 'Perdagangan', 'Aktif'),
(721, 'singapura', 2, 'Bangladesh', 'Perdagangan', 'Aktif'),
(722, 'singapura', 3, 'Argentina', 'Perdagangan', 'Aktif'),
(723, 'singapura', 4, 'Bolivia', 'Perdagangan', 'Aktif'),
(724, 'singapura', 5, 'Armenia', 'Perdagangan', 'Aktif'),
(725, 'singapura', 6, 'Afganistan', 'Perdagangan', 'Aktif'),
(726, 'sri_lanka', 1, 'Argentina', 'Perdagangan', 'Aktif'),
(727, 'sri_lanka', 2, 'Brazil', 'Perdagangan', 'Aktif'),
(728, 'sri_lanka', 3, 'Angola', 'Perdagangan', 'Aktif'),
(729, 'sri_lanka', 4, 'Albania', 'Perdagangan', 'Aktif'),
(730, 'sri_lanka', 5, 'Bangladesh', 'Perdagangan', 'Aktif'),
(731, 'sri_lanka', 6, 'Brunei', 'Perdagangan', 'Aktif'),
(732, 'sri_lanka', 7, 'Benin', 'Perdagangan', 'Aktif'),
(733, 'sri_lanka', 8, 'Bahrain', 'Perdagangan', 'Aktif'),
(734, 'suriah', 1, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(735, 'suriah', 2, 'Argentina', 'Perdagangan', 'Aktif'),
(736, 'suriah', 3, 'Brunei', 'Perdagangan', 'Aktif'),
(737, 'suriah', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(738, 'suriah', 5, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(739, 'suriah', 6, 'Belize', 'Perdagangan', 'Aktif'),
(740, 'suriah', 7, 'Angola', 'Perdagangan', 'Aktif'),
(741, 'taiwan', 1, 'Benin', 'Perdagangan', 'Aktif'),
(742, 'taiwan', 2, 'Aljazair', 'Perdagangan', 'Aktif'),
(743, 'taiwan', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(744, 'taiwan', 4, 'Bolivia', 'Perdagangan', 'Aktif'),
(745, 'taiwan', 5, 'Austria', 'Perdagangan', 'Aktif'),
(746, 'taiwan', 6, 'Botswana', 'Perdagangan', 'Aktif'),
(747, 'tajikistan', 1, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(748, 'tajikistan', 2, 'Austria', 'Perdagangan', 'Aktif'),
(749, 'tajikistan', 3, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(750, 'tajikistan', 4, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(751, 'tajikistan', 5, 'Aljazair', 'Perdagangan', 'Aktif'),
(752, 'tajikistan', 6, 'Belarus', 'Perdagangan', 'Aktif'),
(753, 'thailand', 1, 'Bhutan', 'Perdagangan', 'Aktif'),
(754, 'thailand', 2, 'Bermuda', 'Perdagangan', 'Aktif'),
(755, 'thailand', 3, 'Angola', 'Perdagangan', 'Aktif'),
(756, 'thailand', 4, 'Brazil', 'Perdagangan', 'Aktif'),
(757, 'thailand', 5, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(758, 'thailand', 6, 'Bangladesh', 'Perdagangan', 'Aktif'),
(759, 'thailand', 7, 'Belize', 'Perdagangan', 'Aktif'),
(760, 'turkmenistan', 1, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(761, 'turkmenistan', 2, 'Bahama', 'Perdagangan', 'Aktif'),
(762, 'turkmenistan', 3, 'Botswana', 'Perdagangan', 'Aktif'),
(763, 'turkmenistan', 4, 'Belanda', 'Perdagangan', 'Aktif'),
(764, 'turkmenistan', 5, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(765, 'turkmenistan', 6, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(766, 'uni_emirat_arab', 1, 'Belarus', 'Perdagangan', 'Aktif'),
(767, 'uni_emirat_arab', 2, 'Aljazair', 'Perdagangan', 'Aktif'),
(768, 'uni_emirat_arab', 3, 'Belgia', 'Perdagangan', 'Aktif'),
(769, 'uni_emirat_arab', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(770, 'uni_emirat_arab', 5, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(771, 'uni_emirat_arab', 6, 'Andorra', 'Perdagangan', 'Aktif'),
(772, 'uzbekistan', 1, 'Bangladesh', 'Perdagangan', 'Aktif'),
(773, 'uzbekistan', 2, 'Brazil', 'Perdagangan', 'Aktif'),
(774, 'uzbekistan', 3, 'Belanda', 'Perdagangan', 'Aktif'),
(775, 'uzbekistan', 4, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(776, 'uzbekistan', 5, 'Afganistan', 'Perdagangan', 'Aktif'),
(777, 'uzbekistan', 6, 'Brunei', 'Perdagangan', 'Aktif'),
(778, 'uzbekistan', 7, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(779, 'vietnam', 1, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(780, 'vietnam', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(781, 'vietnam', 3, 'Bahama', 'Perdagangan', 'Aktif'),
(782, 'vietnam', 4, 'Belarus', 'Perdagangan', 'Aktif'),
(783, 'vietnam', 5, 'Bolivia', 'Perdagangan', 'Aktif'),
(784, 'vietnam', 6, 'Barbados', 'Perdagangan', 'Aktif'),
(785, 'yaman', 1, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(786, 'yaman', 2, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(787, 'yaman', 3, 'Argentina', 'Perdagangan', 'Aktif'),
(788, 'yaman', 4, 'Belgia', 'Perdagangan', 'Aktif'),
(789, 'yaman', 5, 'Bermuda', 'Perdagangan', 'Aktif'),
(790, 'yaman', 6, 'Bhutan', 'Perdagangan', 'Aktif'),
(791, 'yordania', 1, 'Argentina', 'Perdagangan', 'Aktif'),
(792, 'yordania', 2, 'Bahrain', 'Perdagangan', 'Aktif'),
(793, 'yordania', 3, 'Angola', 'Perdagangan', 'Aktif'),
(794, 'yordania', 4, 'Belgia', 'Perdagangan', 'Aktif'),
(795, 'yordania', 5, 'Barbados', 'Perdagangan', 'Aktif'),
(796, 'yordania', 6, 'Brazil', 'Perdagangan', 'Aktif'),
(797, 'albania', 1, 'Armenia', 'Perdagangan', 'Aktif'),
(798, 'albania', 2, 'Brazil', 'Perdagangan', 'Aktif'),
(799, 'albania', 3, 'Bahrain', 'Perdagangan', 'Aktif'),
(800, 'albania', 4, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(801, 'albania', 5, 'Angola', 'Perdagangan', 'Aktif'),
(802, 'albania', 6, 'Bermuda', 'Perdagangan', 'Aktif'),
(803, 'albania', 7, 'Argentina', 'Perdagangan', 'Aktif'),
(804, 'andorra', 1, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(805, 'andorra', 2, 'Aljazair', 'Perdagangan', 'Aktif'),
(806, 'andorra', 3, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(807, 'andorra', 4, 'Brazil', 'Perdagangan', 'Aktif'),
(808, 'andorra', 5, 'Belarus', 'Perdagangan', 'Aktif'),
(809, 'andorra', 6, 'Brunei', 'Perdagangan', 'Aktif'),
(810, 'andorra', 7, 'Bhutan', 'Perdagangan', 'Aktif'),
(811, 'austria', 1, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(812, 'austria', 2, 'Brazil', 'Perdagangan', 'Aktif'),
(813, 'austria', 3, 'Angola', 'Perdagangan', 'Aktif'),
(814, 'austria', 4, 'Bhutan', 'Perdagangan', 'Aktif'),
(815, 'austria', 5, 'Belgia', 'Perdagangan', 'Aktif'),
(816, 'austria', 6, 'Afganistan', 'Perdagangan', 'Aktif'),
(817, 'belanda', 1, 'Afganistan', 'Perdagangan', 'Aktif'),
(818, 'belanda', 2, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(819, 'belanda', 3, 'Belarus', 'Perdagangan', 'Aktif'),
(820, 'belanda', 4, 'Brazil', 'Perdagangan', 'Aktif'),
(821, 'belanda', 5, 'Australia', 'Perdagangan', 'Aktif'),
(822, 'belanda', 6, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(823, 'belanda', 7, 'Bangladesh', 'Perdagangan', 'Aktif'),
(824, 'belanda', 8, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(825, 'belarus', 1, 'Belanda', 'Perdagangan', 'Aktif'),
(826, 'belarus', 2, 'Belgia', 'Perdagangan', 'Aktif'),
(827, 'belarus', 3, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(828, 'belarus', 4, 'Brunei', 'Perdagangan', 'Aktif'),
(829, 'belarus', 5, 'Afganistan', 'Perdagangan', 'Aktif'),
(830, 'belarus', 6, 'Bahama', 'Perdagangan', 'Aktif'),
(831, 'belgia', 1, 'Barbados', 'Perdagangan', 'Aktif'),
(832, 'belgia', 2, 'Aljazair', 'Perdagangan', 'Aktif'),
(833, 'belgia', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(834, 'belgia', 4, 'Andorra', 'Perdagangan', 'Aktif'),
(835, 'belgia', 5, 'Armenia', 'Perdagangan', 'Aktif'),
(836, 'belgia', 6, 'Bulgaria', 'Perdagangan', 'Aktif'),
(837, 'belgia', 7, 'Bahrain', 'Perdagangan', 'Aktif'),
(838, 'belgia', 8, 'Botswana', 'Perdagangan', 'Aktif'),
(839, 'belgia', 9, 'Belanda', 'Perdagangan', 'Aktif'),
(840, 'belgia', 10, 'Belarus', 'Perdagangan', 'Aktif'),
(841, 'bosnia_dan_hercegovina', 1, 'Bolivia', 'Perdagangan', 'Aktif'),
(842, 'bosnia_dan_hercegovina', 2, 'Angola', 'Perdagangan', 'Aktif'),
(843, 'bosnia_dan_hercegovina', 3, 'Bahama', 'Perdagangan', 'Aktif'),
(844, 'bosnia_dan_hercegovina', 4, 'Bahrain', 'Perdagangan', 'Aktif'),
(845, 'bosnia_dan_hercegovina', 5, 'Albania', 'Perdagangan', 'Aktif'),
(846, 'bosnia_dan_hercegovina', 6, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(847, 'bosnia_dan_hercegovina', 7, 'Barbados', 'Perdagangan', 'Aktif'),
(848, 'bosnia_dan_hercegovina', 8, 'Belanda', 'Perdagangan', 'Aktif'),
(849, 'bosnia_dan_hercegovina', 9, 'Benin', 'Perdagangan', 'Aktif'),
(850, 'bosnia_dan_hercegovina', 10, 'Belgia', 'Perdagangan', 'Aktif'),
(851, 'bulgaria', 1, 'Brazil', 'Perdagangan', 'Aktif'),
(852, 'bulgaria', 2, 'Austria', 'Perdagangan', 'Aktif'),
(853, 'bulgaria', 3, 'Andorra', 'Perdagangan', 'Aktif'),
(854, 'bulgaria', 4, 'Benin', 'Perdagangan', 'Aktif'),
(855, 'bulgaria', 5, 'Brunei', 'Perdagangan', 'Aktif'),
(856, 'bulgaria', 6, 'Australia', 'Perdagangan', 'Aktif'),
(857, 'ceko', 1, 'Belanda', 'Perdagangan', 'Aktif'),
(858, 'ceko', 2, 'Brazil', 'Perdagangan', 'Aktif'),
(859, 'ceko', 3, 'Armenia', 'Perdagangan', 'Aktif'),
(860, 'ceko', 4, 'Botswana', 'Perdagangan', 'Aktif'),
(861, 'ceko', 5, 'Australia', 'Perdagangan', 'Aktif'),
(862, 'ceko', 6, 'Bahrain', 'Perdagangan', 'Aktif'),
(863, 'ceko', 7, 'Austria', 'Perdagangan', 'Aktif'),
(864, 'ceko', 8, 'Bermuda', 'Perdagangan', 'Aktif'),
(865, 'ceko', 9, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(866, 'ceko', 10, 'Aljazair', 'Perdagangan', 'Aktif'),
(867, 'denmark', 1, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(868, 'denmark', 2, 'Benin', 'Perdagangan', 'Aktif'),
(869, 'denmark', 3, 'Bermuda', 'Perdagangan', 'Aktif'),
(870, 'denmark', 4, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(871, 'denmark', 5, 'Belgia', 'Perdagangan', 'Aktif'),
(872, 'denmark', 6, 'Belarus', 'Perdagangan', 'Aktif'),
(873, 'denmark', 7, 'Bolivia', 'Perdagangan', 'Aktif'),
(874, 'denmark', 8, 'Afganistan', 'Perdagangan', 'Aktif'),
(875, 'estonia', 1, 'Aljazair', 'Perdagangan', 'Aktif'),
(876, 'estonia', 2, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(877, 'estonia', 3, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(878, 'estonia', 4, 'Bermuda', 'Perdagangan', 'Aktif'),
(879, 'estonia', 5, 'Bangladesh', 'Perdagangan', 'Aktif'),
(880, 'estonia', 6, 'Benin', 'Perdagangan', 'Aktif'),
(881, 'estonia', 7, 'Argentina', 'Perdagangan', 'Aktif'),
(882, 'estonia', 8, 'Albania', 'Perdagangan', 'Aktif'),
(883, 'estonia', 9, 'Belanda', 'Perdagangan', 'Aktif'),
(884, 'finlandia', 1, 'Angola', 'Perdagangan', 'Aktif'),
(885, 'finlandia', 2, 'Bahama', 'Perdagangan', 'Aktif'),
(886, 'finlandia', 3, 'Austria', 'Perdagangan', 'Aktif'),
(887, 'finlandia', 4, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(888, 'finlandia', 5, 'Belarus', 'Perdagangan', 'Aktif'),
(889, 'finlandia', 6, 'Albania', 'Perdagangan', 'Aktif'),
(890, 'finlandia', 7, 'Bahrain', 'Perdagangan', 'Aktif'),
(891, 'finlandia', 8, 'Botswana', 'Perdagangan', 'Aktif'),
(892, 'finlandia', 9, 'Bolivia', 'Perdagangan', 'Aktif'),
(893, 'finlandia', 10, 'Argentina', 'Perdagangan', 'Aktif'),
(894, 'gibraltar', 1, 'Belize', 'Perdagangan', 'Aktif'),
(895, 'gibraltar', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(896, 'gibraltar', 3, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(897, 'gibraltar', 4, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(898, 'gibraltar', 5, 'Bolivia', 'Perdagangan', 'Aktif'),
(899, 'gibraltar', 6, 'Bangladesh', 'Perdagangan', 'Aktif'),
(900, 'gibraltar', 7, 'Belanda', 'Perdagangan', 'Aktif'),
(901, 'gibraltar', 8, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(902, 'gibraltar', 9, 'Brazil', 'Perdagangan', 'Aktif'),
(903, 'hungaria', 1, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(904, 'hungaria', 2, 'Bermuda', 'Perdagangan', 'Aktif'),
(905, 'hungaria', 3, 'Belarus', 'Perdagangan', 'Aktif'),
(906, 'hungaria', 4, 'Andorra', 'Perdagangan', 'Aktif'),
(907, 'hungaria', 5, 'Bhutan', 'Perdagangan', 'Aktif'),
(908, 'hungaria', 6, 'Armenia', 'Perdagangan', 'Aktif'),
(909, 'hungaria', 7, 'Botswana', 'Perdagangan', 'Aktif'),
(910, 'hungaria', 8, 'Brunei', 'Perdagangan', 'Aktif'),
(911, 'hungaria', 9, 'Austria', 'Perdagangan', 'Aktif'),
(912, 'hungaria', 10, 'Benin', 'Perdagangan', 'Aktif'),
(913, 'inggris', 1, 'Brunei', 'Perdagangan', 'Aktif'),
(914, 'inggris', 2, 'Brazil', 'Perdagangan', 'Aktif'),
(915, 'inggris', 3, 'Australia', 'Perdagangan', 'Aktif'),
(916, 'inggris', 4, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(917, 'inggris', 5, 'Austria', 'Perdagangan', 'Aktif'),
(918, 'inggris', 6, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(919, 'irlandia', 1, 'Andorra', 'Perdagangan', 'Aktif'),
(920, 'irlandia', 2, 'Bahrain', 'Perdagangan', 'Aktif'),
(921, 'irlandia', 3, 'Brunei', 'Perdagangan', 'Aktif'),
(922, 'irlandia', 4, 'Bermuda', 'Perdagangan', 'Aktif'),
(923, 'irlandia', 5, 'Austria', 'Perdagangan', 'Aktif'),
(924, 'irlandia', 6, 'Belize', 'Perdagangan', 'Aktif'),
(925, 'irlandia', 7, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(926, 'irlandia', 8, 'Bahama', 'Perdagangan', 'Aktif'),
(927, 'islandia', 1, 'Belize', 'Perdagangan', 'Aktif'),
(928, 'islandia', 2, 'Barbados', 'Perdagangan', 'Aktif'),
(929, 'islandia', 3, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(930, 'islandia', 4, 'Andorra', 'Perdagangan', 'Aktif'),
(931, 'islandia', 5, 'Belanda', 'Perdagangan', 'Aktif'),
(932, 'islandia', 6, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(933, 'islandia', 7, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(934, 'islandia', 8, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(935, 'italia', 1, 'Brazil', 'Perdagangan', 'Aktif'),
(936, 'italia', 2, 'Afganistan', 'Perdagangan', 'Aktif'),
(937, 'italia', 3, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(938, 'italia', 4, 'Belgia', 'Perdagangan', 'Aktif'),
(939, 'italia', 5, 'Bolivia', 'Perdagangan', 'Aktif'),
(940, 'italia', 6, 'Armenia', 'Perdagangan', 'Aktif'),
(941, 'jerman', 1, 'Australia', 'Perdagangan', 'Aktif'),
(942, 'jerman', 2, 'Aljazair', 'Perdagangan', 'Aktif'),
(943, 'jerman', 3, 'Brunei', 'Perdagangan', 'Aktif'),
(944, 'jerman', 4, 'Bolivia', 'Perdagangan', 'Aktif'),
(945, 'jerman', 5, 'Brazil', 'Perdagangan', 'Aktif'),
(946, 'jerman', 6, 'Albania', 'Perdagangan', 'Aktif'),
(947, 'kepulauan_faroe', 1, 'Benin', 'Perdagangan', 'Aktif'),
(948, 'kepulauan_faroe', 2, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(949, 'kepulauan_faroe', 3, 'Bolivia', 'Perdagangan', 'Aktif'),
(950, 'kepulauan_faroe', 4, 'Albania', 'Perdagangan', 'Aktif'),
(951, 'kepulauan_faroe', 5, 'Bhutan', 'Perdagangan', 'Aktif'),
(952, 'kepulauan_faroe', 6, 'Bahama', 'Perdagangan', 'Aktif'),
(953, 'kepulauan_faroe', 7, 'Argentina', 'Perdagangan', 'Aktif'),
(954, 'kepulauan_faroe', 8, 'Botswana', 'Perdagangan', 'Aktif'),
(955, 'kosovo', 1, 'Albania', 'Perdagangan', 'Aktif'),
(956, 'kosovo', 2, 'Belize', 'Perdagangan', 'Aktif'),
(957, 'kosovo', 3, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(958, 'kosovo', 4, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(959, 'kosovo', 5, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(960, 'kosovo', 6, 'Bermuda', 'Perdagangan', 'Aktif'),
(961, 'kosovo', 7, 'Bangladesh', 'Perdagangan', 'Aktif'),
(962, 'kosovo', 8, 'Afganistan', 'Perdagangan', 'Aktif'),
(963, 'kosovo', 9, 'Austria', 'Perdagangan', 'Aktif'),
(964, 'kroasia', 1, 'Brunei', 'Perdagangan', 'Aktif'),
(965, 'kroasia', 2, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(966, 'kroasia', 3, 'Bahama', 'Perdagangan', 'Aktif'),
(967, 'kroasia', 4, 'Argentina', 'Perdagangan', 'Aktif'),
(968, 'kroasia', 5, 'Brazil', 'Perdagangan', 'Aktif'),
(969, 'kroasia', 6, 'Bhutan', 'Perdagangan', 'Aktif'),
(970, 'kroasia', 7, 'Armenia', 'Perdagangan', 'Aktif'),
(971, 'latvia', 1, 'Belize', 'Perdagangan', 'Aktif'),
(972, 'latvia', 2, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(973, 'latvia', 3, 'Bhutan', 'Perdagangan', 'Aktif'),
(974, 'latvia', 4, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(975, 'latvia', 5, 'Brunei', 'Perdagangan', 'Aktif'),
(976, 'latvia', 6, 'Barbados', 'Perdagangan', 'Aktif'),
(977, 'latvia', 7, 'Armenia', 'Perdagangan', 'Aktif'),
(978, 'latvia', 8, 'Andorra', 'Perdagangan', 'Aktif'),
(979, 'latvia', 9, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(980, 'liechtenstein', 1, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(981, 'liechtenstein', 2, 'Barbados', 'Perdagangan', 'Aktif'),
(982, 'liechtenstein', 3, 'Afganistan', 'Perdagangan', 'Aktif'),
(983, 'liechtenstein', 4, 'Benin', 'Perdagangan', 'Aktif'),
(984, 'liechtenstein', 5, 'Bahrain', 'Perdagangan', 'Aktif'),
(985, 'liechtenstein', 6, 'Albania', 'Perdagangan', 'Aktif'),
(986, 'liechtenstein', 7, 'Belarus', 'Perdagangan', 'Aktif'),
(987, 'liechtenstein', 8, 'Belanda', 'Perdagangan', 'Aktif'),
(988, 'lithuania', 1, 'Albania', 'Perdagangan', 'Aktif'),
(989, 'lithuania', 2, 'Afganistan', 'Perdagangan', 'Aktif'),
(990, 'lithuania', 3, 'Andorra', 'Perdagangan', 'Aktif'),
(991, 'lithuania', 4, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(992, 'lithuania', 5, 'Austria', 'Perdagangan', 'Aktif'),
(993, 'lithuania', 6, 'Bhutan', 'Perdagangan', 'Aktif'),
(994, 'lithuania', 7, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(995, 'lithuania', 8, 'Belanda', 'Perdagangan', 'Aktif'),
(996, 'luksemburg', 1, 'Australia', 'Perdagangan', 'Aktif'),
(997, 'luksemburg', 2, 'Benin', 'Perdagangan', 'Aktif'),
(998, 'luksemburg', 3, 'Afganistan', 'Perdagangan', 'Aktif'),
(999, 'luksemburg', 4, 'Albania', 'Perdagangan', 'Aktif'),
(1000, 'luksemburg', 5, 'Bangladesh', 'Perdagangan', 'Aktif');

INSERT INTO database_mitra_perdagangan (
    country_id, country_slug, mitra_no, mitra_country, trade_type, status
) VALUES
(1001, 'luksemburg', 6, 'Brazil', 'Perdagangan', 'Aktif'),
(1002, 'luksemburg', 7, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1003, 'luksemburg', 8, 'Belize', 'Perdagangan', 'Aktif'),
(1004, 'luksemburg', 9, 'Argentina', 'Perdagangan', 'Aktif'),
(1005, 'luksemburg', 10, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1006, 'makedonia_utara', 1, 'Bolivia', 'Perdagangan', 'Aktif'),
(1007, 'makedonia_utara', 2, 'Belgia', 'Perdagangan', 'Aktif'),
(1008, 'makedonia_utara', 3, 'Andorra', 'Perdagangan', 'Aktif'),
(1009, 'makedonia_utara', 4, 'Bermuda', 'Perdagangan', 'Aktif'),
(1010, 'makedonia_utara', 5, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1011, 'makedonia_utara', 6, 'Aljazair', 'Perdagangan', 'Aktif'),
(1012, 'makedonia_utara', 7, 'Bahrain', 'Perdagangan', 'Aktif'),
(1013, 'malta', 1, 'Botswana', 'Perdagangan', 'Aktif'),
(1014, 'malta', 2, 'Argentina', 'Perdagangan', 'Aktif'),
(1015, 'malta', 3, 'Bhutan', 'Perdagangan', 'Aktif'),
(1016, 'malta', 4, 'Afganistan', 'Perdagangan', 'Aktif'),
(1017, 'malta', 5, 'Andorra', 'Perdagangan', 'Aktif'),
(1018, 'malta', 6, 'Belize', 'Perdagangan', 'Aktif'),
(1019, 'malta', 7, 'Australia', 'Perdagangan', 'Aktif'),
(1020, 'moldova', 1, 'Bermuda', 'Perdagangan', 'Aktif'),
(1021, 'moldova', 2, 'Bahama', 'Perdagangan', 'Aktif'),
(1022, 'moldova', 3, 'Bhutan', 'Perdagangan', 'Aktif'),
(1023, 'moldova', 4, 'Armenia', 'Perdagangan', 'Aktif'),
(1024, 'moldova', 5, 'Australia', 'Perdagangan', 'Aktif'),
(1025, 'moldova', 6, 'Angola', 'Perdagangan', 'Aktif'),
(1026, 'monako', 1, 'Barbados', 'Perdagangan', 'Aktif'),
(1027, 'monako', 2, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1028, 'monako', 3, 'Bermuda', 'Perdagangan', 'Aktif'),
(1029, 'monako', 4, 'Belize', 'Perdagangan', 'Aktif'),
(1030, 'monako', 5, 'Botswana', 'Perdagangan', 'Aktif'),
(1031, 'monako', 6, 'Australia', 'Perdagangan', 'Aktif'),
(1032, 'monako', 7, 'Bahama', 'Perdagangan', 'Aktif'),
(1033, 'monako', 8, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1034, 'montenegro', 1, 'Bermuda', 'Perdagangan', 'Aktif'),
(1035, 'montenegro', 2, 'Albania', 'Perdagangan', 'Aktif'),
(1036, 'montenegro', 3, 'Botswana', 'Perdagangan', 'Aktif'),
(1037, 'montenegro', 4, 'Bhutan', 'Perdagangan', 'Aktif'),
(1038, 'montenegro', 5, 'Belize', 'Perdagangan', 'Aktif'),
(1039, 'montenegro', 6, 'Bolivia', 'Perdagangan', 'Aktif'),
(1040, 'montenegro', 7, 'Brunei', 'Perdagangan', 'Aktif'),
(1041, 'montenegro', 8, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1042, 'norwegia', 1, 'Brazil', 'Perdagangan', 'Aktif'),
(1043, 'norwegia', 2, 'Albania', 'Perdagangan', 'Aktif'),
(1044, 'norwegia', 3, 'Andorra', 'Perdagangan', 'Aktif'),
(1045, 'norwegia', 4, 'Brunei', 'Perdagangan', 'Aktif'),
(1046, 'norwegia', 5, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1047, 'norwegia', 6, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1048, 'polandia', 1, 'Andorra', 'Perdagangan', 'Aktif'),
(1049, 'polandia', 2, 'Benin', 'Perdagangan', 'Aktif'),
(1050, 'polandia', 3, 'Belize', 'Perdagangan', 'Aktif'),
(1051, 'polandia', 4, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1052, 'polandia', 5, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1053, 'polandia', 6, 'Belarus', 'Perdagangan', 'Aktif'),
(1054, 'polandia', 7, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1055, 'portugal', 1, 'Argentina', 'Perdagangan', 'Aktif'),
(1056, 'portugal', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1057, 'portugal', 3, 'Barbados', 'Perdagangan', 'Aktif'),
(1058, 'portugal', 4, 'Bolivia', 'Perdagangan', 'Aktif'),
(1059, 'portugal', 5, 'Angola', 'Perdagangan', 'Aktif'),
(1060, 'portugal', 6, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1061, 'portugal', 7, 'Belgia', 'Perdagangan', 'Aktif'),
(1062, 'prancis', 1, 'Armenia', 'Perdagangan', 'Aktif'),
(1063, 'prancis', 2, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1064, 'prancis', 3, 'Belarus', 'Perdagangan', 'Aktif'),
(1065, 'prancis', 4, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1066, 'prancis', 5, 'Belize', 'Perdagangan', 'Aktif'),
(1067, 'prancis', 6, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1068, 'prancis', 7, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1069, 'republik_rumania', 1, 'Angola', 'Perdagangan', 'Aktif'),
(1070, 'republik_rumania', 2, 'Argentina', 'Perdagangan', 'Aktif'),
(1071, 'republik_rumania', 3, 'Belgia', 'Perdagangan', 'Aktif'),
(1072, 'republik_rumania', 4, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1073, 'republik_rumania', 5, 'Belarus', 'Perdagangan', 'Aktif'),
(1074, 'republik_rumania', 6, 'Brunei', 'Perdagangan', 'Aktif'),
(1075, 'republik_rumania', 7, 'Botswana', 'Perdagangan', 'Aktif'),
(1076, 'republik_serbia', 1, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1077, 'republik_serbia', 2, 'Bahama', 'Perdagangan', 'Aktif'),
(1078, 'republik_serbia', 3, 'Belize', 'Perdagangan', 'Aktif'),
(1079, 'republik_serbia', 4, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1080, 'republik_serbia', 5, 'Brazil', 'Perdagangan', 'Aktif'),
(1081, 'republik_serbia', 6, 'Afganistan', 'Perdagangan', 'Aktif'),
(1082, 'republik_serbia', 7, 'Bahrain', 'Perdagangan', 'Aktif'),
(1083, 'republik_serbia', 8, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1084, 'republik_serbia', 9, 'Belarus', 'Perdagangan', 'Aktif'),
(1085, 'republik_serbia', 10, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1086, 'rusia', 1, 'Belgia', 'Perdagangan', 'Aktif'),
(1087, 'rusia', 2, 'Belanda', 'Perdagangan', 'Aktif'),
(1088, 'rusia', 3, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1089, 'rusia', 4, 'Afganistan', 'Perdagangan', 'Aktif'),
(1090, 'rusia', 5, 'Bahrain', 'Perdagangan', 'Aktif'),
(1091, 'rusia', 6, 'Aljazair', 'Perdagangan', 'Aktif'),
(1092, 'rusia', 7, 'Andorra', 'Perdagangan', 'Aktif'),
(1093, 'rusia', 8, 'Brunei', 'Perdagangan', 'Aktif'),
(1094, 'rusia', 9, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1095, 'rusia', 10, 'Bahama', 'Perdagangan', 'Aktif'),
(1096, 'san_marino', 1, 'Brunei', 'Perdagangan', 'Aktif'),
(1097, 'san_marino', 2, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1098, 'san_marino', 3, 'Bermuda', 'Perdagangan', 'Aktif'),
(1099, 'san_marino', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(1100, 'san_marino', 5, 'Armenia', 'Perdagangan', 'Aktif'),
(1101, 'san_marino', 6, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1102, 'san_marino', 7, 'Bahama', 'Perdagangan', 'Aktif'),
(1103, 'siprus', 1, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1104, 'siprus', 2, 'Belize', 'Perdagangan', 'Aktif'),
(1105, 'siprus', 3, 'Bhutan', 'Perdagangan', 'Aktif'),
(1106, 'siprus', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1107, 'siprus', 5, 'Angola', 'Perdagangan', 'Aktif'),
(1108, 'siprus', 6, 'Belarus', 'Perdagangan', 'Aktif'),
(1109, 'slovenia', 1, 'Bermuda', 'Perdagangan', 'Aktif'),
(1110, 'slovenia', 2, 'Bolivia', 'Perdagangan', 'Aktif'),
(1111, 'slovenia', 3, 'Bhutan', 'Perdagangan', 'Aktif'),
(1112, 'slovenia', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1113, 'slovenia', 5, 'Belgia', 'Perdagangan', 'Aktif'),
(1114, 'slovenia', 6, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1115, 'slovenia', 7, 'Andorra', 'Perdagangan', 'Aktif'),
(1116, 'slovenia', 8, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1117, 'slovenia', 9, 'Bahama', 'Perdagangan', 'Aktif'),
(1118, 'slowakia', 1, 'Afganistan', 'Perdagangan', 'Aktif'),
(1119, 'slowakia', 2, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1120, 'slowakia', 3, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1121, 'slowakia', 4, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1122, 'slowakia', 5, 'Aljazair', 'Perdagangan', 'Aktif'),
(1123, 'slowakia', 6, 'Austria', 'Perdagangan', 'Aktif'),
(1124, 'slowakia', 7, 'Bhutan', 'Perdagangan', 'Aktif'),
(1125, 'spanyol', 1, 'Benin', 'Perdagangan', 'Aktif'),
(1126, 'spanyol', 2, 'Belgia', 'Perdagangan', 'Aktif'),
(1127, 'spanyol', 3, 'Bolivia', 'Perdagangan', 'Aktif'),
(1128, 'spanyol', 4, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1129, 'spanyol', 5, 'Australia', 'Perdagangan', 'Aktif'),
(1130, 'spanyol', 6, 'Brazil', 'Perdagangan', 'Aktif'),
(1131, 'spanyol', 7, 'Belize', 'Perdagangan', 'Aktif'),
(1132, 'spanyol', 8, 'Argentina', 'Perdagangan', 'Aktif'),
(1133, 'spanyol', 9, 'Andorra', 'Perdagangan', 'Aktif'),
(1134, 'spanyol', 10, 'Bahama', 'Perdagangan', 'Aktif'),
(1135, 'swedia', 1, 'Bolivia', 'Perdagangan', 'Aktif'),
(1136, 'swedia', 2, 'Andorra', 'Perdagangan', 'Aktif'),
(1137, 'swedia', 3, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1138, 'swedia', 4, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1139, 'swedia', 5, 'Belanda', 'Perdagangan', 'Aktif'),
(1140, 'swedia', 6, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1141, 'swedia', 7, 'Bahrain', 'Perdagangan', 'Aktif'),
(1142, 'swiss', 1, 'Belanda', 'Perdagangan', 'Aktif'),
(1143, 'swiss', 2, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1144, 'swiss', 3, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1145, 'swiss', 4, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1146, 'swiss', 5, 'Benin', 'Perdagangan', 'Aktif'),
(1147, 'swiss', 6, 'Bahama', 'Perdagangan', 'Aktif'),
(1148, 'swiss', 7, 'Brazil', 'Perdagangan', 'Aktif'),
(1149, 'swiss', 8, 'Botswana', 'Perdagangan', 'Aktif'),
(1150, 'swiss', 9, 'Australia', 'Perdagangan', 'Aktif'),
(1151, 'swiss', 10, 'Brunei', 'Perdagangan', 'Aktif'),
(1152, 'turki', 1, 'Argentina', 'Perdagangan', 'Aktif'),
(1153, 'turki', 2, 'Austria', 'Perdagangan', 'Aktif'),
(1154, 'turki', 3, 'Bahama', 'Perdagangan', 'Aktif'),
(1155, 'turki', 4, 'Albania', 'Perdagangan', 'Aktif'),
(1156, 'turki', 5, 'Belgia', 'Perdagangan', 'Aktif'),
(1157, 'turki', 6, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1158, 'turki', 7, 'Armenia', 'Perdagangan', 'Aktif'),
(1159, 'turki', 8, 'Bhutan', 'Perdagangan', 'Aktif'),
(1160, 'turki', 9, 'Benin', 'Perdagangan', 'Aktif'),
(1161, 'turki', 10, 'Angola', 'Perdagangan', 'Aktif'),
(1162, 'ukraina', 1, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1163, 'ukraina', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1164, 'ukraina', 3, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1165, 'ukraina', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(1166, 'ukraina', 5, 'Angola', 'Perdagangan', 'Aktif'),
(1167, 'ukraina', 6, 'Belgia', 'Perdagangan', 'Aktif'),
(1168, 'ukraina', 7, 'Aljazair', 'Perdagangan', 'Aktif'),
(1169, 'vatikan', 1, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1170, 'vatikan', 2, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1171, 'vatikan', 3, 'Barbados', 'Perdagangan', 'Aktif'),
(1172, 'vatikan', 4, 'Benin', 'Perdagangan', 'Aktif'),
(1173, 'vatikan', 5, 'Botswana', 'Perdagangan', 'Aktif'),
(1174, 'vatikan', 6, 'Bolivia', 'Perdagangan', 'Aktif'),
(1175, 'vatikan', 7, 'Afganistan', 'Perdagangan', 'Aktif'),
(1176, 'vatikan', 8, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1177, 'yunani', 1, 'Belgia', 'Perdagangan', 'Aktif'),
(1178, 'yunani', 2, 'Belarus', 'Perdagangan', 'Aktif'),
(1179, 'yunani', 3, 'Austria', 'Perdagangan', 'Aktif'),
(1180, 'yunani', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(1181, 'yunani', 5, 'Belanda', 'Perdagangan', 'Aktif'),
(1182, 'yunani', 6, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1183, 'yunani', 7, 'Afganistan', 'Perdagangan', 'Aktif'),
(1184, 'yunani', 8, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1185, 'yunani', 9, 'Andorra', 'Perdagangan', 'Aktif'),
(1186, 'yunani', 10, 'Angola', 'Perdagangan', 'Aktif'),
(1187, 'amerika_serikat', 1, 'Benin', 'Perdagangan', 'Aktif'),
(1188, 'amerika_serikat', 2, 'Bulgaria', 'Perdagangan', 'Aktif'),
(1189, 'amerika_serikat', 3, 'Belize', 'Perdagangan', 'Aktif'),
(1190, 'amerika_serikat', 4, 'Bahama', 'Perdagangan', 'Aktif'),
(1191, 'amerika_serikat', 5, 'Barbados', 'Perdagangan', 'Aktif'),
(1192, 'amerika_serikat', 6, 'Botswana', 'Perdagangan', 'Aktif'),
(1193, 'amerika_serikat', 7, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1194, 'amerika_serikat', 8, 'Andorra', 'Perdagangan', 'Aktif'),
(1195, 'amerika_serikat', 9, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1196, 'amerika_serikat', 10, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1197, 'antigua_dan_barbuda', 1, 'Bermuda', 'Perdagangan', 'Aktif'),
(1198, 'antigua_dan_barbuda', 2, 'Bulgaria', 'Perdagangan', 'Aktif'),
(1199, 'antigua_dan_barbuda', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(1200, 'antigua_dan_barbuda', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1201, 'antigua_dan_barbuda', 5, 'Barbados', 'Perdagangan', 'Aktif'),
(1202, 'antigua_dan_barbuda', 6, 'Botswana', 'Perdagangan', 'Aktif'),
(1203, 'antigua_dan_barbuda', 7, 'Belize', 'Perdagangan', 'Aktif'),
(1204, 'antigua_dan_barbuda', 8, 'Bhutan', 'Perdagangan', 'Aktif'),
(1205, 'bahama', 1, 'Bulgaria', 'Perdagangan', 'Aktif'),
(1206, 'bahama', 2, 'Austria', 'Perdagangan', 'Aktif'),
(1207, 'bahama', 3, 'Argentina', 'Perdagangan', 'Aktif'),
(1208, 'bahama', 4, 'Brunei', 'Perdagangan', 'Aktif'),
(1209, 'bahama', 5, 'Australia', 'Perdagangan', 'Aktif'),
(1210, 'bahama', 6, 'Bolivia', 'Perdagangan', 'Aktif'),
(1211, 'barbados', 1, 'Armenia', 'Perdagangan', 'Aktif'),
(1212, 'barbados', 2, 'Bolivia', 'Perdagangan', 'Aktif'),
(1213, 'barbados', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(1214, 'barbados', 4, 'Belize', 'Perdagangan', 'Aktif'),
(1215, 'barbados', 5, 'Benin', 'Perdagangan', 'Aktif'),
(1216, 'barbados', 6, 'Austria', 'Perdagangan', 'Aktif'),
(1217, 'barbados', 7, 'Argentina', 'Perdagangan', 'Aktif'),
(1218, 'barbados', 8, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1219, 'barbados', 9, 'Bahama', 'Perdagangan', 'Aktif'),
(1220, 'barbados', 10, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1221, 'belize', 1, 'Afganistan', 'Perdagangan', 'Aktif'),
(1222, 'belize', 2, 'Benin', 'Perdagangan', 'Aktif'),
(1223, 'belize', 3, 'Brunei', 'Perdagangan', 'Aktif'),
(1224, 'belize', 4, 'Belgia', 'Perdagangan', 'Aktif'),
(1225, 'belize', 5, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1226, 'belize', 6, 'Argentina', 'Perdagangan', 'Aktif'),
(1227, 'belize', 7, 'Angola', 'Perdagangan', 'Aktif'),
(1228, 'bermuda', 1, 'Bahama', 'Perdagangan', 'Aktif'),
(1229, 'bermuda', 2, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1230, 'bermuda', 3, 'Aljazair', 'Perdagangan', 'Aktif'),
(1231, 'bermuda', 4, 'Albania', 'Perdagangan', 'Aktif'),
(1232, 'bermuda', 5, 'Brunei', 'Perdagangan', 'Aktif'),
(1233, 'bermuda', 6, 'Brazil', 'Perdagangan', 'Aktif'),
(1234, 'bermuda', 7, 'Argentina', 'Perdagangan', 'Aktif'),
(1235, 'bermuda', 8, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1236, 'bermuda', 9, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1237, 'bermuda', 10, 'Barbados', 'Perdagangan', 'Aktif'),
(1238, 'costa_rica', 1, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1239, 'costa_rica', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1240, 'costa_rica', 3, 'Bermuda', 'Perdagangan', 'Aktif'),
(1241, 'costa_rica', 4, 'Bhutan', 'Perdagangan', 'Aktif'),
(1242, 'costa_rica', 5, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1243, 'costa_rica', 6, 'Armenia', 'Perdagangan', 'Aktif'),
(1244, 'costa_rica', 7, 'Bahrain', 'Perdagangan', 'Aktif'),
(1245, 'curacao', 1, 'Belgia', 'Perdagangan', 'Aktif'),
(1246, 'curacao', 2, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1247, 'curacao', 3, 'Argentina', 'Perdagangan', 'Aktif'),
(1248, 'curacao', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1249, 'curacao', 5, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1250, 'curacao', 6, 'Bolivia', 'Perdagangan', 'Aktif'),
(1251, 'dominika', 1, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1252, 'dominika', 2, 'Australia', 'Perdagangan', 'Aktif'),
(1253, 'dominika', 3, 'Brunei', 'Perdagangan', 'Aktif'),
(1254, 'dominika', 4, 'Argentina', 'Perdagangan', 'Aktif'),
(1255, 'dominika', 5, 'Andorra', 'Perdagangan', 'Aktif'),
(1256, 'dominika', 6, 'Bahrain', 'Perdagangan', 'Aktif'),
(1257, 'dominika', 7, 'Belize', 'Perdagangan', 'Aktif'),
(1258, 'el_salvador', 1, 'Benin', 'Perdagangan', 'Aktif'),
(1259, 'el_salvador', 2, 'Afganistan', 'Perdagangan', 'Aktif'),
(1260, 'el_salvador', 3, 'Belarus', 'Perdagangan', 'Aktif'),
(1261, 'el_salvador', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(1262, 'el_salvador', 5, 'Albania', 'Perdagangan', 'Aktif'),
(1263, 'el_salvador', 6, 'Austria', 'Perdagangan', 'Aktif'),
(1264, 'el_salvador', 7, 'Angola', 'Perdagangan', 'Aktif'),
(1265, 'el_salvador', 8, 'Botswana', 'Perdagangan', 'Aktif'),
(1266, 'greenland', 1, 'Bhutan', 'Perdagangan', 'Aktif'),
(1267, 'greenland', 2, 'Botswana', 'Perdagangan', 'Aktif'),
(1268, 'greenland', 3, 'Belanda', 'Perdagangan', 'Aktif'),
(1269, 'greenland', 4, 'Afganistan', 'Perdagangan', 'Aktif'),
(1270, 'greenland', 5, 'Bermuda', 'Perdagangan', 'Aktif'),
(1271, 'greenland', 6, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1272, 'greenland', 7, 'Angola', 'Perdagangan', 'Aktif'),
(1273, 'greenland', 8, 'Belarus', 'Perdagangan', 'Aktif'),
(1274, 'greenland', 9, 'Benin', 'Perdagangan', 'Aktif'),
(1275, 'greenland', 10, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1276, 'grenada', 1, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1277, 'grenada', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1278, 'grenada', 3, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1279, 'grenada', 4, 'Bermuda', 'Perdagangan', 'Aktif'),
(1280, 'grenada', 5, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1281, 'grenada', 6, 'Argentina', 'Perdagangan', 'Aktif'),
(1282, 'grenada', 7, 'Bhutan', 'Perdagangan', 'Aktif'),
(1283, 'grenada', 8, 'Brunei', 'Perdagangan', 'Aktif'),
(1284, 'grenada', 9, 'Austria', 'Perdagangan', 'Aktif'),
(1285, 'guatemala', 1, 'Andorra', 'Perdagangan', 'Aktif'),
(1286, 'guatemala', 2, 'Belize', 'Perdagangan', 'Aktif'),
(1287, 'guatemala', 3, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1288, 'guatemala', 4, 'Bermuda', 'Perdagangan', 'Aktif'),
(1289, 'guatemala', 5, 'Argentina', 'Perdagangan', 'Aktif'),
(1290, 'guatemala', 6, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1291, 'guatemala', 7, 'Austria', 'Perdagangan', 'Aktif'),
(1292, 'haiti', 1, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1293, 'haiti', 2, 'Botswana', 'Perdagangan', 'Aktif'),
(1294, 'haiti', 3, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1295, 'haiti', 4, 'Benin', 'Perdagangan', 'Aktif'),
(1296, 'haiti', 5, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1297, 'haiti', 6, 'Belize', 'Perdagangan', 'Aktif'),
(1298, 'honduras', 1, 'Botswana', 'Perdagangan', 'Aktif'),
(1299, 'honduras', 2, 'Brazil', 'Perdagangan', 'Aktif'),
(1300, 'honduras', 3, 'Armenia', 'Perdagangan', 'Aktif'),
(1301, 'honduras', 4, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1302, 'honduras', 5, 'Belize', 'Perdagangan', 'Aktif'),
(1303, 'honduras', 6, 'Benin', 'Perdagangan', 'Aktif'),
(1304, 'honduras', 7, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1305, 'jamaika', 1, 'Albania', 'Perdagangan', 'Aktif'),
(1306, 'jamaika', 2, 'Barbados', 'Perdagangan', 'Aktif'),
(1307, 'jamaika', 3, 'Bermuda', 'Perdagangan', 'Aktif'),
(1308, 'jamaika', 4, 'Bolivia', 'Perdagangan', 'Aktif'),
(1309, 'jamaika', 5, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1310, 'jamaika', 6, 'Belize', 'Perdagangan', 'Aktif'),
(1311, 'jamaika', 7, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1312, 'jamaika', 8, 'Australia', 'Perdagangan', 'Aktif'),
(1313, 'kanada', 1, 'Aljazair', 'Perdagangan', 'Aktif'),
(1314, 'kanada', 2, 'Bolivia', 'Perdagangan', 'Aktif'),
(1315, 'kanada', 3, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1316, 'kanada', 4, 'Bermuda', 'Perdagangan', 'Aktif'),
(1317, 'kanada', 5, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1318, 'kanada', 6, 'Belgia', 'Perdagangan', 'Aktif'),
(1319, 'kuba', 1, 'Australia', 'Perdagangan', 'Aktif'),
(1320, 'kuba', 2, 'Austria', 'Perdagangan', 'Aktif'),
(1321, 'kuba', 3, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1322, 'kuba', 4, 'Botswana', 'Perdagangan', 'Aktif'),
(1323, 'kuba', 5, 'Belize', 'Perdagangan', 'Aktif'),
(1324, 'kuba', 6, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1325, 'kuba', 7, 'Bermuda', 'Perdagangan', 'Aktif'),
(1326, 'kuba', 8, 'Brunei', 'Perdagangan', 'Aktif'),
(1327, 'meksiko', 1, 'Belarus', 'Perdagangan', 'Aktif'),
(1328, 'meksiko', 2, 'Bahrain', 'Perdagangan', 'Aktif'),
(1329, 'meksiko', 3, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1330, 'meksiko', 4, 'Brazil', 'Perdagangan', 'Aktif'),
(1331, 'meksiko', 5, 'Barbados', 'Perdagangan', 'Aktif'),
(1332, 'meksiko', 6, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1333, 'meksiko', 7, 'Aljazair', 'Perdagangan', 'Aktif'),
(1334, 'meksiko', 8, 'Botswana', 'Perdagangan', 'Aktif'),
(1335, 'nikaragua', 1, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1336, 'nikaragua', 2, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1337, 'nikaragua', 3, 'Bolivia', 'Perdagangan', 'Aktif'),
(1338, 'nikaragua', 4, 'Aljazair', 'Perdagangan', 'Aktif'),
(1339, 'nikaragua', 5, 'Belanda', 'Perdagangan', 'Aktif'),
(1340, 'nikaragua', 6, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1341, 'panama', 1, 'Afganistan', 'Perdagangan', 'Aktif'),
(1342, 'panama', 2, 'Albania', 'Perdagangan', 'Aktif'),
(1343, 'panama', 3, 'Austria', 'Perdagangan', 'Aktif'),
(1344, 'panama', 4, 'Argentina', 'Perdagangan', 'Aktif'),
(1345, 'panama', 5, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1346, 'panama', 6, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1347, 'panama', 7, 'Angola', 'Perdagangan', 'Aktif'),
(1348, 'panama', 8, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1349, 'puerto_rico', 1, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1350, 'puerto_rico', 2, 'Bahrain', 'Perdagangan', 'Aktif'),
(1351, 'puerto_rico', 3, 'Aljazair', 'Perdagangan', 'Aktif'),
(1352, 'puerto_rico', 4, 'Angola', 'Perdagangan', 'Aktif'),
(1353, 'puerto_rico', 5, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1354, 'puerto_rico', 6, 'Bhutan', 'Perdagangan', 'Aktif'),
(1355, 'puerto_rico', 7, 'Belarus', 'Perdagangan', 'Aktif'),
(1356, 'puerto_rico', 8, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1357, 'republik_dominika', 1, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1358, 'republik_dominika', 2, 'Afganistan', 'Perdagangan', 'Aktif'),
(1359, 'republik_dominika', 3, 'Argentina', 'Perdagangan', 'Aktif'),
(1360, 'republik_dominika', 4, 'Botswana', 'Perdagangan', 'Aktif'),
(1361, 'republik_dominika', 5, 'Brunei', 'Perdagangan', 'Aktif'),
(1362, 'republik_dominika', 6, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1363, 'republik_dominika', 7, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1364, 'republik_dominika', 8, 'Benin', 'Perdagangan', 'Aktif'),
(1365, 'republik_dominika', 9, 'Andorra', 'Perdagangan', 'Aktif'),
(1366, 'saint_kitts_dan_nevis', 1, 'Belize', 'Perdagangan', 'Aktif'),
(1367, 'saint_kitts_dan_nevis', 2, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1368, 'saint_kitts_dan_nevis', 3, 'Brunei', 'Perdagangan', 'Aktif'),
(1369, 'saint_kitts_dan_nevis', 4, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1370, 'saint_kitts_dan_nevis', 5, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1371, 'saint_kitts_dan_nevis', 6, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1372, 'saint_kitts_dan_nevis', 7, 'Belanda', 'Perdagangan', 'Aktif'),
(1373, 'saint_kitts_dan_nevis', 8, 'Belgia', 'Perdagangan', 'Aktif'),
(1374, 'saint_lucia', 1, 'Austria', 'Perdagangan', 'Aktif'),
(1375, 'saint_lucia', 2, 'Bahama', 'Perdagangan', 'Aktif'),
(1376, 'saint_lucia', 3, 'Australia', 'Perdagangan', 'Aktif'),
(1377, 'saint_lucia', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1378, 'saint_lucia', 5, 'Bermuda', 'Perdagangan', 'Aktif'),
(1379, 'saint_lucia', 6, 'Belize', 'Perdagangan', 'Aktif'),
(1380, 'saint_vincent_dan_grenadine', 1, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1381, 'saint_vincent_dan_grenadine', 2, 'Bermuda', 'Perdagangan', 'Aktif'),
(1382, 'saint_vincent_dan_grenadine', 3, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1383, 'saint_vincent_dan_grenadine', 4, 'Albania', 'Perdagangan', 'Aktif'),
(1384, 'saint_vincent_dan_grenadine', 5, 'Belgia', 'Perdagangan', 'Aktif'),
(1385, 'saint_vincent_dan_grenadine', 6, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1386, 'trinidad_dan_tobago', 1, 'Belanda', 'Perdagangan', 'Aktif'),
(1387, 'trinidad_dan_tobago', 2, 'Aljazair', 'Perdagangan', 'Aktif'),
(1388, 'trinidad_dan_tobago', 3, 'Bahama', 'Perdagangan', 'Aktif'),
(1389, 'trinidad_dan_tobago', 4, 'Belize', 'Perdagangan', 'Aktif'),
(1390, 'trinidad_dan_tobago', 5, 'Bahrain', 'Perdagangan', 'Aktif'),
(1391, 'trinidad_dan_tobago', 6, 'Barbados', 'Perdagangan', 'Aktif'),
(1392, 'trinidad_dan_tobago', 7, 'Argentina', 'Perdagangan', 'Aktif'),
(1393, 'trinidad_dan_tobago', 8, 'Belarus', 'Perdagangan', 'Aktif'),
(1394, 'australia', 1, 'Bahrain', 'Perdagangan', 'Aktif'),
(1395, 'australia', 2, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1396, 'australia', 3, 'Bahama', 'Perdagangan', 'Aktif'),
(1397, 'australia', 4, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1398, 'australia', 5, 'Benin', 'Perdagangan', 'Aktif'),
(1399, 'australia', 6, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1400, 'fiji', 1, 'Austria', 'Perdagangan', 'Aktif'),
(1401, 'fiji', 2, 'Brazil', 'Perdagangan', 'Aktif'),
(1402, 'fiji', 3, 'Albania', 'Perdagangan', 'Aktif'),
(1403, 'fiji', 4, 'Bermuda', 'Perdagangan', 'Aktif'),
(1404, 'fiji', 5, 'Bolivia', 'Perdagangan', 'Aktif'),
(1405, 'fiji', 6, 'Barbados', 'Perdagangan', 'Aktif'),
(1406, 'fiji', 7, 'Argentina', 'Perdagangan', 'Aktif'),
(1407, 'guam', 1, 'Belarus', 'Perdagangan', 'Aktif'),
(1408, 'guam', 2, 'Austria', 'Perdagangan', 'Aktif'),
(1409, 'guam', 3, 'Argentina', 'Perdagangan', 'Aktif'),
(1410, 'guam', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(1411, 'guam', 5, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1412, 'guam', 6, 'Andorra', 'Perdagangan', 'Aktif'),
(1413, 'kiribati', 1, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1414, 'kiribati', 2, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1415, 'kiribati', 3, 'Belgia', 'Perdagangan', 'Aktif'),
(1416, 'kiribati', 4, 'Armenia', 'Perdagangan', 'Aktif'),
(1417, 'kiribati', 5, 'Andorra', 'Perdagangan', 'Aktif'),
(1418, 'kiribati', 6, 'Albania', 'Perdagangan', 'Aktif'),
(1419, 'kiribati', 7, 'Brunei', 'Perdagangan', 'Aktif'),
(1420, 'kiribati', 8, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1421, 'kiribati', 9, 'Bermuda', 'Perdagangan', 'Aktif'),
(1422, 'marshall', 1, 'Botswana', 'Perdagangan', 'Aktif'),
(1423, 'marshall', 2, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1424, 'marshall', 3, 'Barbados', 'Perdagangan', 'Aktif'),
(1425, 'marshall', 4, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1426, 'marshall', 5, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1427, 'marshall', 6, 'Belanda', 'Perdagangan', 'Aktif'),
(1428, 'marshall', 7, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1429, 'marshall', 8, 'Bermuda', 'Perdagangan', 'Aktif'),
(1430, 'marshall', 9, 'Benin', 'Perdagangan', 'Aktif'),
(1431, 'mikronesia', 1, 'Brunei', 'Perdagangan', 'Aktif'),
(1432, 'mikronesia', 2, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1433, 'mikronesia', 3, 'Armenia', 'Perdagangan', 'Aktif'),
(1434, 'mikronesia', 4, 'Australia', 'Perdagangan', 'Aktif'),
(1435, 'mikronesia', 5, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1436, 'mikronesia', 6, 'Belarus', 'Perdagangan', 'Aktif'),
(1437, 'mikronesia', 7, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1438, 'nauru', 1, 'Barbados', 'Perdagangan', 'Aktif'),
(1439, 'nauru', 2, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1440, 'nauru', 3, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1441, 'nauru', 4, 'Afganistan', 'Perdagangan', 'Aktif'),
(1442, 'nauru', 5, 'Andorra', 'Perdagangan', 'Aktif'),
(1443, 'nauru', 6, 'Austria', 'Perdagangan', 'Aktif'),
(1444, 'palau', 1, 'Botswana', 'Perdagangan', 'Aktif'),
(1445, 'palau', 2, 'Armenia', 'Perdagangan', 'Aktif'),
(1446, 'palau', 3, 'Belarus', 'Perdagangan', 'Aktif'),
(1447, 'palau', 4, 'Belgia', 'Perdagangan', 'Aktif'),
(1448, 'palau', 5, 'Aljazair', 'Perdagangan', 'Aktif'),
(1449, 'palau', 6, 'Bermuda', 'Perdagangan', 'Aktif'),
(1450, 'palau', 7, 'Benin', 'Perdagangan', 'Aktif'),
(1451, 'palau', 8, 'Barbados', 'Perdagangan', 'Aktif'),
(1452, 'palau', 9, 'Bolivia', 'Perdagangan', 'Aktif'),
(1453, 'palau', 10, 'Bhutan', 'Perdagangan', 'Aktif'),
(1454, 'papua_nugini', 1, 'Brunei', 'Perdagangan', 'Aktif'),
(1455, 'papua_nugini', 2, 'Bolivia', 'Perdagangan', 'Aktif'),
(1456, 'papua_nugini', 3, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1457, 'papua_nugini', 4, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1458, 'papua_nugini', 5, 'Andorra', 'Perdagangan', 'Aktif'),
(1459, 'papua_nugini', 6, 'Brazil', 'Perdagangan', 'Aktif'),
(1460, 'samoa', 1, 'Belize', 'Perdagangan', 'Aktif'),
(1461, 'samoa', 2, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1462, 'samoa', 3, 'Brunei', 'Perdagangan', 'Aktif'),
(1463, 'samoa', 4, 'Belarus', 'Perdagangan', 'Aktif'),
(1464, 'samoa', 5, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1465, 'samoa', 6, 'Benin', 'Perdagangan', 'Aktif'),
(1466, 'samoa', 7, 'Botswana', 'Perdagangan', 'Aktif'),
(1467, 'samoa', 8, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1468, 'samoa_amerika', 1, 'Armenia', 'Perdagangan', 'Aktif'),
(1469, 'samoa_amerika', 2, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1470, 'samoa_amerika', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(1471, 'samoa_amerika', 4, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1472, 'samoa_amerika', 5, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1473, 'samoa_amerika', 6, 'Bhutan', 'Perdagangan', 'Aktif'),
(1474, 'samoa_amerika', 7, 'Bermuda', 'Perdagangan', 'Aktif'),
(1475, 'selandia_baru', 1, 'Armenia', 'Perdagangan', 'Aktif'),
(1476, 'selandia_baru', 2, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1477, 'selandia_baru', 3, 'Australia', 'Perdagangan', 'Aktif'),
(1478, 'selandia_baru', 4, 'Belarus', 'Perdagangan', 'Aktif'),
(1479, 'selandia_baru', 5, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1480, 'selandia_baru', 6, 'Belgia', 'Perdagangan', 'Aktif'),
(1481, 'selandia_baru', 7, 'Bolivia', 'Perdagangan', 'Aktif'),
(1482, 'tahiti', 1, 'Belarus', 'Perdagangan', 'Aktif'),
(1483, 'tahiti', 2, 'Angola', 'Perdagangan', 'Aktif'),
(1484, 'tahiti', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(1485, 'tahiti', 4, 'Bermuda', 'Perdagangan', 'Aktif'),
(1486, 'tahiti', 5, 'Benin', 'Perdagangan', 'Aktif'),
(1487, 'tahiti', 6, 'Bolivia', 'Perdagangan', 'Aktif'),
(1488, 'tonga', 1, 'Bahrain', 'Perdagangan', 'Aktif'),
(1489, 'tonga', 2, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1490, 'tonga', 3, 'Bolivia', 'Perdagangan', 'Aktif'),
(1491, 'tonga', 4, 'Angola', 'Perdagangan', 'Aktif'),
(1492, 'tonga', 5, 'Barbados', 'Perdagangan', 'Aktif'),
(1493, 'tonga', 6, 'Benin', 'Perdagangan', 'Aktif'),
(1494, 'tonga', 7, 'Andorra', 'Perdagangan', 'Aktif'),
(1495, 'tonga', 8, 'Bahama', 'Perdagangan', 'Aktif'),
(1496, 'tonga', 9, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1497, 'tonga', 10, 'Brunei', 'Perdagangan', 'Aktif'),
(1498, 'tuvalu', 1, 'Belarus', 'Perdagangan', 'Aktif'),
(1499, 'tuvalu', 2, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1500, 'tuvalu', 3, 'Andorra', 'Perdagangan', 'Aktif');

INSERT INTO database_mitra_perdagangan (
    country_id, country_slug, mitra_no, mitra_country, trade_type, status
) VALUES
(1501, 'tuvalu', 4, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1502, 'tuvalu', 5, 'Belgia', 'Perdagangan', 'Aktif'),
(1503, 'tuvalu', 6, 'Brunei', 'Perdagangan', 'Aktif'),
(1504, 'tuvalu', 7, 'Australia', 'Perdagangan', 'Aktif'),
(1505, 'tuvalu', 8, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1506, 'vanuatu', 1, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1507, 'vanuatu', 2, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1508, 'vanuatu', 3, 'Benin', 'Perdagangan', 'Aktif'),
(1509, 'vanuatu', 4, 'Belgia', 'Perdagangan', 'Aktif'),
(1510, 'vanuatu', 5, 'Belarus', 'Perdagangan', 'Aktif'),
(1511, 'vanuatu', 6, 'Belize', 'Perdagangan', 'Aktif'),
(1512, 'vanuatu', 7, 'Brunei', 'Perdagangan', 'Aktif'),
(1513, 'vanuatu', 8, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1514, 'argentina', 1, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1515, 'argentina', 2, 'Belgia', 'Perdagangan', 'Aktif'),
(1516, 'argentina', 3, 'Brunei', 'Perdagangan', 'Aktif'),
(1517, 'argentina', 4, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1518, 'argentina', 5, 'Bulgaria', 'Perdagangan', 'Aktif'),
(1519, 'argentina', 6, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1520, 'bolivia', 1, 'Benin', 'Perdagangan', 'Aktif'),
(1521, 'bolivia', 2, 'Bahrain', 'Perdagangan', 'Aktif'),
(1522, 'bolivia', 3, 'Botswana', 'Perdagangan', 'Aktif'),
(1523, 'bolivia', 4, 'Barbados', 'Perdagangan', 'Aktif'),
(1524, 'bolivia', 5, 'Bulgaria', 'Perdagangan', 'Aktif'),
(1525, 'bolivia', 6, 'Belize', 'Perdagangan', 'Aktif'),
(1526, 'brazil', 1, 'Afganistan', 'Perdagangan', 'Aktif'),
(1527, 'brazil', 2, 'Botswana', 'Perdagangan', 'Aktif'),
(1528, 'brazil', 3, 'Bahrain', 'Perdagangan', 'Aktif'),
(1529, 'brazil', 4, 'Bermuda', 'Perdagangan', 'Aktif'),
(1530, 'brazil', 5, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1531, 'brazil', 6, 'Australia', 'Perdagangan', 'Aktif'),
(1532, 'chile', 1, 'Bolivia', 'Perdagangan', 'Aktif'),
(1533, 'chile', 2, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1534, 'chile', 3, 'Albania', 'Perdagangan', 'Aktif'),
(1535, 'chile', 4, 'Belize', 'Perdagangan', 'Aktif'),
(1536, 'chile', 5, 'Botswana', 'Perdagangan', 'Aktif'),
(1537, 'chile', 6, 'Bhutan', 'Perdagangan', 'Aktif'),
(1538, 'chile', 7, 'Brunei', 'Perdagangan', 'Aktif'),
(1539, 'chile', 8, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1540, 'ekuador', 1, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1541, 'ekuador', 2, 'Belize', 'Perdagangan', 'Aktif'),
(1542, 'ekuador', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(1543, 'ekuador', 4, 'Andorra', 'Perdagangan', 'Aktif'),
(1544, 'ekuador', 5, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1545, 'ekuador', 6, 'Argentina', 'Perdagangan', 'Aktif'),
(1546, 'ekuador', 7, 'Belgia', 'Perdagangan', 'Aktif'),
(1547, 'ekuador', 8, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1548, 'guiana_prancis', 1, 'Aljazair', 'Perdagangan', 'Aktif'),
(1549, 'guiana_prancis', 2, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1550, 'guiana_prancis', 3, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1551, 'guiana_prancis', 4, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1552, 'guiana_prancis', 5, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1553, 'guiana_prancis', 6, 'Belgia', 'Perdagangan', 'Aktif'),
(1554, 'guiana_prancis', 7, 'Bahama', 'Perdagangan', 'Aktif'),
(1555, 'guiana_prancis', 8, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1556, 'guiana_prancis', 9, 'Belize', 'Perdagangan', 'Aktif'),
(1557, 'guyana', 1, 'Bahama', 'Perdagangan', 'Aktif'),
(1558, 'guyana', 2, 'Bermuda', 'Perdagangan', 'Aktif'),
(1559, 'guyana', 3, 'Austria', 'Perdagangan', 'Aktif'),
(1560, 'guyana', 4, 'Belanda', 'Perdagangan', 'Aktif'),
(1561, 'guyana', 5, 'Bosnia dan Hercegovina', 'Perdagangan', 'Aktif'),
(1562, 'guyana', 6, 'Belize', 'Perdagangan', 'Aktif'),
(1563, 'guyana', 7, 'Brunei', 'Perdagangan', 'Aktif'),
(1564, 'kolombia', 1, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1565, 'kolombia', 2, 'Afganistan', 'Perdagangan', 'Aktif'),
(1566, 'kolombia', 3, 'Austria', 'Perdagangan', 'Aktif'),
(1567, 'kolombia', 4, 'Andorra', 'Perdagangan', 'Aktif'),
(1568, 'kolombia', 5, 'Brunei', 'Perdagangan', 'Aktif'),
(1569, 'kolombia', 6, 'Belarus', 'Perdagangan', 'Aktif'),
(1570, 'paraguay', 1, 'Bermuda', 'Perdagangan', 'Aktif'),
(1571, 'paraguay', 2, 'Belize', 'Perdagangan', 'Aktif'),
(1572, 'paraguay', 3, 'Bangladesh', 'Perdagangan', 'Aktif'),
(1573, 'paraguay', 4, 'Armenia', 'Perdagangan', 'Aktif'),
(1574, 'paraguay', 5, 'Australia', 'Perdagangan', 'Aktif'),
(1575, 'paraguay', 6, 'Bahama', 'Perdagangan', 'Aktif'),
(1576, 'paraguay', 7, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1577, 'paraguay', 8, 'Argentina', 'Perdagangan', 'Aktif'),
(1578, 'paraguay', 9, 'Benin', 'Perdagangan', 'Aktif'),
(1579, 'paraguay', 10, 'Angola', 'Perdagangan', 'Aktif'),
(1580, 'peru', 1, 'Arab Saudi', 'Perdagangan', 'Aktif'),
(1581, 'peru', 2, 'Bahrain', 'Perdagangan', 'Aktif'),
(1582, 'peru', 3, 'Belanda', 'Perdagangan', 'Aktif'),
(1583, 'peru', 4, 'Austria', 'Perdagangan', 'Aktif'),
(1584, 'peru', 5, 'Angola', 'Perdagangan', 'Aktif'),
(1585, 'peru', 6, 'Aljazair', 'Perdagangan', 'Aktif'),
(1586, 'suriname', 1, 'Amerika Serikat', 'Perdagangan', 'Aktif'),
(1587, 'suriname', 2, 'Botswana', 'Perdagangan', 'Aktif'),
(1588, 'suriname', 3, 'Barbados', 'Perdagangan', 'Aktif'),
(1589, 'suriname', 4, 'Belarus', 'Perdagangan', 'Aktif'),
(1590, 'suriname', 5, 'Brazil', 'Perdagangan', 'Aktif'),
(1591, 'suriname', 6, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1592, 'suriname', 7, 'Bhutan', 'Perdagangan', 'Aktif'),
(1593, 'suriname', 8, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1594, 'uruguay', 1, 'Antigua dan Barbuda', 'Perdagangan', 'Aktif'),
(1595, 'uruguay', 2, 'Belanda', 'Perdagangan', 'Aktif'),
(1596, 'uruguay', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(1597, 'uruguay', 4, 'Afganistan', 'Perdagangan', 'Aktif'),
(1598, 'uruguay', 5, 'Benin', 'Perdagangan', 'Aktif'),
(1599, 'uruguay', 6, 'Australia', 'Perdagangan', 'Aktif'),
(1600, 'uruguay', 7, 'Bermuda', 'Perdagangan', 'Aktif'),
(1601, 'uruguay', 8, 'Bahama', 'Perdagangan', 'Aktif'),
(1602, 'uruguay', 9, 'Belize', 'Perdagangan', 'Aktif'),
(1603, 'venezuela', 1, 'Belgia', 'Perdagangan', 'Aktif'),
(1604, 'venezuela', 2, 'Afrika Selatan', 'Perdagangan', 'Aktif'),
(1605, 'venezuela', 3, 'Brazil', 'Perdagangan', 'Aktif'),
(1606, 'venezuela', 4, 'Belarus', 'Perdagangan', 'Aktif'),
(1607, 'venezuela', 5, 'Azerbaijan', 'Perdagangan', 'Aktif'),
(1608, 'venezuela', 6, 'Angola', 'Perdagangan', 'Aktif'),
(1609, 'venezuela', 7, 'Belanda', 'Perdagangan', 'Aktif'),
(1610, 'venezuela', 8, 'Albania', 'Perdagangan', 'Aktif');

