DROP TABLE IF EXISTS database_sistem_ekonomi;
CREATE TABLE database_sistem_ekonomi (
id SERIAL NOT NULL PRIMARY KEY,
country_id INT NOT NULL,
country_slug VARCHAR(100) NOT NULL,
country_name VARCHAR(100) NOT NULL,
iso VARCHAR(10) NOT NULL,
spektrum_val INT NOT NULL DEFAULT 50, -- 0 (Terpusat/Komando) - 100 (Pasar Bebas/Laissez-Faire)
system_title VARCHAR(100) NOT NULL,
category VARCHAR(255) NOT NULL,
policy_price_control VARCHAR(255) NOT NULL DEFAULT 'Terpusat',
policy_strategic_ownership VARCHAR(255) NOT NULL DEFAULT 'Terpusat',
policy_trade VARCHAR(255) NOT NULL DEFAULT 'Pasar Bebas',
policy_labor VARCHAR(255) NOT NULL DEFAULT 'Pasar Bebas'
);
INSERT INTO database_sistem_ekonomi
(country_id, country_slug, country_name, iso, spektrum_val, system_title, category, policy_price_control, policy_strategic_ownership, policy_trade, policy_labor)
VALUES
(21869, 'afganistan', 'Afganistan', 'af', 15, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(29240, 'afrika_selatan', 'Afrika Selatan', 'za', 65, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(93002, 'albania', 'Albania', 'al', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20793, 'aljazair', 'Aljazair', 'dz', 25, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20257, 'amerika_serikat', 'Amerika Serikat', 'us', 88, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(34293, 'andorra', 'Andorra', 'ad', 72, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20427, 'angola', 'Angola', 'ao', 30, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas'),
(10222, 'antigua_dan_barbuda', 'Antigua dan Barbuda', 'ag', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21021, 'arab_saudi', 'Arab Saudi', 'sa', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20367, 'argentina', 'Argentina', 'ar', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20977, 'armenia', 'Armenia', 'am', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20448, 'australia', 'Australia', 'au', 82, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20456, 'austria', 'Austria', 'at', 55, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20835, 'azerbaijan', 'Azerbaijan', 'az', 35, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21714, 'bahama', 'Bahama', 'bs', 75, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20836, 'bahrain', 'Bahrain', 'bh', 68, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20465, 'bangladesh', 'Bangladesh', 'bd', 45, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20469, 'barbados', 'Barbados', 'bb', 60, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20474, 'belanda', 'Belanda', 'nl', 70, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20478, 'belarus', 'Belarus', 'by', 18, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20482, 'belgia', 'Belgia', 'be', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20486, 'belize', 'Belize', 'bz', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20490, 'benin', 'Benin', 'bj', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20494, 'bhutan', 'Bhutan', 'bt', 40, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20500, 'bolivia', 'Bolivia', 'bo', 28, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20510, 'botswana', 'Botswana', 'bw', 66, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20515, 'brazil', 'Brazil', 'br', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20520, 'brunei', 'Brunei', 'bn', 32, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20525, 'bulgaria', 'Bulgaria', 'bg', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20530, 'burkina_faso', 'Burkina faso', 'bf', 36, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20535, 'burundi', 'Burundi', 'bi', 22, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20545, 'chile', 'Chile', 'cl', 78, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20550, 'china', 'China', 'cn', 25, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20560, 'denmark', 'Denmark', 'dk', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20565, 'djibouti', 'Djibouti', 'dj', 44, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20570, 'dominika', 'Dominika', 'dm', 54, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20575, 'ekuador', 'Ekuador', 'ec', 46, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20580, 'el_salvador', 'El salvador', 'sv', 68, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20585, 'eritrea', 'Eritrea', 'er', 12, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20590, 'estonia', 'Estonia', 'ee', 80, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20595, 'eswatini', 'Eswatini', 'sz', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20600, 'ethiopia', 'Ethiopia', 'et', 26, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20605, 'fiji', 'Fiji', 'fj', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20610, 'filipina', 'Filipina', 'ph', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20615, 'finlandia', 'Finlandia', 'fi', 60, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20620, 'gabon', 'Gabon', 'ga', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20625, 'gambia', 'Gambia', 'gm', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20630, 'georgia', 'Georgia', 'ge', 76, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20635, 'ghana', 'Ghana', 'gh', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20640, 'grenada', 'Grenada', 'gd', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20645, 'guatemala', 'Guatemala', 'gt', 66, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20650, 'guinea', 'Guinea', 'gn', 34, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20655, 'guinea_bissau', 'Guinea bissau', 'gw', 30, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20665, 'guyana', 'Guyana', 'gy', 46, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20670, 'haiti', 'Haiti', 'ht', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20675, 'honduras', 'Honduras', 'hn', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20680, 'hungaria', 'Hungaria', 'hu', 54, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20685, 'india', 'India', 'in', 50, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20690, 'indonesia', 'Indonesia', 'id', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20695, 'inggris', 'Inggris', 'gb', 76, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20700, 'iran', 'Iran', 'ir', 20, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20705, 'irak', 'Irak', 'iq', 28, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20710, 'irlandia', 'Irlandia', 'ie', 84, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20715, 'israel', 'Israel', 'il', 72, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20720, 'italia', 'Italia', 'it', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20725, 'jamaika', 'Jamaika', 'jm', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20730, 'jepang', 'Jepang', 'jp', 68, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20735, 'jerman', 'Jerman', 'de', 65, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20740, 'kamboja', 'Kamboja', 'kh', 44, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20745, 'kamerun', 'Kamerun', 'cm', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20750, 'kanada', 'Kanada', 'ca', 74, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20755, 'kazakhstan', 'Kazakhstan', 'kz', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20760, 'kenya', 'Kenya', 'ke', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20765, 'kirgizstan', 'Kirgizstan', 'kg', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20770, 'kiribati', 'Kiribati', 'ki', 36, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20775, 'kolombia', 'Kolombia', 'co', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20780, 'komoro', 'Komoro', 'km', 40, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20785, 'korea_selatan', 'Korea Selatan', 'kr', 78, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20790, 'korea_utara', 'Korea Utara', 'kp', 5, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20800, 'kroasia', 'Kroasia', 'hr', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20805, 'kuba', 'Kuba', 'cu', 14, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20810, 'kuwait', 'Kuwait', 'kw', 45, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20815, 'laos', 'Laos', 'la', 28, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20820, 'latvia', 'Latvia', 'lv', 72, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20825, 'lebanon', 'Lebanon', 'lb', 60, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20830, 'lesotho', 'Lesotho', 'ls', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20840, 'liberia', 'Liberia', 'lr', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20845, 'libya', 'Libya', 'ly', 22, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20850, 'liechtenstein', 'Liechtenstein', 'li', 90, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20860, 'luksemburg', 'Luksemburg', 'lu', 82, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20865, 'madagaskar', 'Madagaskar', 'mg', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20870, 'makau', 'Makau', 'mo', 85, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20875, 'makedonia_utara', 'Makedonia utara', 'mk', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20880, 'malawi', 'Malawi', 'mw', 36, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20885, 'malaysia', 'Malaysia', 'my', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20895, 'mali', 'Mali', 'ml', 32, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20900, 'malta', 'Malta', 'mt', 72, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20905, 'maroko', 'Maroko', 'ma', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20910, 'mauritania', 'Mauritania', 'mr', 34, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20915, 'mauritius', 'Mauritius', 'mu', 76, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20920, 'meksiko', 'Meksiko', 'mx', 66, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20925, 'mesir', 'Mesir', 'eg', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20930, 'mikronesia', 'Mikronesia', 'fm', 50, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20935, 'moldova', 'Moldova', 'md', 54, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20940, 'monako', 'Monako', 'mc', 88, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20945, 'mongolia', 'Mongolia', 'mn', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20950, 'montenegro', 'Montenegro', 'me', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20955, 'mozambik', 'Mozambik', 'mz', 34, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20960, 'myanmar', 'Myanmar', 'mm', 24, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20965, 'namibia', 'Namibia', 'na', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20970, 'nauru', 'Nauru', 'nr', 46, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20975, 'nepal', 'Nepal', 'np', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20980, 'nikaragua', 'Nikaragua', 'ni', 32, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20985, 'niger', 'Niger', 'ne', 30, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20990, 'nigeria', 'Nigeria', 'ng', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20995, 'norwegia', 'Norwegia', 'no', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21000, 'oman', 'Oman', 'om', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21005, 'pakistan', 'Pakistan', 'pk', 44, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21010, 'palau', 'Palau', 'pw', 60, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21015, 'panama', 'Panama', 'pa', 74, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21020, 'papua_nugini', 'Papua nugini', 'pg', 46, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21025, 'paraguay', 'Paraguay', 'py', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21035, 'peru', 'Peru', 'pe', 68, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21040, 'polandia', 'Polandia', 'pl', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21045, 'portugal', 'Portugal', 'pt', 60, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21050, 'qatar', 'Qatar', 'qa', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21055, 'republik_afrika_tengah', 'Republik afrika tengah', 'cf', 24, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21060, 'republik_demokratik_kongo', 'Republik demokratik kongo', 'cd', 28, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21065, 'republik_dominika', 'Republik dominika', 'do', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21085, 'rusia', 'Rusia', 'ru', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21090, 'rwanda', 'Rwanda', 'rw', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21095, 'saint_kitts_dan_nevis', 'Saint kitts dan nevis', 'kn', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21100, 'saint_lucia', 'Saint lucia', 'lc', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21105, 'saint_vincent_dan_grenadine', 'Saint vincent dan grenadine', 'vc', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21110, 'samoa', 'Samoa', 'ws', 50, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21115, 'san_marino', 'San marino', 'sm', 76, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21120, 'sao_tome_dan_principe', 'Sao tome dan principe', 'st', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21125, 'selandia_baru', 'Selandia baru', 'nz', 82, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21130, 'senegal', 'Senegal', 'sn', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21135, 'republik_serbia', 'Republik serbia', 'rs', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21140, 'seychelles', 'Seychelles', 'sc', 68, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21145, 'sierra_leone', 'Sierra leone', 'sl', 34, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21150, 'singapura', 'Singapura', 'sg', 92, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21160, 'slovenia', 'Slovenia', 'si', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21170, 'somalia', 'Somalia', 'so', 45, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21175, 'spanyol', 'Spanyol', 'es', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21180, 'sri_lanka', 'Sri lanka', 'lk', 44, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21185, 'republik_sudan', 'Republik sudan', 'sd', 22, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21190, 'sudan_selatan', 'Sudan selatan', 'ss', 18, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21195, 'suriname', 'Suriname', 'sr', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21200, 'suriah', 'Suriah', 'sy', 16, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21205, 'swedia', 'Swedia', 'se', 65, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21210, 'swiss', 'Swiss', 'ch', 88, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21215, 'taiwan', 'Taiwan', 'tw', 80, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21220, 'tajikistan', 'Tajikistan', 'tj', 32, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21225, 'republik_tanzania', 'Republik tanzania', 'tz', 46, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21230, 'thailand', 'Thailand', 'th', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21235, 'republik_timor_leste', 'Republik timor leste', 'tl', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21240, 'togo', 'Togo', 'tg', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21245, 'tonga', 'Tonga', 'to', 50, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21250, 'trinidad_dan_tobago', 'Trinidad dan tobago', 'tt', 60, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21255, 'tunisia', 'Tunisia', 'tn', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21260, 'turki', 'Turki', 'tr', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21265, 'turkmenistan', 'Turkmenistan', 'tm', 15, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21270, 'tuvalu', 'Tuvalu', 'tv', 44, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21275, 'republik_uganda', 'Republik uganda', 'ug', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21280, 'ukraina', 'Ukraina', 'ua', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21285, 'uni_emirat_arab', 'Uni emirat arab', 'ae', 78, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21290, 'uruguay', 'Uruguay', 'uy', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21295, 'uzbekistan', 'Uzbekistan', 'uz', 36, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21300, 'vanuatu', 'Vanuatu', 'vu', 54, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21305, 'vatikan', 'Vatikan', 'va', 30, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21310, 'venezuela', 'Venezuela', 've', 12, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21315, 'vietnam', 'Vietnam', 'vn', 32, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21320, 'yaman', 'Yaman', 'ye', 20, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21325, 'yordania', 'Yordania', 'jo', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21330, 'yunani', 'Yunani', 'gr', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21335, 'republik_zambia', 'Republik zambia', 'zm', 46, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21340, 'republik_zimbabwe', 'Republik zimbabwe', 'zw', 28, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(10164, 'mayotte', 'Mayotte', 'yt', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(10165, 'reunion', 'Reunion', 're', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(70010, 'guadeloupe', 'Guadeloupe', 'gp', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(70011, 'martinique', 'Martinique', 'mq', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(70012, 'bonaire_sint_eustatius_dan_saba', 'Bonaire, Sint Eustatius dan Saba', 'bq', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(9450, 'kongo', 'Kongo', 'cg', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(66658, 'pantai_gading', 'Pantai gading', 'ci', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(70013, 'tanjung_verde', 'Tanjung verde', 'cv', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(93039, 'hong_kong', 'Hong kong', 'hk', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(76126, 'maldives', 'Maldives', 'mv', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(38423, 'palestina', 'Palestina', 'ps', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(70001, 'bosnia_dan_hercegovina', 'Bosnia dan hercegovina', 'ba', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(51812, 'gibraltar', 'Gibraltar', 'gi', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(93352, 'islandia', 'Islandia', 'is', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(40041, 'kepulauan_faroe', 'Kepulauan faroe', 'fo', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(17768, 'kosovo', 'Kosovo', 'xk', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(61324, 'lithuania', 'Lithuania', 'lt', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(3895, 'republik_rumania', 'Republik rumania', 'ro', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(92726, 'siprus', 'Siprus', 'cy', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(14492, 'slowakia', 'Slowakia', 'sk', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(54357, 'bermuda', 'Bermuda', 'bm', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(11770, 'costa_rica', 'Costa rica', 'cr', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(60907, 'curacao', 'Curacao', 'cw', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(18499, 'greenland', 'Greenland', 'gl', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(83966, 'puerto_rico', 'Puerto rico', 'pr', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(33529, 'guam', 'Guam', 'gu', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(70006, 'marshall', 'Marshall', 'mh', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(84512, 'samoa_amerika', 'Samoa amerika', 'ws', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(70012, 'tahiti', 'Tahiti', 'pf', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(70002, 'guiana_prancis', 'Guiana prancis', 'gf', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(93060, 'chad', 'Chad', 'td', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(67981, 'ceko', 'Ceko', 'cz', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(9760, 'prancis', 'Prancis', 'fr', 50, 'Belum tersedia', 'Belum tersedia', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas');
-- ========================================================
