-- ========================================================
-- DATABASE FITUR KEBIJAKAN & SISTEM EKONOMI DUNIA
-- File: d:\project-sendiri\em\json\database_sistem_ekonomi\database_sistem_ekonomi.sql
-- Description: Menyimpan data nilai spektrum sistem ekonomi (0-100), kartu kebijakan terpilih,
--              dan statistik indikator ekonomi untuk 207 negara.
-- ========================================================

DROP TABLE IF EXISTS `database_sistem_ekonomi`;
CREATE TABLE IF NOT EXISTS `database_sistem_ekonomi` (
    id INT AUTO_INCREMENT PRIMARY KEY,
    country_id INT NOT NULL,
    country_slug VARCHAR(100) NOT NULL,
    country_name VARCHAR(100) NOT NULL,
    iso VARCHAR(10) NOT NULL,
    spektrum_val INT NOT NULL DEFAULT 50, -- 0 (Terpusat/Komando) - 100 (Pasar Bebas/Laissez-Faire)
    system_title VARCHAR(100) NOT NULL,
    category ENUM('Terpusat', 'Campuran', 'Pasar Bebas') NOT NULL,
    policy_price_control ENUM('Terpusat', 'Pasar Bebas') NOT NULL DEFAULT 'Terpusat',
    policy_strategic_ownership ENUM('Terpusat', 'Pasar Bebas') NOT NULL DEFAULT 'Terpusat',
    policy_trade ENUM('Terpusat', 'Pasar Bebas') NOT NULL DEFAULT 'Pasar Bebas',
    policy_labor ENUM('Terpusat', 'Pasar Bebas') NOT NULL DEFAULT 'Pasar Bebas'
);

INSERT INTO database_sistem_ekonomi 
(country_id, country_slug, country_name, iso, spektrum_val, system_title, category, policy_price_control, policy_strategic_ownership, policy_trade, policy_labor) 
VALUES
(21869, 'afganistan', 'Afganistan', 'af', 15, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(29240, 'afrika-selatan', 'Afrika selatan', 'za', 65, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(93002, 'albania', 'Albania', 'al', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20793, 'aljazair', 'Aljazair', 'dz', 25, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20257, 'amerika-serikat', 'Amerika serikat', 'us', 88, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(34293, 'andorra', 'Andorra', 'ad', 72, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20427, 'angola', 'Angola', 'ao', 30, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas'),
(10222, 'antigua-dan-barbuda', 'Antigua dan barbuda', 'ag', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21021, 'arab-saudi', 'Arab saudi', 'sa', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20367, 'argentina', 'Argentina', 'ar', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20977, 'armenia', 'Armenia', 'am', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20448, 'australia', 'Australia', 'au', 82, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20456, 'austria', 'Austria', 'at', 55, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20835, 'azerbaijan', 'Azerbaijan', 'az', 35, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21714, 'bahama', 'Bahama', 'bs', 75, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20836, 'bahrain', 'Bahrain', 'bh', 68, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20465, 'bangladesh', 'Bangladesh', 'bd', 45, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20469, 'barbados', 'Barbados', 'bb', 60, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20474, 'belanda', 'Belanda', 'nl', 70, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20478, 'belarus', 'Belarus', 'by', 18, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20482, 'belgia', 'Belgia', 'be', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20486, 'belize', 'Belize', 'bz', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20490, 'benin', 'Benin', 'bj', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20494, 'bhutan', 'Bhutan', 'bt', 40, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20500, 'bolivia', 'Bolivia', 'bo', 28, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20505, 'bosnia-dan-herzegovina', 'Bosnia dan herzegovina', 'ba', 50, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20510, 'botswana', 'Botswana', 'bw', 66, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20515, 'brazil', 'Brazil', 'br', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20520, 'brunei', 'Brunei', 'bn', 32, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20525, 'bulgaria', 'Bulgaria', 'bg', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20530, 'burkina-faso', 'Burkina faso', 'bf', 36, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20535, 'burundi', 'Burundi', 'bi', 22, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20540, 'tchad', 'Chad', 'td', 20, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20545, 'chile', 'Chile', 'cl', 78, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20550, 'china', 'China', 'cn', 25, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20555, 'cyprus', 'Cyprus', 'cy', 70, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20560, 'denmark', 'Denmark', 'dk', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20565, 'djibouti', 'Djibouti', 'dj', 44, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20570, 'dominika', 'Dominika', 'dm', 54, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20575, 'ekuador', 'Ekuador', 'ec', 46, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20580, 'el-salvador', 'El salvador', 'sv', 68, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20585, 'eritrea', 'Eritrea', 'er', 12, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20590, 'estonia', 'Estonia', 'ee', 80, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20595, 'eswatini', 'Eswatini', 'sz', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20600, 'ethiopia', 'Ethiopia', 'et', 26, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20605, 'fiji', 'Fiji', 'fj', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20610, 'filipina', 'Filipina', 'ph', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20615, 'finlandia', 'Finlandia', 'fi', 60, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20620, 'gabon', 'Gabon', 'ga', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20625, 'gambia', 'Gambia', 'gm', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20630, 'georgia', 'Georgia', 'ge', 76, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20635, 'ghana', 'Ghana', 'gh', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20640, 'grenada', 'Grenada', 'gd', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20645, 'guatemala', 'Guatemala', 'gt', 66, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20650, 'guinea', 'Guinea', 'gn', 34, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20655, 'guinea-bissau', 'Guinea-bissau', 'gw', 30, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20660, 'guinea-khatulistiwa', 'Guinea khatulistiwa', 'gq', 24, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20665, 'guyana', 'Guyana', 'gy', 46, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20670, 'haiti', 'Haiti', 'ht', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20675, 'honduras', 'Honduras', 'hn', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20680, 'hungaria', 'Hungaria', 'hu', 54, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20685, 'india', 'India', 'in', 50, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20690, 'indonesia', 'Indonesia', 'id', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20695, 'inggris', 'Inggris', 'gb', 76, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20700, 'iran', 'Iran', 'ir', 20, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20705, 'irak', 'Irak', 'iq', 28, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20710, 'irlandia', 'Irlandia', 'ie', 84, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20715, 'israel', 'Israel', 'il', 72, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20720, 'italia', 'Italia', 'it', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20725, 'jamaika', 'Jamaika', 'jm', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20730, 'jepang', 'Jepang', 'jp', 68, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20735, 'jerman', 'Jerman', 'de', 65, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(20740, 'kamboja', 'Kamboja', 'kh', 44, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20745, 'kamerun', 'Kamerun', 'cm', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20750, 'kanada', 'Kanada', 'ca', 74, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20755, 'kazakhstan', 'Kazakhstan', 'kz', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20760, 'kenya', 'Kenya', 'ke', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20765, 'kirgizstan', 'Kirgizstan', 'kg', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20770, 'kiribati', 'Kiribati', 'ki', 36, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20775, 'kolombia', 'Kolombia', 'co', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20780, 'komoro', 'Komoro', 'km', 40, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20785, 'korea-selatan', 'Korea selatan', 'kr', 78, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20790, 'korea-utara', 'Korea utara', 'kp', 5, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20795, 'kosta-rika', 'Kosta rika', 'cr', 66, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20800, 'kroasia', 'Kroasia', 'hr', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20805, 'kuba', 'Kuba', 'cu', 14, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20810, 'kuwait', 'Kuwait', 'kw', 45, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20815, 'laos', 'Laos', 'la', 28, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20820, 'latvia', 'Latvia', 'lv', 72, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20825, 'lebanon', 'Lebanon', 'lb', 60, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20830, 'lesotho', 'Lesotho', 'ls', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20840, 'liberia', 'Liberia', 'lr', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20845, 'libya', 'Libya', 'ly', 22, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20850, 'liechtenstein', 'Liechtenstein', 'li', 90, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20855, 'lituania', 'Lituania', 'lt', 74, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20860, 'luksemburg', 'Luksemburg', 'lu', 82, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20865, 'madagaskar', 'Madagaskar', 'mg', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20870, 'makau', 'Makau', 'mo', 85, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20875, 'makedonia-utara', 'Makedonia utara', 'mk', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20880, 'malawi', 'Malawi', 'mw', 36, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20885, 'malaysia', 'Malaysia', 'my', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20890, 'maladewa', 'Maladewa', 'mv', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20895, 'mali', 'Mali', 'ml', 32, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20900, 'malta', 'Malta', 'mt', 72, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20905, 'maroko', 'Maroko', 'ma', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20910, 'mauritania', 'Mauritania', 'mr', 34, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20915, 'mauritius', 'Mauritius', 'mu', 76, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20920, 'meksiko', 'Meksiko', 'mx', 66, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20925, 'mesir', 'Mesir', 'eg', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20930, 'mikronesia', 'Mikronesia', 'fm', 50, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20935, 'moldova', 'Moldova', 'md', 54, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20940, 'monako', 'Monako', 'mc', 88, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20945, 'mongolia', 'Mongolia', 'mn', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20950, 'montenegro', 'Montenegro', 'me', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20955, 'mozambik', 'Mozambik', 'mz', 34, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20960, 'myanmar', 'Myanmar', 'mm', 24, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20965, 'namibia', 'Namibia', 'na', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20970, 'nauru', 'Nauru', 'nr', 46, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(20975, 'nepal', 'Nepal', 'np', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20980, 'nikaragua', 'Nikaragua', 'ni', 32, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(20985, 'niger', 'Niger', 'ne', 30, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(20990, 'nigeria', 'Nigeria', 'ng', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(20995, 'norwegia', 'Norwegia', 'no', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21000, 'oman', 'Oman', 'om', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21005, 'pakistan', 'Pakistan', 'pk', 44, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21010, 'palau', 'Palau', 'pw', 60, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21015, 'panama', 'Panama', 'pa', 74, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21020, 'papua-nugini', 'Papua nugini', 'pg', 46, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21025, 'paraguay', 'Paraguay', 'py', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21030, 'perancis', 'Prancis', 'fr', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21035, 'peru', 'Peru', 'pe', 68, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21040, 'polandia', 'Polandia', 'pl', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21045, 'portugal', 'Portugal', 'pt', 60, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21050, 'qatar', 'Qatar', 'qa', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21055, 'republik-afrika-tengah', 'Republik afrika tengah', 'cf', 24, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21060, 'republik-demokratik-kongo', 'Republik demokratik kongo', 'cd', 28, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21065, 'republik-dominika', 'Republik dominika', 'do', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21070, 'republik-kongo', 'Republik kongo', 'cg', 32, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21075, 'republik-ceko', 'Ceko', 'cz', 72, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21080, 'rumania', 'Rumania', 'ro', 66, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21085, 'rusia', 'Rusia', 'ru', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21090, 'rwanda', 'Rwanda', 'rw', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21095, 'saint-kitts-dan-nevis', 'Saint kitts dan nevis', 'kn', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21100, 'saint-lucia', 'Saint lucia', 'lc', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21105, 'saint-vincent-dan-grenadine', 'Saint vincent dan grenadine', 'vc', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21110, 'samoa', 'Samoa', 'ws', 50, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21115, 'san-marino', 'San marino', 'sm', 76, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21120, 'sao-tome-dan-principe', 'Sao tome dan principe', 'st', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21125, 'selandia-baru', 'Selandia baru', 'nz', 82, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21130, 'senegal', 'Senegal', 'sn', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21135, 'serbia', 'Serbia', 'rs', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21140, 'seychelles', 'Seychelles', 'sc', 68, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21145, 'sierra-leone', 'Sierra leone', 'sl', 34, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21150, 'singapura', 'Singapura', 'sg', 92, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21155, 'siprus-utara', 'Siprus utara', 'cy', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21160, 'slovenia', 'Slovenia', 'si', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21165, 'slovakia', 'Slovakia', 'sk', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21170, 'somalia', 'Somalia', 'so', 45, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21175, 'spanyol', 'Spanyol', 'es', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21180, 'sri-lanka', 'Sri lanka', 'lk', 44, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21185, 'sudan', 'Sudan', 'sd', 22, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21190, 'sudan-selatan', 'Sudan selatan', 'ss', 18, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21195, 'suriname', 'Suriname', 'sr', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21200, 'suriah', 'Suriah', 'sy', 16, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21205, 'swedia', 'Swedia', 'se', 65, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21210, 'swiss', 'Swiss', 'ch', 88, 'Laissez-Faire / Kapitalisme Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21215, 'taiwan', 'Taiwan', 'tw', 80, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21220, 'tajikistan', 'Tajikistan', 'tj', 32, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21225, 'tanzania', 'Tanzania', 'tz', 46, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21230, 'thailand', 'Thailand', 'th', 64, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21235, 'timor-leste', 'Timor leste', 'tl', 42, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21240, 'togo', 'Togo', 'tg', 38, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21245, 'tonga', 'Tonga', 'to', 50, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21250, 'trinidad-dan-tobago', 'Trinidad dan tobago', 'tt', 60, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21255, 'tunisia', 'Tunisia', 'tn', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21260, 'turki', 'Turki', 'tr', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21265, 'turkmenistan', 'Turkmenistan', 'tm', 15, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21270, 'tuvalu', 'Tuvalu', 'tv', 44, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21275, 'uganda', 'Uganda', 'ug', 52, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21280, 'ukraina', 'Ukraina', 'ua', 48, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21285, 'uni-emirat-arab', 'Uni emirat arab', 'ae', 78, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21290, 'uruguay', 'Uruguay', 'uy', 62, 'Pasar Bebas Terregulasi (Regulated Market)', 'Pasar Bebas', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21295, 'uzbekistan', 'Uzbekistan', 'uz', 36, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21300, 'vanuatu', 'Vanuatu', 'vu', 54, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21305, 'vatikan', 'Vatikan', 'va', 30, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21310, 'venezuela', 'Venezuela', 've', 12, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21315, 'vietnam', 'Vietnam', 'vn', 32, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Terpusat'),
(21320, 'yaman', 'Yaman', 'ye', 20, 'Ekonomi Komando (Command Economy)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat'),
(21325, 'yordania', 'Yordania', 'jo', 58, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Pasar Bebas'),
(21330, 'yunani', 'Yunani', 'gr', 56, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas', 'Terpusat'),
(21335, 'zambia', 'Zambia', 'zm', 46, 'Ekonomi Campuran (Mixed Economy)', 'Campuran', 'Terpusat', 'Terpusat', 'Pasar Bebas', 'Pasar Bebas'),
(21340, 'zimbabwe', 'Zimbabwe', 'zw', 28, 'Sosialisme Pasar (Market Socialism)', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat', 'Terpusat');
